package com.ai.aiga.domain;
// Generated 2017-2-21 15:55:52 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AigaOrganize generated by hbm2java
 */
@Entity
@Table(name="AIGA_ORGANIZE")
public class AigaOrganize  implements java.io.Serializable {


     private Long organizeId;
     private Long parentOrganizeId;
     private String organizeName;
     private String code;
     private Long orgRoleTypeId;
     private String districtId;
     private String shortName;
     private String englishName;
     private Integer memberNum;
     private String managerName;
     private String email;
     private String phoneId;
     private String faxId;
     private String orgAddress;
     private String contactName;
     private Integer contactCardType;
     private String contactCardId;
     private Integer postcode;
     private String contactBillId;
     private Long postProvince;
     private Long postCity;
     private String postAddress;
     private Integer postPostcod;
     private String notes;
     private Integer state;
     private Long doneCode;
     private Date createDate;
     private Date doneDate;
     private Date validDate;
     private Date expireDate;
     private Long opId;
     private Long orgId;
     private String oldCode;
     private String countyId;
     private String oldParentCode;
     private String ext1;
     private String ext2;
     private String ext3;
     private String sLeaf;

    public AigaOrganize() {
    }

	
    public AigaOrganize(Long organizeId, String sLeaf) {
        this.organizeId = organizeId;
        this.sLeaf = sLeaf;
    }
    public AigaOrganize(Long organizeId, Long parentOrganizeId, String organizeName, String code, Long orgRoleTypeId, String districtId, String shortName, String englishName, Integer memberNum, String managerName, String email, String phoneId, String faxId, String orgAddress, String contactName, Integer contactCardType, String contactCardId, Integer postcode, String contactBillId, Long postProvince, Long postCity, String postAddress, Integer postPostcod, String notes, Integer state, Long doneCode, Date createDate, Date doneDate, Date validDate, Date expireDate, Long opId, Long orgId, String oldCode, String countyId, String oldParentCode, String ext1, String ext2, String ext3, String sLeaf) {
       this.organizeId = organizeId;
       this.parentOrganizeId = parentOrganizeId;
       this.organizeName = organizeName;
       this.code = code;
       this.orgRoleTypeId = orgRoleTypeId;
       this.districtId = districtId;
       this.shortName = shortName;
       this.englishName = englishName;
       this.memberNum = memberNum;
       this.managerName = managerName;
       this.email = email;
       this.phoneId = phoneId;
       this.faxId = faxId;
       this.orgAddress = orgAddress;
       this.contactName = contactName;
       this.contactCardType = contactCardType;
       this.contactCardId = contactCardId;
       this.postcode = postcode;
       this.contactBillId = contactBillId;
       this.postProvince = postProvince;
       this.postCity = postCity;
       this.postAddress = postAddress;
       this.postPostcod = postPostcod;
       this.notes = notes;
       this.state = state;
       this.doneCode = doneCode;
       this.createDate = createDate;
       this.doneDate = doneDate;
       this.validDate = validDate;
       this.expireDate = expireDate;
       this.opId = opId;
       this.orgId = orgId;
       this.oldCode = oldCode;
       this.countyId = countyId;
       this.oldParentCode = oldParentCode;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
       this.sLeaf = sLeaf;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="AIGA_ORGANIZE$SEQ")
     @SequenceGenerator(name="AIGA_ORGANIZE$SEQ",sequenceName="AIGA_ORGANIZE$SEQ",allocationSize=1)
    @Column(name="ORGANIZE_ID", unique=true, nullable=false, precision=12, scale=0)
    public Long getOrganizeId() {
        return this.organizeId;
    }
    
    public void setOrganizeId(Long organizeId) {
        this.organizeId = organizeId;
    }
    
    @Column(name="PARENT_ORGANIZE_ID", precision=12, scale=0)
    public Long getParentOrganizeId() {
        return this.parentOrganizeId;
    }
    
    public void setParentOrganizeId(Long parentOrganizeId) {
        this.parentOrganizeId = parentOrganizeId;
    }
    
    @Column(name="ORGANIZE_NAME", length=200)
    public String getOrganizeName() {
        return this.organizeName;
    }
    
    public void setOrganizeName(String organizeName) {
        this.organizeName = organizeName;
    }
    
    @Column(name="CODE", length=100)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="ORG_ROLE_TYPE_ID", precision=12, scale=0)
    public Long getOrgRoleTypeId() {
        return this.orgRoleTypeId;
    }
    
    public void setOrgRoleTypeId(Long orgRoleTypeId) {
        this.orgRoleTypeId = orgRoleTypeId;
    }
    
    @Column(name="DISTRICT_ID", length=40)
    public String getDistrictId() {
        return this.districtId;
    }
    
    public void setDistrictId(String districtId) {
        this.districtId = districtId;
    }
    
    @Column(name="SHORT_NAME", length=2000)
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    
    @Column(name="ENGLISH_NAME", length=2000)
    public String getEnglishName() {
        return this.englishName;
    }
    
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }
    
    @Column(name="MEMBER_NUM", precision=6, scale=0)
    public Integer getMemberNum() {
        return this.memberNum;
    }
    
    public void setMemberNum(Integer memberNum) {
        this.memberNum = memberNum;
    }
    
    @Column(name="MANAGER_NAME", length=50)
    public String getManagerName() {
        return this.managerName;
    }
    
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }
    
    @Column(name="EMAIL", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="PHONE_ID", length=50)
    public String getPhoneId() {
        return this.phoneId;
    }
    
    public void setPhoneId(String phoneId) {
        this.phoneId = phoneId;
    }
    
    @Column(name="FAX_ID", length=50)
    public String getFaxId() {
        return this.faxId;
    }
    
    public void setFaxId(String faxId) {
        this.faxId = faxId;
    }
    
    @Column(name="ORG_ADDRESS", length=250)
    public String getOrgAddress() {
        return this.orgAddress;
    }
    
    public void setOrgAddress(String orgAddress) {
        this.orgAddress = orgAddress;
    }
    
    @Column(name="CONTACT_NAME", length=50)
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    
    @Column(name="CONTACT_CARD_TYPE", precision=2, scale=0)
    public Integer getContactCardType() {
        return this.contactCardType;
    }
    
    public void setContactCardType(Integer contactCardType) {
        this.contactCardType = contactCardType;
    }
    
    @Column(name="CONTACT_CARD_ID", length=40)
    public String getContactCardId() {
        return this.contactCardId;
    }
    
    public void setContactCardId(String contactCardId) {
        this.contactCardId = contactCardId;
    }
    
    @Column(name="POSTCODE", precision=6, scale=0)
    public Integer getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(Integer postcode) {
        this.postcode = postcode;
    }
    
    @Column(name="CONTACT_BILL_ID", length=40)
    public String getContactBillId() {
        return this.contactBillId;
    }
    
    public void setContactBillId(String contactBillId) {
        this.contactBillId = contactBillId;
    }
    
    @Column(name="POST_PROVINCE", precision=12, scale=0)
    public Long getPostProvince() {
        return this.postProvince;
    }
    
    public void setPostProvince(Long postProvince) {
        this.postProvince = postProvince;
    }
    
    @Column(name="POST_CITY", precision=12, scale=0)
    public Long getPostCity() {
        return this.postCity;
    }
    
    public void setPostCity(Long postCity) {
        this.postCity = postCity;
    }
    
    @Column(name="POST_ADDRESS")
    public String getPostAddress() {
        return this.postAddress;
    }
    
    public void setPostAddress(String postAddress) {
        this.postAddress = postAddress;
    }
    
    @Column(name="POST_POSTCOD", precision=6, scale=0)
    public Integer getPostPostcod() {
        return this.postPostcod;
    }
    
    public void setPostPostcod(Integer postPostcod) {
        this.postPostcod = postPostcod;
    }
    
    @Column(name="NOTES")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    @Column(name="STATE", precision=2, scale=0)
    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }
    
    @Column(name="DONE_CODE", precision=12, scale=0)
    public Long getDoneCode() {
        return this.doneCode;
    }
    
    public void setDoneCode(Long doneCode) {
        this.doneCode = doneCode;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DONE_DATE", length=7)
    public Date getDoneDate() {
        return this.doneDate;
    }
    
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="VALID_DATE", length=7)
    public Date getValidDate() {
        return this.validDate;
    }
    
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRE_DATE", length=7)
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
    
    @Column(name="OP_ID", precision=12, scale=0)
    public Long getOpId() {
        return this.opId;
    }
    
    public void setOpId(Long opId) {
        this.opId = opId;
    }
    
    @Column(name="ORG_ID", precision=12, scale=0)
    public Long getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }
    
    @Column(name="OLD_CODE")
    public String getOldCode() {
        return this.oldCode;
    }
    
    public void setOldCode(String oldCode) {
        this.oldCode = oldCode;
    }
    
    @Column(name="COUNTY_ID")
    public String getCountyId() {
        return this.countyId;
    }
    
    public void setCountyId(String countyId) {
        this.countyId = countyId;
    }
    
    @Column(name="OLD_PARENT_CODE")
    public String getOldParentCode() {
        return this.oldParentCode;
    }
    
    public void setOldParentCode(String oldParentCode) {
        this.oldParentCode = oldParentCode;
    }
    
    @Column(name="EXT1")
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT2")
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT3")
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }

    @Column(name="S_LEAF",  length=1)
	public String getsLeaf() {
		return sLeaf;
	}


	public void setsLeaf(String sLeaf) {
		this.sLeaf = sLeaf;
	}
    




}


