package com.ai.aiga.domain;
// Generated 2017-3-2 10:38:17 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AigaSubSysFolder generated by hbm2java
 */
@Entity
@Table(name = "AIGA_SUB_SYS_FOLDER")
public class AigaSubSysFolder implements java.io.Serializable {

	private BigDecimal subsysId;
	private String sysName;
	private Date createTime;
	private Date updateTime;
	private BigDecimal sysId;

	public AigaSubSysFolder() {
	}

	public AigaSubSysFolder(BigDecimal subsysId) {
		this.subsysId = subsysId;
	}

	public AigaSubSysFolder(BigDecimal subsysId, String sysName, Date createTime, Date updateTime, BigDecimal sysId) {
		this.subsysId = subsysId;
		this.sysName = sysName;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.sysId = sysId;
	}

	@Id

	@Column(name = "SUBSYS_ID", unique = true, nullable = false, precision = 20, scale = 0)
	public BigDecimal getSubsysId() {
		return this.subsysId;
	}

	public void setSubsysId(BigDecimal subsysId) {
		this.subsysId = subsysId;
	}

	@Column(name = "SYS_NAME", length = 2000)
	public String getSysName() {
		return this.sysName;
	}

	public void setSysName(String sysName) {
		this.sysName = sysName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "SYS_ID", precision = 20, scale = 0)
	public BigDecimal getSysId() {
		return this.sysId;
	}

	public void setSysId(BigDecimal sysId) {
		this.sysId = sysId;
	}

}
