package com.ai.aiga.domain;


/**
 * ArchAigaFunction generated by hbm2java
 */

public class ArchAigaFunctionTime {


     private String applyTime;
     private String modifyDate;

     public ArchAigaFunctionTime() {

     }
     
    public ArchAigaFunctionTime(String applyTime, String modifyDate) {
       super();
       this.applyTime = applyTime;
       this.modifyDate = modifyDate;

    }

    public String getApplyTime() {
        return this.applyTime;
    }
    
    public void setApplyTime(String applyTime) {
        this.applyTime = applyTime;
    }
    
    public String getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(String modifyDate) {
        this.modifyDate = modifyDate;
    }
    
    
}


