package com.ai.aiga.domain;
// Generated 2017-9-7 14:24:34 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchiTopList generated by hbm2java
 */
@Entity
@Table(name="ARCHI_TOP_LIST"
)
public class ArchiTopList  implements java.io.Serializable {


     private long indexId;
     private Long indexSeq;
     private String indexName;
     private String indexGroup;
     private String settMonth;
     private String key1;
     private String key2;
     private String key3;
     private Long resultValue;
     private String imgSrc;
     private Byte starNum;
     private Date createDate;

    public ArchiTopList() {
    }

	
    public ArchiTopList(long indexId) {
        this.indexId = indexId;
    }
    public ArchiTopList(long indexId, Long indexSeq, String indexName, String indexGroup, String settMonth, String key1, String key2, String key3, Long resultValue, String imgSrc, Byte starNum, Date createDate) {
       this.indexId = indexId;
       this.indexSeq = indexSeq;
       this.indexName = indexName;
       this.indexGroup = indexGroup;
       this.settMonth = settMonth;
       this.key1 = key1;
       this.key2 = key2;
       this.key3 = key3;
       this.resultValue = resultValue;
       this.imgSrc = imgSrc;
       this.starNum = starNum;
       this.createDate = createDate;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="ARCHI_TOP_LIST$SEQ")
    @SequenceGenerator(name="ARCHI_TOP_LIST$SEQ",sequenceName="ARCHI_TOP_LIST$SEQ",allocationSize=1)
    @Column(name="INDEX_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getIndexId() {
        return this.indexId;
    }
    
    public void setIndexId(long indexId) {
        this.indexId = indexId;
    }
    
    @Column(name="INDEX_SEQ", precision=10, scale=0)
    public Long getIndexSeq() {
        return this.indexSeq;
    }
    
    public void setIndexSeq(Long indexSeq) {
        this.indexSeq = indexSeq;
    }
    
    @Column(name="INDEX_NAME", length=100)
    public String getIndexName() {
        return this.indexName;
    }
    
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }
    
    @Column(name="INDEX_GROUP", length=100)
    public String getIndexGroup() {
        return this.indexGroup;
    }
    
    public void setIndexGroup(String indexGroup) {
        this.indexGroup = indexGroup;
    }
    
    @Column(name="SETT_MONTH", length=10)
    public String getSettMonth() {
        return this.settMonth;
    }
    
    public void setSettMonth(String settMonth) {
        this.settMonth = settMonth;
    }
    
    @Column(name="KEY_1", length=100)
    public String getKey1() {
        return this.key1;
    }
    
    public void setKey1(String key1) {
        this.key1 = key1;
    }
    
    @Column(name="KEY_2", length=100)
    public String getKey2() {
        return this.key2;
    }
    
    public void setKey2(String key2) {
        this.key2 = key2;
    }
    
    @Column(name="KEY_3", length=100)
    public String getKey3() {
        return this.key3;
    }
    
    public void setKey3(String key3) {
        this.key3 = key3;
    }
    
    @Column(name="RESULT_VALUE", precision=10, scale=0)
    public Long getResultValue() {
        return this.resultValue;
    }
    
    public void setResultValue(Long resultValue) {
        this.resultValue = resultValue;
    }
    
    @Column(name="IMG_SRC", length=100)
    public String getImgSrc() {
        return this.imgSrc;
    }
    
    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc;
    }
    
    @Column(name="STAR_NUM", precision=2, scale=0)
    public Byte getStarNum() {
        return this.starNum;
    }
    
    public void setStarNum(Byte starNum) {
        this.starNum = starNum;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}


