package com.ai.aiga.domain;
// Generated 2017-8-24 16:24:56 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchiOnlinePlan generated by hbm2java
 */
@Entity
@Table(name="ARCHI_ONLINE_PLAN")
public class ArchiOnlinePlan  implements java.io.Serializable {


     private Date onlineTime;
     private Date creatTime;
     private String ext1;
     private String ext2;
     private String ext3;

    public ArchiOnlinePlan() {
    }

	
    public ArchiOnlinePlan(Date onlineTime) {
        this.onlineTime = onlineTime;
    }
    public ArchiOnlinePlan(Date onlineTime, Date creatTime, String ext1, String ext2, String ext3) {
       this.onlineTime = onlineTime;
       this.creatTime = creatTime;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ONLINE_TIME", unique=true, nullable=false, length=7)
    public Date getOnlineTime() {
        return this.onlineTime;
    }
    
    public void setOnlineTime(Date onlineTime) {
        this.onlineTime = onlineTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREAT_TIME", length=7)
    public Date getCreatTime() {
        return this.creatTime;
    }
    
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }
    
    @Column(name="EXT_1")
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2")
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3")
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


