package com.ai.aiga.domain;
// Generated 2018-3-6 15:02:07 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchSvnDbcp generated by hbm2java
 */
@Entity
@Table(name="ARCH_DCOS_DATA")
public class ArchDcosData  implements java.io.Serializable {

	private Long indexId;
	private String settMonth;
	private String key1;
	private String key2;
	private String key3;
	private String resultValue;
	private Long groupId;
	private Date insertTime;
	
    public ArchDcosData() {
    }

   public ArchDcosData(Long indexId, String settMonth, String key1, String key2, String key3, String resultValue, Long groupId, Date insertTime) {
	  super();
	  this.indexId = indexId;
      this.settMonth = settMonth;
      this.key1 = key1;
      this.key2 = key2;
      this.key3 = key3;
      this.resultValue = resultValue;
      this.groupId = groupId;
      this.insertTime = insertTime;
   }
   
    @Id
    @Column(name="INDEX_ID", precision=12, scale=0)
	public Long getIndexId() {
		return indexId;
	}
	
	public void setIndexId(Long indexId) {
		this.indexId = indexId;
	}
	   
	@Column(name="SETT_MONTH", length=12)
	public String getSettMonth() {
		return settMonth;
	}
	
	public void setSettMonth(String settMonth) {
		this.settMonth = settMonth;
	}
	   
	@Column(name="KEY_1", length=100)
	public String getKey1() {
		return key1;
	}
	
	public void setKey1(String key1) {
		this.key1 = key1;
	}
	
	@Column(name="KEY_2", length=100)
	public String getKey2() {
		return key2;
	}
	
	public void setKey2(String key2) {
		this.key2 = key2;
	}
	
	@Column(name="KEY_3", length=100)
	public String getKey3() {
		return key3;
	}
	
	public void setKey3(String key3) {
		this.key3 = key3;
	}
	
	@Column(name="RESULT_VALUE", length=100)
	public String getResultValue() {
		return resultValue;
	}
	
	public void setResultValue(String resultValue) {
		this.resultValue = resultValue;
	}
	
    @Column(name="GROUP_ID", precision=12, scale=0)
	public Long getGroupId() {
		return groupId;
	}
	
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}
	
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INSERT_TIME", nullable=false, length=7)
	public Date getInsertTime() {
		return insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}
   
	
}


