package com.ai.aiga.domain;
// Generated 2018-1-29 15:02:07 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArchSvnDbcp generated by hbm2java
 */
@Entity
@Table(name="ARCH_SVN_DBCP")
public class ArchSvnDbcp  implements java.io.Serializable {

    private String center;
    private String module;
    private String db;
    private Long initialSize;
    private Long maxActive;
    private Long maxIdle;
    private Long minIdle;
    private Long maxWait;
    private Date insertTime;

    public ArchSvnDbcp() {
    }

   public ArchSvnDbcp(String center, String module, String db, Long initialSize, Long maxActive, Long maxIdle, Long minIdle, Long maxWait, Date insertTime) {
	  super();
	  this.center = center;
      this.module = module;
      this.db = db;
      this.initialSize = initialSize;
      this.maxActive = maxActive;
      this.maxIdle = maxIdle;
      this.minIdle = minIdle;
      this.maxWait = maxWait;
      this.insertTime = insertTime;
   }
  
   @Id
   @Column(name="CENTER", length=32)
   public String getCenter() {
       return this.center;
   }
   
   public void setCenter(String center) {
       this.center = center;
   }

   @Column(name="MODULE", length=32)
   public String getModule() {
       return this.module;
   }
   
   public void setModule(String module) {
       this.module = module;
   }

   @Column(name="DB", length=16)
   public String getDb() {
       return this.db;
   }
   
   public void setDb(String db) {
       this.db = db;
   }

   @Column(name="INITIAL_SIZE", precision=10, scale=0)
   public Long getInitialSize() {
       return this.initialSize;
   }
   
   public void setInitialSize(Long initialSize) {
       this.initialSize = initialSize;
   }

   @Column(name="MAX_ACTIVE", precision=10, scale=0)
   public Long getMaxActive() {
       return this.maxActive;
   }
   
   public void setMaxActive(Long maxActive) {
       this.maxActive = maxActive;
   }

   @Column(name="MAX_IDLE", precision=10, scale=0)
   public Long getMaxIdle() {
       return this.maxIdle;
   }
   
   public void setMaxIdle(Long maxIdle) {
       this.maxIdle = maxIdle;
   }

   @Column(name="MIN_IDLE", precision=10, scale=0)
   public Long getMinIdle() {
       return this.minIdle;
   }
   
   public void setMinIdle(Long minIdle) {
       this.minIdle = minIdle;
   }

   @Column(name="MAX_WAIT", precision=10, scale=0)
   public Long getMaxWait() {
       return this.maxWait;
   }
   
   public void setMaxWait(Long maxWait) {
       this.maxWait = maxWait;
   }

   @Column(name="INSERT_TIME", length=7)
   public Date getInsertTime() {
       return this.insertTime;
   }
   
   public void setInsertTime(Date insertTime) {
       this.insertTime = insertTime;
   }

}


