package com.ai.aiga.domain;
// Generated 2018-3-19 15:02:07 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchSvnDbcp generated by hbm2java
 */
@Entity
@Table(name="ARCH_BUSI_ERRCODE_MAP")
public class ArchBusiErrcodeMap  implements java.io.Serializable {

	private Date insertTime;
    private String person;
    private String center;
    private String dataResource;
    private Long errcodeMapId;
    private String csfServiceCode;
    private String i18nErrcode;
    private String i18nErrcodeDesc;
    private String esbErrcode;
    private String esbErrcodeDesc;
    private String csfErrcode;
    private String csfErrcodeDesc;
    private Date createDate;
    private Date stateDate;
    private char state;
    private String remarks;
    private String checkResult;
    
    public ArchBusiErrcodeMap() {
    }

   public ArchBusiErrcodeMap(Date insertTime, String person, String center, String dataResource, Long errcodeMapId, String csfServiceCode, String i18nErrcode, String i18nErrcodeDesc, String esbErrcode, String esbErrcodeDesc, String csfErrcode, String csfErrcodeDesc, Date createDate, Date stateDate, char state, String remarks, String checkResult) {
	  super();
	  this.insertTime = insertTime;
      this.person = person;
      this.center = center;
      this.dataResource = dataResource;
      this.errcodeMapId = errcodeMapId;
      this.csfServiceCode = csfServiceCode;
      this.i18nErrcode = i18nErrcode;
      this.i18nErrcodeDesc = i18nErrcodeDesc;
      this.esbErrcode = esbErrcode;
      this.esbErrcodeDesc = esbErrcodeDesc;
      this.csfErrcode = csfErrcode;
      this.csfErrcodeDesc = csfErrcodeDesc;
      this.createDate = createDate;
      this.stateDate = stateDate;
      this.state = state;
      this.remarks = remarks;
      this.checkResult = checkResult;
   }
   
    @Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INSERT_TIME", nullable=false, length=7)
	public Date getInsertTime() {
		return insertTime;
	}
	
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}
	
	@Column(name="PERSON", length=256)
	public String getPerson() {
		return person;
	}
	
	public void setPerson(String person) {
		this.person = person;
	}
	
	@Column(name="CENTER", length=256)
	public String getCenter() {
		return center;
	}
	
	public void setCenter(String center) {
		this.center = center;
	}
	
	@Column(name="DATA_RESOURCE", length=256)
	public String getDataResource() {
		return dataResource;
	}
	
	public void setDataResource(String dataResource) {
		this.dataResource = dataResource;
	}
	
    @Column(name="ERRCODE_MAP_ID", precision=12, scale=0)
	public Long getErrcodeMapId() {
		return errcodeMapId;
	}
	
	public void setErrcodeMapId(Long errcodeMapId) {
		this.errcodeMapId = errcodeMapId;
	}
	
	@Column(name="CSF_SERVICE_CODE", length=128)
	public String getCsfServiceCode() {
		return csfServiceCode;
	}
	
	public void setCsfServiceCode(String csfServiceCode) {
		this.csfServiceCode = csfServiceCode;
	}
	
	@Column(name="I18N_ERRCODE", length=128)
	public String getI18nErrcode() {
		return i18nErrcode;
	}
	
	public void setI18nErrcode(String i18nErrcode) {
		this.i18nErrcode = i18nErrcode;
	}
	
	@Column(name="I18N_ERRCODE_DESC", length=256)
	public String getI18nErrcodeDesc() {
		return i18nErrcodeDesc;
	}
	
	public void setI18nErrcodeDesc(String i18nErrcodeDesc) {
		this.i18nErrcodeDesc = i18nErrcodeDesc;
	}
	
	@Column(name="ESB_ERRCODE", length=128)
	public String getEsbErrcode() {
		return esbErrcode;
	}
	
	public void setEsbErrcode(String esbErrcode) {
		this.esbErrcode = esbErrcode;
	}
	
	@Column(name="ESB_ERRCODE_DESC", length=256)
	public String getEsbErrcodeDesc() {
		return esbErrcodeDesc;
	}
	
	public void setEsbErrcodeDesc(String esbErrcodeDesc) {
		this.esbErrcodeDesc = esbErrcodeDesc;
	}
	
	@Column(name="CSF_ERRCODE", length=128)
	public String getCsfErrcode() {
		return csfErrcode;
	}
	
	public void setCsfErrcode(String csfErrcode) {
		this.csfErrcode = csfErrcode;
	}
	
	@Column(name="CSF_ERRCODE_DESC", length=256)
	public String getCsfErrcodeDesc() {
		return csfErrcodeDesc;
	}
	
	public void setCsfErrcodeDesc(String csfErrcodeDesc) {
		this.csfErrcodeDesc = csfErrcodeDesc;
	}
	
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
	public Date getCreateDate() {
		return createDate;
	}
	
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STATE_DATE", nullable=false, length=7)
	public Date getStateDate() {
		return stateDate;
	}
	
	public void setStateDate(Date stateDate) {
		this.stateDate = stateDate;
	}
	
	@Column(name="STATE", length=1)
	public char getState() {
		return state;
	}
	
	public void setState(char state) {
		this.state = state;
	}
	
	@Column(name="REMARKS", length=512)
	public String getRemarks() {
		return remarks;
	}
	
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	
	@Column(name="CHECK_RESULT", length=128)
	public String getCheckResult() {
		return checkResult;
	}

	public void setCheckResult(String checkResult) {
		this.checkResult = checkResult;
	}
	
}


