package com.ai.aiga.domain;
// Generated 2018-3-30 14:30:39 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchTaskPlan generated by hbm2java
 */
@Entity
@Table(name="ARCH_TASK_PLAN")
public class ArchTaskPlan  implements java.io.Serializable {


     private long taskId;
     private String taskName;
     private String taskDesc;
     private String classPath;
     private String cronexpression;
     private String param1;
     private String param2;
     private String param3;
     private String param4;
     private String param5;
     private Date createDate;
     private Character state;
     private String ext1;
     private String ext2;
     private String ext3;

    public ArchTaskPlan() {
    }

	
    public ArchTaskPlan(long taskId, String taskName, String classPath, String cronexpression, Date createDate) {
        this.taskId = taskId;
        this.taskName = taskName;
        this.classPath = classPath;
        this.cronexpression = cronexpression;
        this.createDate = createDate;
    }
    public ArchTaskPlan(long taskId, String taskName, String taskDesc, String classPath, String cronexpression, String param1, String param2, String param3, String param4, String param5, Date createDate, Character state, String ext1, String ext2, String ext3) {
       this.taskId = taskId;
       this.taskName = taskName;
       this.taskDesc = taskDesc;
       this.classPath = classPath;
       this.cronexpression = cronexpression;
       this.param1 = param1;
       this.param2 = param2;
       this.param3 = param3;
       this.param4 = param4;
       this.param5 = param5;
       this.createDate = createDate;
       this.state = state;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
    
    @Column(name="TASK_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(long taskId) {
        this.taskId = taskId;
    }
    
    @Column(name="TASK_NAME", nullable=false)
    public String getTaskName() {
        return this.taskName;
    }
    
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }
    
    @Column(name="TASK_DESC", length=1000)
    public String getTaskDesc() {
        return this.taskDesc;
    }
    
    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc;
    }
    
    @Column(name="CLASS_PATH", nullable=false, length=1000)
    public String getClassPath() {
        return this.classPath;
    }
    
    public void setClassPath(String classPath) {
        this.classPath = classPath;
    }
    
    @Column(name="CRONEXPRESSION", nullable=false)
    public String getCronexpression() {
        return this.cronexpression;
    }
    
    public void setCronexpression(String cronexpression) {
        this.cronexpression = cronexpression;
    }
    
    @Column(name="PARAM1", length=500)
    public String getParam1() {
        return this.param1;
    }
    
    public void setParam1(String param1) {
        this.param1 = param1;
    }
    
    @Column(name="PARAM2", length=500)
    public String getParam2() {
        return this.param2;
    }
    
    public void setParam2(String param2) {
        this.param2 = param2;
    }
    
    @Column(name="PARAM3", length=500)
    public String getParam3() {
        return this.param3;
    }
    
    public void setParam3(String param3) {
        this.param3 = param3;
    }
    
    @Column(name="PARAM4", length=500)
    public String getParam4() {
        return this.param4;
    }
    
    public void setParam4(String param4) {
        this.param4 = param4;
    }
    
    @Column(name="PARAM5", length=500)
    public String getParam5() {
        return this.param5;
    }
    
    public void setParam5(String param5) {
        this.param5 = param5;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    @Column(name="STATE", length=1)
    public Character getState() {
        return this.state;
    }
    
    public void setState(Character state) {
        this.state = state;
    }
    
    @Column(name="EXT1", length=500)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT2", length=500)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT3", length=500)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


