package com.ai.aiga.domain;
// Generated 2018-1-26 10:18:51 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchFunctionRecord generated by hbm2java
 */
@Entity
@Table(name="ARCH_FUNCTION_RECORD")
public class ArchFunctionRecord  implements java.io.Serializable {


     private long recordId;
     private String menuUrl;
     private String menuCode;
     private String menuName;
     private String userCode;
     private String userName;
     private Date recordTime;
     private String ext1;
     private String ext2;
     private String ext3;

    public ArchFunctionRecord() {
    }

	
    public ArchFunctionRecord(long recordId, String menuUrl) {
        this.recordId = recordId;
        this.menuUrl = menuUrl;
    }
    public ArchFunctionRecord(long recordId, String menuUrl, String menuCode, String menuName, String userCode, String userName, Date recordTime, String ext1, String ext2, String ext3) {
       this.recordId = recordId;
       this.menuUrl = menuUrl;
       this.menuCode = menuCode;
       this.menuName = menuName;
       this.userCode = userCode;
       this.userName = userName;
       this.recordTime = recordTime;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="ARCH_FUNCTION_RECORD$SEQ")
     @SequenceGenerator(name="ARCH_FUNCTION_RECORD$SEQ",sequenceName="ARCH_FUNCTION_RECORD$SEQ",allocationSize=1)     
    @Column(name="RECORD_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(long recordId) {
        this.recordId = recordId;
    }
    
    @Column(name="MENU_URL", nullable=false)
    public String getMenuUrl() {
        return this.menuUrl;
    }
    
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }
    
    @Column(name="MENU_CODE")
    public String getMenuCode() {
        return this.menuCode;
    }
    
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }
    
    @Column(name="MENU_NAME")
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    
    @Column(name="USER_CODE")
    public String getUserCode() {
        return this.userCode;
    }
    
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }
    
    @Column(name="USER_NAME")
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORD_TIME", length=7)
    public Date getRecordTime() {
        return this.recordTime;
    }
    
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
    
    @Column(name="EXT_1")
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2")
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3")
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


