package com.ai.aiga.domain;
// Generated 2017-12-5 15:08:40 by Hibernate Tools 3.2.2.GA



/**
 * ArchAigaFunction generated by hbm2java
 */

public class ArchAigaFunction  implements java.io.Serializable {


     private long applycount;
     private long tongguo;
     private long bohui;
     private long xinzeng;
     private long yewu;
     private long guanxin;
     private long bomc;
     private long shuju;
     private long anquan;
     private long gonggong;
     private long wangluo;
     private long dishi;
     private long kaifang;

    public ArchAigaFunction(long applycount, long tongguo, long bohui, long xinzeng, long yewu, long guanxin, long bomc, long shuju, long anquan, long gonggong, long wangluo, long dishi, long kaifang) {
       super();
       this.applycount = applycount;
       this.tongguo = tongguo;
       this.bohui = bohui;
       this.xinzeng = xinzeng;
       this.yewu = yewu;
       this.guanxin = guanxin;
       this.bomc = bomc;
       this.shuju = shuju;
       this.anquan = anquan;
       this.gonggong = gonggong;
       this.wangluo = wangluo;
       this.dishi = dishi;
       this.kaifang = kaifang;
    }

    public ArchAigaFunction() {
    	super();
    }
}


