package com.ai.aiga.domain;
// Generated 2018-1-29 15:02:07 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchSvnDbcp generated by hbm2java
 */
@Entity
@Table(name="ARCH_SVN_DBCP")
public class ArchSvnDbcpTwo  implements java.io.Serializable {

    private Long successCollect;
    private Long total;
    private Long change;


    public ArchSvnDbcpTwo() {
    }

   public ArchSvnDbcpTwo(Long successCollect, Long total, Long change) {
	  super();
      this.successCollect = successCollect;
      this.total = total;
      this.change = change;
   }

	public Long getSuccessCollect() {
		return successCollect;
	}
	
	public void setSuccessCollect(Long successCollect) {
		this.successCollect = successCollect;
	}
	
	public Long getTotal() {
		return total;
	}
	
	public void setTotal(Long total) {
		this.total = total;
	}
	
	public Long getChange() {
		return change;
	}
	
	public void setChange(Long change) {
		this.change = change;
	}
  
}


