package com.ai.aiga.domain;
// Generated 2017-12-5 15:08:40 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Workplan generated by hbm2java
 */
@Entity
@Table(name="arch_notice_title")
public class ArchNoticeTitle  implements java.io.Serializable {


     private long id;
     private String noticeTitle;
     private String noticeDescription;
     private String noticeDetails;


    public ArchNoticeTitle() {
    }

	
    public ArchNoticeTitle(long id, String noticeTitle) {
        this.id = id;
        this.noticeTitle = noticeTitle;
    }
    public ArchNoticeTitle(long id, String noticeTitle,  String noticeDescription, String noticeDetails) {
       this.id = id;
       this.noticeTitle = noticeTitle;
       this.noticeDescription = noticeDescription;
       this.noticeDetails = noticeDetails;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="arch_notice_title$SEQ")
     @SequenceGenerator(name="arch_notice_title$SEQ",sequenceName="arch_notice_title$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="NOTICE_TITLE", length=100)
    public String getNoticeTitle() {
        return this.noticeTitle;
    }
    
    public void setNoticeTitle(String noticeTitle) {
        this.noticeTitle = noticeTitle;
    }
    
    @Column(name="NOTICE_DESCRIPTION",  length=20)
    public String getNoticeDescription() {
        return this.noticeDescription;
    }
    
    public void setNoticeDescription(String noticeDescription) {
        this.noticeDescription = noticeDescription;
    }
    
    @Column(name="NOTICE_DETAILS",  length=10)
    public String getNoticeDetails() {
        return this.noticeDetails;
    }
    
    public void setNoticeDetails(String noticeDetails) {
        this.noticeDetails = noticeDetails;
    }


}


