package com.ai.aiga.domain;
// Generated 2018-5-2 16:35:47 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchStaffGrad generated by hbm2java
 */
@Entity
@Table(name="ARCH_STAFF_GRAD")
public class ArchStaffGrad  implements java.io.Serializable {


     private long applyId;
     private String staffCode;
     private String staffName;
     private String staffPassword;
     private String email;
     private String billId;
     private String roleId;
     private String organizeId;
     private String organizeName;
     private String state;
     private String gradingPerson;
     private Date createDate;
     private Date modifyDate;
     private String ext1;
     private String ext2;
     private String ext3;

    public ArchStaffGrad() {
    }

	
    public ArchStaffGrad(long applyId, String staffCode, String staffName, String staffPassword, String email, String billId) {
        this.applyId = applyId;
        this.staffCode = staffCode;
        this.staffName = staffName;
        this.staffPassword = staffPassword;
        this.email = email;
        this.billId = billId;
    }
    public ArchStaffGrad(long applyId, String staffCode, String staffName, String staffPassword, String email, String billId, String roleId, String organizeId, String organizeName, String state, String gradingPerson, Date createDate, Date modifyDate, String ext1, String ext2, String ext3) {
       this.applyId = applyId;
       this.staffCode = staffCode;
       this.staffName = staffName;
       this.staffPassword = staffPassword;
       this.email = email;
       this.billId = billId;
       this.roleId = roleId;
       this.organizeId = organizeId;
       this.organizeName = organizeName;
       this.state = state;
       this.gradingPerson = gradingPerson;
       this.createDate = createDate;
       this.modifyDate = modifyDate;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="ARCH_STAFF_GRAD$SEQ")
     @SequenceGenerator(name="ARCH_STAFF_GRAD$SEQ",sequenceName="ARCH_STAFF_GRAD$SEQ",allocationSize=1)    
    @Column(name="APPLY_ID", unique=true, nullable=false, precision=12, scale=0)
    public long getApplyId() {
        return this.applyId;
    }
    
    public void setApplyId(long applyId) {
        this.applyId = applyId;
    }
    
    @Column(name="STAFF_CODE", nullable=false)
    public String getStaffCode() {
        return this.staffCode;
    }
    
    public void setStaffCode(String staffCode) {
        this.staffCode = staffCode;
    }
    
    @Column(name="STAFF_NAME", nullable=false)
    public String getStaffName() {
        return this.staffName;
    }
    
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }
    
    @Column(name="STAFF_PASSWORD", nullable=false)
    public String getStaffPassword() {
        return this.staffPassword;
    }
    
    public void setStaffPassword(String staffPassword) {
        this.staffPassword = staffPassword;
    }
    
    @Column(name="EMAIL", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="BILL_ID", nullable=false)
    public String getBillId() {
        return this.billId;
    }
    
    public void setBillId(String billId) {
        this.billId = billId;
    }
    
    @Column(name="ROLE_ID")
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    
    @Column(name="ORGANIZE_ID")
    public String getOrganizeId() {
        return this.organizeId;
    }
    
    public void setOrganizeId(String organizeId) {
        this.organizeId = organizeId;
    }
    
    @Column(name="ORGANIZE_NAME")
    public String getOrganizeName() {
        return this.organizeName;
    }
    
    public void setOrganizeName(String organizeName) {
        this.organizeName = organizeName;
    }
    
    @Column(name="STATE", length=50)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="GRADING_PERSON")
    public String getGradingPerson() {
        return this.gradingPerson;
    }
    
    public void setGradingPerson(String gradingPerson) {
        this.gradingPerson = gradingPerson;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_DATE", length=7)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
    
    @Column(name="EXT1", length=500)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT2", length=500)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT3", length=500)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


