package com.ai.aiga.domain;
// Generated 2017-8-25 16:48:34 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchiSysHealthReport generated by hbm2java
 */
@Entity
@Table(name="ARCHI_SYS_HEALTH_REPORT")
public class ArchiSysHealthReport  implements java.io.Serializable {


     private long reportId;
     private Long onlysysId;
     private Date time;
     private String type;
     private String key;
     private String value;
     private Date creatTime;
     private String ext1;
     private String ext2;
     private String ext3;

    public ArchiSysHealthReport() {
    }

	
    public ArchiSysHealthReport(long reportId) {
        this.reportId = reportId;
    }
    public ArchiSysHealthReport(long reportId, Long onlysysId, Date time, String type, String key, String value, Date creatTime, String ext1, String ext2, String ext3) {
       this.reportId = reportId;
       this.onlysysId = onlysysId;
       this.time = time;
       this.type = type;
       this.key = key;
       this.value = value;
       this.creatTime = creatTime;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="ARCHI_SYS_HEALTH_REPORT$SEQ")
     @SequenceGenerator(name="ARCHI_SYS_HEALTH_REPORT$SEQ",sequenceName="ARCHI_SYS_HEALTH_REPORT$SEQ",allocationSize=1)  
    @Column(name="REPORT_ID", unique=true, nullable=false, precision=12, scale=0)
    public long getReportId() {
        return this.reportId;
    }
    
    public void setReportId(long reportId) {
        this.reportId = reportId;
    }
    
    @Column(name="ONLYSYS_ID", precision=12, scale=0)
    public Long getOnlysysId() {
        return this.onlysysId;
    }
    
    public void setOnlysysId(Long onlysysId) {
        this.onlysysId = onlysysId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIME", length=7)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    
    @Column(name="TYPE", length=10)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="KEY")
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    
    @Column(name="VALUE")
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREAT_TIME", length=7)
    public Date getCreatTime() {
        return this.creatTime;
    }
    
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }
    
    @Column(name="EXT_1")
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2")
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3")
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


