package com.ai.aiga.domain;
// Generated 2017-8-18 15:18:08 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ArchiSysIndexRela generated by hbm2java
 */
@Entity
@Table(name="ARCHI_SYS_INDEX_RELA")
public class ArchiSysIndexRela  implements java.io.Serializable {


     private long realId;
     private Long onlysysId;
     private Long indexId;
     private String indexName;
     private Character state;
     private String ext1;
     private String ext2;
     private String ext3;
     private String ext4;
     private String ext5;

    public ArchiSysIndexRela() {
    }

	
    public ArchiSysIndexRela(long realId) {
        this.realId = realId;
    }
    public ArchiSysIndexRela(long realId, Long onlysysId, Long indexId, String indexName, Character state, String ext1, String ext2, String ext3, String ext4, String ext5) {
       this.realId = realId;
       this.onlysysId = onlysysId;
       this.indexId = indexId;
       this.indexName = indexName;
       this.state = state;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
       this.ext4 = ext4;
       this.ext5 = ext5;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="ARCHI_SYS_INDEX_RELA$SEQ")
     @SequenceGenerator(name="ARCHI_SYS_INDEX_RELA$SEQ",sequenceName="ARCHI_SYS_INDEX_RELA$SEQ",allocationSize=1)    
    @Column(name="REAL_ID", unique=true, nullable=false, precision=14, scale=0)
    public long getRealId() {
        return this.realId;
    }
    
    public void setRealId(long realId) {
        this.realId = realId;
    }
    
    @Column(name="ONLYSYS_ID", precision=10, scale=0)
    public Long getOnlysysId() {
        return this.onlysysId;
    }
    
    public void setOnlysysId(Long onlysysId) {
        this.onlysysId = onlysysId;
    }
    
    @Column(name="INDEX_ID", precision=12, scale=0)
    public Long getIndexId() {
        return this.indexId;
    }
    
    public void setIndexId(Long indexId) {
        this.indexId = indexId;
    }
    
    @Column(name="INDEX_NAME", length=100)
    public String getIndexName() {
        return this.indexName;
    }
    
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }
    
    @Column(name="STATE", length=1)
    public Character getState() {
        return this.state;
    }
    
    public void setState(Character state) {
        this.state = state;
    }
    
    @Column(name="EXT_1")
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2")
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3")
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }
    
    @Column(name="EXT_4")
    public String getExt4() {
        return this.ext4;
    }
    
    public void setExt4(String ext4) {
        this.ext4 = ext4;
    }
    
    @Column(name="EXT_5")
    public String getExt5() {
        return this.ext5;
    }
    
    public void setExt5(String ext5) {
        this.ext5 = ext5;
    }




}


