package com.ai.aiga.domain;
// Generated 2018-3-19 15:02:07 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchSvnDbcp generated by hbm2java
 */
@Entity
@Table(name="ARCH_BUSI_ERRCODE_MAP")
public class ArchCsfErrcodeReport  implements java.io.Serializable {

	private Long id;
	private String monthDate;
    private String centerName;
    private Long errcodeCfgNum;
    private Long cfgCsfNum;
    private Long totlaCsfNum;
    private String errcodeCoverRate;
    private String errcodeSpecRate;
    private String collectionOrigin;
    private String pmOfChinamobile;
    private String pmOfAsiainfo;
    private Date insertDate;
    
    public ArchCsfErrcodeReport() {
    }

   public ArchCsfErrcodeReport(Long id, String monthDate, String centerName, Long errcodeCfgNum, Long cfgCsfNum, Long totlaCsfNum, String errcodeCoverRate, String errcodeSpecRate, String collectionOrigin, String pmOfChinamobile, String pmOfAsiainfo, Date insertDate) {
	  super();
	  this.id = id;
      this.monthDate = monthDate;
      this.centerName = centerName;
      this.errcodeCfgNum = errcodeCfgNum;
      this.cfgCsfNum = cfgCsfNum;
      this.totlaCsfNum = totlaCsfNum;
      this.errcodeCoverRate = errcodeCoverRate;
      this.errcodeSpecRate = errcodeSpecRate;
      this.collectionOrigin = collectionOrigin;
      this.pmOfChinamobile = pmOfChinamobile;
      this.pmOfAsiainfo = pmOfAsiainfo;
      this.insertDate = insertDate;
   }
   
	@Id 
    @Column(name="ID",nullable=false)
	public Long getId() {
		return id;
	}
	
	public void setId(Long id) {
		this.id = id;
	}
	@Column(name="MONTH_DATE", nullable=false, length=32)
	public String getMonthDate() {
		return monthDate;
	}
	
	public void setMonthDate(String monthDate) {
		this.monthDate = monthDate;
	}
	@Column(name="CENTER_NAME", nullable=false, length=256)
	public String getCenterName() {
		return centerName;
	}
	
	public void setCenterName(String centerName) {
		this.centerName = centerName;
	}
    @Column(name="ERRCODE_CFG_NUM")	
	public Long getErrcodeCfgNum() {
		return errcodeCfgNum;
	}
	
	public void setErrcodeCfgNum(Long errcodeCfgNum) {
		this.errcodeCfgNum = errcodeCfgNum;
	}
    @Column(name="CFG_CSF_NUM")	
	public Long getCfgCsfNum() {
		return cfgCsfNum;
	}
	
	public void setCfgCsfNum(Long cfgCsfNum) {
		this.cfgCsfNum = cfgCsfNum;
	}
    @Column(name="TOTLA_CSF_NUM")	
	public Long getTotlaCsfNum() {
		return totlaCsfNum;
	}
	
	public void setTotlaCsfNum(Long totlaCsfNum) {
		this.totlaCsfNum = totlaCsfNum;
	}
	@Column(name="ERRCODE_COVER_RATE", nullable=false, length=32)
	public String getErrcodeCoverRate() {
		return errcodeCoverRate;
	}
	public void setErrcodeCoverRate(String errcodeCoverRate) {
		this.errcodeCoverRate = errcodeCoverRate;
	}
	
	@Column(name="ERRCODE_SPEC_RATE", nullable=false, length=32)
	public String getErrcodeSpecRate() {
		return errcodeSpecRate;
	}
	
	public void setErrcodeSpecRate(String errcodeSpecRate) {
		this.errcodeSpecRate = errcodeSpecRate;
	}
	@Column(name="COLLECTION_ORIGIN", nullable=false, length=128)
	public String getCollectionOrigin() {
		return collectionOrigin;
	}
	
	public void setCollectionOrigin(String collectionOrigin) {
		this.collectionOrigin = collectionOrigin;
	}
	@Column(name="PM_OF_CHINAMOBILE", nullable=false, length=128)
	public String getPmOfChinamobile() {
		return pmOfChinamobile;
	}
	
	public void setPmOfChinamobile(String pmOfChinamobile) {
		this.pmOfChinamobile = pmOfChinamobile;
	}
	@Column(name="PM_OF_ASIAINFO", nullable=false, length=128)
	public String getPmOfAsiainfo() {
		return pmOfAsiainfo;
	}
	
	public void setPmOfAsiainfo(String pmOfAsiainfo) {
		this.pmOfAsiainfo = pmOfAsiainfo;
	}
	
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INSERT_TIME", nullable=false, length=7)
	public Date getInsertDate() {
		return insertDate;
	}
	
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}
   
}


