package com.ai.aiga.domain;
// Generated 2017-6-9 10:57:21 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchitectureFirst generated by hbm2java
 */
@Entity
@Table(name="ARCHITECTURE_FIRST"
    ,schema="AIGA"
)
public class ArchitectureFirst  implements java.io.Serializable {


     private long idFirst;
     private String name;
     private String shortName;
     private String description;
     private String code;
     private String belongLevel;
     private String state;
     private long applyId;
     private String applyUser;
     private Date createDate;
     private Date modifyDate;
     private String identifiedInfo;
     private String fileInfo;
     private String ext1;
     private String ext2;
     private String ext3;

    public ArchitectureFirst() {
    }

	
    public ArchitectureFirst(long idFirst, String name, String description, String code, String belongLevel, String state, long applyId, String applyUser, Date createDate, Date modifyDate, String identifiedInfo, String fileInfo) {
        this.idFirst = idFirst;
        this.name = name;
        this.description = description;
        this.code = code;
        this.belongLevel = belongLevel;
        this.state = state;
        this.applyId = applyId;
        this.applyUser = applyUser;
        this.createDate = createDate;
        this.modifyDate = modifyDate;
        this.identifiedInfo = identifiedInfo;
        this.fileInfo = fileInfo;
    }
    public ArchitectureFirst(long idFirst, String name, String shortName, String description, String code, String belongLevel, String state, long applyId, String applyUser, Date createDate, Date modifyDate, String identifiedInfo, String fileInfo, String ext1, String ext2, String ext3 ) {
       this.idFirst = idFirst;
       this.name = name;
       this.shortName = shortName;
       this.description = description;
       this.code = code;
       this.belongLevel = belongLevel;
       this.state = state;
       this.applyId = applyId;
       this.applyUser = applyUser;
       this.createDate = createDate;
       this.modifyDate = modifyDate;
       this.identifiedInfo = identifiedInfo;
       this.fileInfo = fileInfo;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
    
    @Column(name="ID_FIRST", unique=true, nullable=false, precision=10, scale=0)
    public long getIdFirst() {
        return this.idFirst;
    }
    
    public void setIdFirst(long idFirst) {
        this.idFirst = idFirst;
    }
    
    @Column(name="NAME", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="SHORT_NAME")
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    
    @Column(name="DESCRIPTION", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="CODE", nullable=false, length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="BELONG_LEVEL", nullable=false, length=20)
    public String getBelongLevel() {
        return this.belongLevel;
    }
    
    public void setBelongLevel(String belongLevel) {
        this.belongLevel = belongLevel;
    }
    
    @Column(name="STATE", nullable=false, length=20)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="APPLY_ID", nullable=false, precision=10, scale=0)
    public long getApplyId() {
        return this.applyId;
    }
    
    public void setApplyId(long applyId) {
        this.applyId = applyId;
    }
    
    @Column(name="APPLY_USER", nullable=false, length=10)
    public String getApplyUser() {
        return this.applyUser;
    }
    
    public void setApplyUser(String applyUser) {
        this.applyUser = applyUser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", nullable=false, length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFY_DATE", nullable=false, length=7)
    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
    
    @Column(name="IDENTIFIED_INFO", nullable=false)
    public String getIdentifiedInfo() {
        return this.identifiedInfo;
    }
    
    public void setIdentifiedInfo(String identifiedInfo) {
        this.identifiedInfo = identifiedInfo;
    }
    
    @Column(name="FILE_INFO", nullable=false, length=500)
    public String getFileInfo() {
        return this.fileInfo;
    }
    
    public void setFileInfo(String fileInfo) {
        this.fileInfo = fileInfo;
    }
    
    @Column(name="EXT_1")
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2")
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3")
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }

}


