package com.ai.aiga.domain;
// Generated 2017-6-23 16:48:01 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArchitectureStaticData generated by hbm2java
 */
@Entity
@Table(name="ARCHITECTURE_STATIC_DATA")
public class ArchitectureStaticData  implements java.io.Serializable {


     private ArchitectureStaticDataId id;

    public ArchitectureStaticData() {
    }

    public ArchitectureStaticData(ArchitectureStaticDataId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="codeType", column=@Column(name="CODE_TYPE") ), 
        @AttributeOverride(name="codeValue", column=@Column(name="CODE_VALUE") ), 
        @AttributeOverride(name="codeName", column=@Column(name="CODE_NAME") ), 
        @AttributeOverride(name="codeDesc", column=@Column(name="CODE_DESC") ), 
        @AttributeOverride(name="ext1", column=@Column(name="EXT1") ), 
        @AttributeOverride(name="ext2", column=@Column(name="EXT2") ), 
        @AttributeOverride(name="ext3", column=@Column(name="EXT3") ) } )
    public ArchitectureStaticDataId getId() {
        return this.id;
    }
    
    public void setId(ArchitectureStaticDataId id) {
        this.id = id;
    }




}


