package com.ai.aiga.domain;
// Generated 2017-6-14 15:31:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FirstCategory generated by hbm2java
 */
@Entity
@Table(name="FIRST_CATEGORY",schema="AIGA")
public class FirstCategory  implements java.io.Serializable {


     private long firstId;
     private String name;
     private long rootId;

    public FirstCategory() {
    }

    public FirstCategory(long firstId, String name, long rootId) {
       this.firstId = firstId;
       this.name = name;
       this.rootId = rootId;
    }
   
     @Id 
    
    @Column(name="FIRST_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getFirstId() {
        return this.firstId;
    }
    
    public void setFirstId(long firstId) {
        this.firstId = firstId;
    }
    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="ROOT_ID", nullable=false, precision=10, scale=0)
    public long getRootId() {
        return this.rootId;
    }
    
    public void setRootId(long rootId) {
        this.rootId = rootId;
    }




}


