package com.ai.aiga.domain;
// Generated 2017-3-15 14:42:25 by Hibernate Tools 3.2.2.GA



import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * NaAutoEnvironment generated by hbm2java
 */
@Entity
@Table(name="NA_AUTO_ENVIRONMENT"
    ,schema="AIGA"
)
public class NaAutoEnvironment  implements java.io.Serializable {


     private BigDecimal envId;
     private BigDecimal sysId;
     private String envName;
     private String envUrl;
     private String sysAccount;
     private String sysPassword;
     private String database;
     private String dbAccount;
     private String dbPassword;
     private BigDecimal regionId;
     private String soId;
     private String svnUrl;
     private String svnAccount;
     private String svnPassword;
     private BigDecimal envType;
     private BigDecimal runEnv;
     private BigDecimal creatorId;
     private String envCode;

     @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
     private Date updateTime;

    public NaAutoEnvironment() {
    }

	
    public NaAutoEnvironment(BigDecimal envId) {
        this.envId = envId;
    }
    public NaAutoEnvironment(BigDecimal envId, BigDecimal sysId, String envName, String envUrl, String sysAccount, String sysPassword, String database, String dbAccount, String dbPassword, BigDecimal regionId, String soId, String svnUrl, String svnAccount, String svnPassword, BigDecimal envType, BigDecimal runEnv, BigDecimal creatorId, Date updateTime,String envCode) {
       this.envId = envId;
       this.sysId = sysId;
       this.envName = envName;
       this.envUrl = envUrl;
       this.sysAccount = sysAccount;
       this.sysPassword = sysPassword;
       this.database = database;
       this.dbAccount = dbAccount;
       this.dbPassword = dbPassword;
       this.regionId = regionId;
       this.soId = soId;
       this.svnUrl = svnUrl;
       this.svnAccount = svnAccount;
       this.svnPassword = svnPassword;
       this.envType = envType;
       this.runEnv = runEnv;
       this.creatorId = creatorId;
       this.updateTime = updateTime;
       this.envCode=envCode;
    }


     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_AUTO_ENVIRONMENT$SEQ")
     @SequenceGenerator(name="NA_AUTO_ENVIRONMENT$SEQ",sequenceName="NA_AUTO_ENVIRONMENT$SEQ",allocationSize=1)
    @Column(name="ENV_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getEnvId() {
        return this.envId;
    }
    
    public void setEnvId(BigDecimal envId) {
        this.envId = envId;
    }
    
    @Column(name="SYS_ID", precision=22, scale=0)
    public BigDecimal getSysId() {
        return this.sysId;
    }
    
    public void setSysId(BigDecimal sysId) {
        this.sysId = sysId;
    }
    
    @Column(name="ENV_NAME", length=100)
    public String getEnvName() {
        return this.envName;
    }
    
    public void setEnvName(String envName) {
        this.envName = envName;
    }
    
    @Column(name="ENV_URL", length=200)
    public String getEnvUrl() {
        return this.envUrl;
    }
    
    public void setEnvUrl(String envUrl) {
        this.envUrl = envUrl;
    }
    
    @Column(name="SYS_ACCOUNT", length=40)
    public String getSysAccount() {
        return this.sysAccount;
    }
    
    public void setSysAccount(String sysAccount) {
        this.sysAccount = sysAccount;
    }
    
    @Column(name="SYS_PASSWORD", length=40)
    public String getSysPassword() {
        return this.sysPassword;
    }
    
    public void setSysPassword(String sysPassword) {
        this.sysPassword = sysPassword;
    }
    
    @Column(name="DATABASE", length=40)
    public String getDatabase() {
        return this.database;
    }
    
    public void setDatabase(String database) {
        this.database = database;
    }
    
    @Column(name="DB_ACCOUNT", length=40)
    public String getDbAccount() {
        return this.dbAccount;
    }
    
    public void setDbAccount(String dbAccount) {
        this.dbAccount = dbAccount;
    }
    
    @Column(name="DB_PASSWORD", length=40)
    public String getDbPassword() {
        return this.dbPassword;
    }
    
    public void setDbPassword(String dbPassword) {
        this.dbPassword = dbPassword;
    }
    
    @Column(name="REGION_ID", precision=22, scale=0)
    public BigDecimal getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(BigDecimal regionId) {
        this.regionId = regionId;
    }
    
    @Column(name="SO_ID", length=10)
    public String getSoId() {
        return this.soId;
    }
    
    public void setSoId(String soId) {
        this.soId = soId;
    }
    
    @Column(name="SVN_URL", length=400)
    public String getSvnUrl() {
        return this.svnUrl;
    }
    
    public void setSvnUrl(String svnUrl) {
        this.svnUrl = svnUrl;
    }
    
    @Column(name="SVN_ACCOUNT", length=40)
    public String getSvnAccount() {
        return this.svnAccount;
    }
    
    public void setSvnAccount(String svnAccount) {
        this.svnAccount = svnAccount;
    }
    
    @Column(name="SVN_PASSWORD", length=40)
    public String getSvnPassword() {
        return this.svnPassword;
    }
    
    public void setSvnPassword(String svnPassword) {
        this.svnPassword = svnPassword;
    }
    
    @Column(name="ENV_TYPE", precision=22, scale=0)
    public BigDecimal getEnvType() {
        return this.envType;
    }
    
    public void setEnvType(BigDecimal envType) {
        this.envType = envType;
    }
    
    @Column(name="RUN_ENV", precision=22, scale=0)
    public BigDecimal getRunEnv() {
        return this.runEnv;
    }
    
    public void setRunEnv(BigDecimal runEnv) {
        this.runEnv = runEnv;
    }
    
    @Column(name="CREATOR_ID", precision=22, scale=0)
    public BigDecimal getCreatorId() {
        return this.creatorId;
    }
    
    public void setCreatorId(BigDecimal creatorId) {
        this.creatorId = creatorId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_TIME", length=7)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    @Basic
    @Column(name="ENV_CODE")
    public String getEnvCode() {
        return this.envCode;
    }

    public void setEnvCode(String envCode) {
        this.envCode = envCode;
    }



}


