package com.ai.aiga.domain;
// Generated 2017-3-17 15:38:13 by Hibernate Tools 3.2.2.GA


import java.sql.Clob;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaAutoRunResult generated by hbm2java
 */
@Entity
@Table(name="NA_AUTO_RUN_RESULT"
    ,schema="AIGA"
)
public class NaAutoRunResult  implements java.io.Serializable {


     private Long resultId;
     private Long taskId;
     private Long autoId;
     private Long groupId;
     private Long collectId;
     private Byte resultType;
     private Byte runType;
     private Long sortNumber;
     private Long sortGroup;
     private Byte environmentType;
     private Date beginTime;
     private Date endTime;
     private String runInfo;
     private String runLog;
     private String failReason;

    public NaAutoRunResult() {
    }

	
    public NaAutoRunResult(long resultId) {
        this.resultId = resultId;
    }
    public NaAutoRunResult(Long resultId, Long taskId, Long autoId, Long groupId, Long collectId, Byte resultType, Byte runType, Long sortNumber, Long sortGroup, Byte environmentType, Date beginTime, Date endTime, String runInfo, String runLog, String failReason) {
       this.resultId = resultId;
       this.taskId = taskId;
       this.autoId = autoId;
       this.groupId = groupId;
       this.collectId = collectId;
       this.resultType = resultType;
       this.runType = runType;
       this.sortNumber = sortNumber;
       this.sortGroup = sortGroup;
       this.environmentType = environmentType;
       this.beginTime = beginTime;
       this.endTime = endTime;
       this.runInfo = runInfo;
       this.runLog = runLog;
       this.failReason = failReason;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_AUTO_RUN_RESULT$SEQ")
    @SequenceGenerator(name="NA_AUTO_RUN_RESULT$SEQ",sequenceName="NA_AUTO_RUN_RESULT$SEQ",allocationSize=1)
    @Column(name="RESULT_ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getResultId() {
        return this.resultId;
    }
    
    public void setResultId(Long resultId) {
        this.resultId = resultId;
    }
    
    @Column(name="TASK_ID", precision=14, scale=0)
    public Long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }
    
    @Column(name="AUTO_ID", precision=14, scale=0)
    public Long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(Long autoId) {
        this.autoId = autoId;
    }
    
    @Column(name="GROUP_ID", precision=14, scale=0)
    public Long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }
    
    @Column(name="COLLECT_ID", precision=14, scale=0)
    public Long getCollectId() {
        return this.collectId;
    }
    
    public void setCollectId(Long collectId) {
        this.collectId = collectId;
    }
    
    @Column(name="RESULT_TYPE", precision=2, scale=0)
    public Byte getResultType() {
        return this.resultType;
    }
    
    public void setResultType(Byte resultType) {
        this.resultType = resultType;
    }
    
    @Column(name="RUN_TYPE", precision=2, scale=0)
    public Byte getRunType() {
        return this.runType;
    }
    
    public void setRunType(Byte runType) {
        this.runType = runType;
    }
    
    @Column(name="SORT_NUMBER", precision=14, scale=0)
    public Long getSortNumber() {
        return this.sortNumber;
    }
    
    public void setSortNumber(Long sortNumber) {
        this.sortNumber = sortNumber;
    }
    
    @Column(name="SORT_GROUP", precision=14, scale=0)
    public Long getSortGroup() {
        return this.sortGroup;
    }
    
    public void setSortGroup(Long sortGroup) {
        this.sortGroup = sortGroup;
    }
    
    @Column(name="ENVIRONMENT_TYPE", precision=2, scale=0)
    public Byte getEnvironmentType() {
        return this.environmentType;
    }
    
    public void setEnvironmentType(Byte environmentType) {
        this.environmentType = environmentType;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BEGIN_TIME", length=7)
    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_TIME", length=7)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    
    @Lob
  	@Basic(fetch = FetchType.LAZY)
    @Column(name="RUN_INFO", columnDefinition = "CLOB")
    public String getRunInfo() {
        return this.runInfo;
    }
    
    public void setRunInfo(String runInfo) {
        this.runInfo = runInfo;
    }
    
    @Lob
  	@Basic(fetch = FetchType.LAZY)
    @Column(name="RUN_LOG", columnDefinition = "CLOB")
    public String getRunLog() {
        return this.runLog;
    }
    
    public void setRunLog(String runLog) {
        this.runLog = runLog;
    }
    
    @Column(name="FAIL_REASON", length=4000)
    public String getFailReason() {
        return this.failReason;
    }
    
    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }




}


