package com.ai.aiga.domain;
// Generated 2017-3-17 18:53:45 by Hibernate Tools 3.2.2.GA




import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaAutoRunPlan generated by hbm2java
 */
@Entity
@Table(name="NA_AUTO_RUN_PLAN"
)
public class NaAutoRunPlan  implements java.io.Serializable {

@OrderBy("createTime desc")
     private Long planId;
     private String planTag;
     private String planName;
     private Long creatorId;
     private Date createTime;
     private Date updateTime;
     private Long cycleType;
     private String machineIp;
     private Long runType;

    public NaAutoRunPlan() {
    }

	
    public NaAutoRunPlan(Long planId, String planTag, String planName) {
        this.planId = planId;
        this.planTag = planTag;
        this.planName = planName;
    }
    public NaAutoRunPlan(Long planId, String planTag, String planName, Long creatorId, Date createTime, Date updateTime, Long cycleType, String machineIp, Long runType) {
       this.planId = planId;
       this.planTag = planTag;
       this.planName = planName;
       this.creatorId = creatorId;
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.cycleType = cycleType;
       this.machineIp = machineIp;
       this.runType = runType;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_AUTO_CASE$SEQ")
     @SequenceGenerator(name="NA_AUTO_CASE$SEQ",sequenceName="NA_AUTO_CASE$SEQ",allocationSize=1)
    @Column(name="PLAN_ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="PLAN_TAG", nullable=false, length=40)
    public String getPlanTag() {
        return this.planTag;
    }
    
    public void setPlanTag(String planTag) {
        this.planTag = planTag;
    }				
    
    @Column(name="PLAN_NAME", nullable=false, length=100)
    public String getPlanName() {
        return this.planName;
    }
    
    public void setPlanName(String planName) {
        this.planName = planName;
    }
    
    @Column(name="CREATOR_ID", precision=22, scale=0)
    public Long getCreatorId() {
        return this.creatorId;
    }
    
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    @Column(name="CREATE_TIME", length=7)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Column(name="UPDATE_TIME", length=7)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    @Column(name="CYCLE_TYPE", precision=22, scale=0)
    public Long getCycleType() {
        return this.cycleType;
    }
    
    public void setCycleType(Long cycleType) {
        this.cycleType = cycleType;
    }
    
    @Column(name="MACHINE_IP", length=20)
    public String getMachineIp() {
        return this.machineIp;
    }
    
    public void setMachineIp(String machineIp) {
        this.machineIp = machineIp;
    }
    
    @Column(name="RUN_TYPE", precision=22, scale=0)
    public Long getRunType() {
        return this.runType;
    }
    
    public void setRunType(Long runType) {
        this.runType = runType;
    }




}


