package com.ai.aiga.domain;
// Generated 2017-3-17 15:35:33 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * NaAutoRunTaskReport generated by hbm2java
 */
@Entity
@Table(name="NA_AUTO_RUN_TASK_REPORT"
    ,schema="AIGA"
)
public class NaAutoRunTaskReport  implements java.io.Serializable {


     private Long reportId;
     private Long taskId;
     private String reportName;
     private Long totalCase;
     private Long hasRunCase;
     private Long noneRunCase;
     private Long successCase;
     private Long failCase;
     private String  successRate;
     @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
     private Date beginTime;
     @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
     private Date endTime;
     @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
     private Date spendTime;
     private Long creatorId;
     private Date updateTime;

    public NaAutoRunTaskReport() {
    }

	
    public NaAutoRunTaskReport(long reportId) {
        this.reportId = reportId;
    }
    public NaAutoRunTaskReport(Long reportId, Long taskId, String reportName, Long totalCase, Long hasRunCase, Long noneRunCase, Long successCase, Long failCase, String successRate, Date beginTime, Date endTime, Date spendTime, Long creatorId, Date updateTime) {
       this.reportId = reportId;
       this.taskId = taskId;
       this.reportName = reportName;
       this.totalCase = totalCase;
       this.hasRunCase = hasRunCase;
       this.noneRunCase = noneRunCase;
       this.successCase = successCase;
       this.failCase = failCase;
       this.successRate = successRate;
       this.beginTime = beginTime;
       this.endTime = endTime;
       this.spendTime = spendTime;
       this.creatorId = creatorId;
       this.updateTime = updateTime;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_AUTO_RUN_TASK_REPORT$SEQ")
    @SequenceGenerator(name="NA_AUTO_RUN_TASK_REPORT$SEQ",sequenceName="NA_AUTO_RUN_TASK_REPORT$SEQ",allocationSize=1)
    @Column(name="REPORT_ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getReportId() {
        return this.reportId;
    }
    
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }
    
    @Column(name="TASK_ID", precision=14, scale=0)
    public Long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }
    
    @Column(name="REPORT_NAME", length=200)
    public String getReportName() {
        return this.reportName;
    }
    
    public void setReportName(String reportName) {
        this.reportName = reportName;
    }
    
    @Column(name="TOTAL_CASE", precision=14, scale=0)
    public Long getTotalCase() {
        return this.totalCase;
    }
    
    public void setTotalCase(Long totalCase) {
        this.totalCase = totalCase;
    }
    
    @Column(name="HAS_RUN_CASE", precision=14, scale=0)
    public Long getHasRunCase() {
        return this.hasRunCase;
    }
    
    public void setHasRunCase(Long hasRunCase) {
        this.hasRunCase = hasRunCase;
    }
    
    @Column(name="NONE_RUN_CASE", precision=14, scale=0)
    public Long getNoneRunCase() {
        return this.noneRunCase;
    }
    
    public void setNoneRunCase(Long noneRunCase) {
        this.noneRunCase = noneRunCase;
    }
    
    @Column(name="SUCCESS_CASE", precision=14, scale=0)
    public Long getSuccessCase() {
        return this.successCase;
    }
    
    public void setSuccessCase(Long successCase) {
        this.successCase = successCase;
    }
    
    @Column(name="FAIL_CASE", precision=14, scale=0)
    public Long getFailCase() {
        return this.failCase;
    }
    
    public void setFailCase(Long failCase) {
        this.failCase = failCase;
    }
    
    @Column(name="SUCCESS_RATE", length=10)
    public String getSuccessRate() {
        return this.successRate;
    }
    
    public void setSuccessRate(String successRate) {
        this.successRate = successRate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BEGIN_TIME", length=7)
    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_TIME", length=7)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SPEND_TIME", length=7)
    public Date getSpendTime() {
        return this.spendTime;
    }
    
    public void setSpendTime(Date spendTime) {
        this.spendTime = spendTime;
    }
    
    @Column(name="CREATOR_ID", precision=14, scale=0)
    public Long getCreatorId() {
        return this.creatorId;
    }
    
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_TIME", length=7)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }




}


