package com.ai.aiga.domain;
// Generated 2017-3-17 9:34:34 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaBusiness generated by hbm2java
 */
@Entity
@Table(name="NA_BUSINESS")
public class NaBusiness  implements java.io.Serializable {


     private long busiId;
     private String busiName;
     private Long busiType;
     private String busiDesc;
     private Short important;
     private Short invalid;
     private Long creatorId;
     private Date createTime;

    public NaBusiness() {
    }

	
    public NaBusiness(long busiId) {
        this.busiId = busiId;
    }
    public NaBusiness(long busiId, String busiName, Long busiType, String busiDesc, Short important, Short invalid, Long creatorId, Date createTime) {
       this.busiId = busiId;
       this.busiName = busiName;
       this.busiType = busiType;
       this.busiDesc = busiDesc;
       this.important = important;
       this.invalid = invalid;
       this.creatorId = creatorId;
       this.createTime = createTime;
    }
   
     @Id 
    
    @Column(name="BUSI_ID", unique=true, nullable=false, precision=14, scale=0)
    public long getBusiId() {
        return this.busiId;
    }
    
    public void setBusiId(long busiId) {
        this.busiId = busiId;
    }
    
    @Column(name="BUSI_NAME", length=40)
    public String getBusiName() {
        return this.busiName;
    }
    
    public void setBusiName(String busiName) {
        this.busiName = busiName;
    }
    
    @Column(name="BUSI_TYPE", precision=14, scale=0)
    public Long getBusiType() {
        return this.busiType;
    }
    
    public void setBusiType(Long busiType) {
        this.busiType = busiType;
    }
    
    @Column(name="BUSI_DESC", length=1000)
    public String getBusiDesc() {
        return this.busiDesc;
    }
    
    public void setBusiDesc(String busiDesc) {
        this.busiDesc = busiDesc;
    }
    
    @Column(name="IMPORTANT", precision=3, scale=0)
    public Short getImportant() {
        return this.important;
    }
    
    public void setImportant(Short important) {
        this.important = important;
    }
    
    @Column(name="INVALID", precision=3, scale=0)
    public Short getInvalid() {
        return this.invalid;
    }
    
    public void setInvalid(Short invalid) {
        this.invalid = invalid;
    }
    
    @Column(name="CREATOR_ID", precision=14, scale=0)
    public Long getCreatorId() {
        return this.creatorId;
    }
    
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", length=7)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


