package com.ai.aiga.domain;
// Generated 2017-3-1 11:33:01 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaCaseTemplate generated by hbm2java
 */
@Entity
@Table(name = "NA_CASE_TEMPLATE")
public class NaCaseTemplate implements java.io.Serializable {

	private long caseId;
	private String caseName;
	private Byte caseType;
	private String testType;
	private String preCond;
	private String operateDesc;
	private Short important;
	private Long sysId;
	private Long sysSubId;
	private Long funId;
	private Long scId;
	private Long busiId;
	private Long creatorId;
	private Date createTime;
	private Long updateId;
	private Date updateTime;
	private Byte states;

	public NaCaseTemplate() {
	}

	public NaCaseTemplate(long caseId, String caseName, byte caseType) {
		this.caseId = caseId;
		this.caseName = caseName;
		this.caseType = caseType;
	}

	public NaCaseTemplate(long caseId, String caseName, Byte caseType, String testType, String preCond,
			String operateDesc, Short important, Long sysId, Long sysSubId, Long funId, Long scId, Long busiId,
			Long creatorId, Date createTime, Long updateId, Date updateTime, Byte states) {
		this.caseId = caseId;
		this.caseName = caseName;
		this.caseType = caseType;
		this.testType = testType;
		this.preCond = preCond;
		this.operateDesc = operateDesc;
		this.important = important;
		this.sysId = sysId;
		this.sysSubId = sysSubId;
		this.funId = funId;
		this.scId = scId;
		this.busiId = busiId;
		this.creatorId = creatorId;
		this.createTime = createTime;
		this.updateId = updateId;
		this.updateTime = updateTime;
		this.states = states;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NA_CASE_TEMPLATE$SEQ")
	@SequenceGenerator(name = "NA_CASE_TEMPLATE$SEQ", sequenceName = "NA_CASE_TEMPLATE$SEQ", allocationSize = 1)
	@Column(name = "CASE_ID", unique = true, nullable = false, precision = 14, scale = 0)
	public long getCaseId() {
		return this.caseId;
	}

	public void setCaseId(long caseId) {
		this.caseId = caseId;
	}

	@Column(name = "CASE_NAME", nullable = false, length = 400)
	public String getCaseName() {
		return this.caseName;
	}

	public void setCaseName(String caseName) {
		this.caseName = caseName;
	}

	@Column(name = "CASE_TYPE", nullable = false, precision = 2, scale = 0)
	public Byte getCaseType() {
		return this.caseType;
	}

	public void setCaseType(Byte caseType) {
		this.caseType = caseType;
	}

	@Column(name = "TEST_TYPE", length = 40)
	public String getTestType() {
		return this.testType;
	}

	public void setTestType(String testType) {
		this.testType = testType;
	}

	@Lob
	@Basic(fetch = FetchType.LAZY)
	@Column(name = "PRE_COND", columnDefinition = "CLOB")
	public String getPreCond() {
		return this.preCond;
	}

	public void setPreCond(String preCond) {
		this.preCond = preCond;
	}

	@Lob
	@Basic(fetch = FetchType.LAZY)
	@Column(name = "OPERATE_DESC", columnDefinition = "CLOB")
	public String getOperateDesc() {
		return this.operateDesc;
	}

	public void setOperateDesc(String operateDesc) {
		this.operateDesc = operateDesc;
	}

	@Column(name = "IMPORTANT", precision = 3, scale = 0)
	public Short getImportant() {
		return this.important;
	}

	public void setImportant(Short important) {
		this.important = important;
	}

	@Column(name = "SYS_ID", precision = 14, scale = 0)
	public Long getSysId() {
		return this.sysId;
	}

	public void setSysId(Long sysId) {
		this.sysId = sysId;
	}

	@Column(name = "SYS_SUB_ID", precision = 14, scale = 0)
	public Long getSysSubId() {
		return this.sysSubId;
	}

	public void setSysSubId(Long sysSubId) {
		this.sysSubId = sysSubId;
	}

	@Column(name = "FUN_ID", precision = 14, scale = 0)
	public Long getFunId() {
		return this.funId;
	}

	public void setFunId(Long funId) {
		this.funId = funId;
	}

	@Column(name = "SC_ID", precision = 14, scale = 0)
	public Long getScId() {
		return this.scId;
	}

	public void setScId(Long scId) {
		this.scId = scId;
	}

	@Column(name = "BUSI_ID", precision = 14, scale = 0)
	public Long getBusiId() {
		return this.busiId;
	}

	public void setBusiId(Long busiId) {
		this.busiId = busiId;
	}

	@Column(name = "CREATOR_ID", precision = 14, scale = 0)
	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 11)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "UPDATE_ID", precision = 14, scale = 0)
	public Long getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(Long updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 11)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "STATES", precision = 2, scale = 0)
	public Byte getStates() {
		return this.states;
	}

	public void setStates(Byte states) {
		this.states = states;
	}

	@Override
	public String toString() {
		return "NaCaseTemplate [caseId=" + caseId + ", caseName=" + caseName + ", caseType=" + caseType + ", testType="
				+ testType + ", preCond=" + preCond + ", operateDesc=" + operateDesc + ", important=" + important
				+ ", sysId=" + sysId + ", sysSubId=" + sysSubId + ", funId=" + funId + ", scId=" + scId + ", busiId="
				+ busiId + ", creatorId=" + creatorId + ", createTime=" + createTime + ", updateId=" + updateId
				+ ", updateTime=" + updateTime + ", states=" + states + "]";
	}

}
