package com.ai.aiga.domain;
// Generated 2017-4-24 15:00:18 by Hibernate Tools 3.2.2.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaChangeUpdate generated by hbm2java
 */
@Entity
@Table(name="NA_CHANGE_UPDATE"
)
public class NaChangeUpdate  implements java.io.Serializable {


     private Long id;
     private String configIsUpdate;
     private String resourceType;
     private String name;
     private String configUpdateBefore;
     private String configUpdateAfter;
     private Long planId;
     private String fileName;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaChangeUpdate() {
    }

	
    public NaChangeUpdate(Long id) {
        this.id = id;
    }
    public NaChangeUpdate(Long id, String configIsUpdate, String resourceType, String name, String configUpdateBefore, String configUpdateAfter, Long planId, String fileName, String ext1, String ext2, String ext3) {
       this.id = id;
       this.configIsUpdate = configIsUpdate;
       this.resourceType = resourceType;
       this.name = name;
       this.configUpdateBefore = configUpdateBefore;
       this.configUpdateAfter = configUpdateAfter;
       this.planId = planId;
       this.fileName = fileName;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_CHANGE_UPDATE$SEQ")
     @SequenceGenerator(name="NA_CHANGE_UPDATE$SEQ",sequenceName="NA_CHANGE_UPDATE$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="CONFIG_IS_UPDATE", length=100)
    public String getConfigIsUpdate() {
        return this.configIsUpdate;
    }
    
    public void setConfigIsUpdate(String configIsUpdate) {
        this.configIsUpdate = configIsUpdate;
    }
    
    @Column(name="RESOURCE_TYPE", length=100)
    public String getResourceType() {
        return this.resourceType;
    }
    
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }
    
    @Column(name="NAME", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="CONFIG_UPDATE_BEFORE", length=100)
    public String getConfigUpdateBefore() {
        return this.configUpdateBefore;
    }
    
    public void setConfigUpdateBefore(String configUpdateBefore) {
        this.configUpdateBefore = configUpdateBefore;
    }
    
    @Column(name="CONFIG_UPDATE_AFTER", length=100)
    public String getConfigUpdateAfter() {
        return this.configUpdateAfter;
    }
    
    public void setConfigUpdateAfter(String configUpdateAfter) {
        this.configUpdateAfter = configUpdateAfter;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="FILE_NAME", length=100)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="EXT_1", length=100)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=100)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=100)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


