package com.ai.aiga.domain;
// Generated 2017-4-24 15:00:18 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaChangeDangurousEstimate generated by hbm2java
 */
@Entity
@Table(name="NA_CHANGE_DANGUROUS_ESTIMATE"
)
public class NaChangeDangurousEstimate  implements java.io.Serializable {


     private Long id;
     private String types;
     private String contents;
     private Long planId;
     private String fileName;
     private String ext1;
     private String ext2;

    public NaChangeDangurousEstimate() {
    }

	
    public NaChangeDangurousEstimate(Long id) {
        this.id = id;
    }
    public NaChangeDangurousEstimate(Long id, String types, String contents, Long planId, String fileName, String ext1, String ext2) {
       this.id = id;
       this.types = types;
       this.contents = contents;
       this.planId = planId;
       this.fileName = fileName;
       this.ext1 = ext1;
       this.ext2 = ext2;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NA_CHANGE_DANGUROUS_E$SEQ")
   	@SequenceGenerator(name = "NA_CHANGE_DANGUROUS_E$SEQ", sequenceName = "NA_CHANGE_DANGUROUS_E$SEQ", allocationSize = 1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="TYPES", length=200)
    public String getTypes() {
        return this.types;
    }
    
    public void setTypes(String types) {
        this.types = types;
    }
    
    @Column(name="CONTENTS", length=200)
    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="FILE_NAME", length=200)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="EXT_1", length=200)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=200)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }




}


