package com.ai.aiga.domain;
// Generated 2017-3-28 14:38:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaChangePlanOnile generated by hbm2java
 */
@Entity
@Table(name="NA_CHANGE_PLAN_ONILE"
    ,schema="AIGA"
)
public class NaChangePlanOnile  implements java.io.Serializable {


     private Long onlinePlan;
     private String onlinePlanName;
     private Long planState;
     private String createOpId;
     private Date createDate;
     private Date doneDate;
     private Date planDate;
     private Byte result;
     private String remark;
     private String ext1;
     private String ext2;
     private String ext3;
     private Byte sign;
     private Byte types;
     private Byte timely;
     private Byte isFinished;
     private Byte autoRunResult;

    public NaChangePlanOnile() {
    }

	
    public NaChangePlanOnile(Long onlinePlan, String onlinePlanName, Long planState) {
        this.onlinePlan = onlinePlan;
        this.onlinePlanName = onlinePlanName;
        this.planState = planState;
    }
    public NaChangePlanOnile(Long onlinePlan, String onlinePlanName, Long planState, String createOpId, Date createDate, Date doneDate, Date planDate, Byte result, String remark, String ext1, String ext2, String ext3, Byte sign, Byte types, Byte timely, Byte isFinished, Byte autoRunResult) {
       this.onlinePlan = onlinePlan;
       this.onlinePlanName = onlinePlanName;
       this.planState = planState;
       this.createOpId = createOpId;
       this.createDate = createDate;
       this.doneDate = doneDate;
       this.planDate = planDate;
       this.result = result;
       this.remark = remark;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
       this.sign = sign;
       this.types = types;
       this.timely = timely;
       this.isFinished = isFinished;
       this.autoRunResult = autoRunResult;
    }
   
     @Id 
    
    @Column(name="ONLINE_PLAN", nullable=false, precision=12, scale=0)
    public Long getOnlinePlan() {
        return this.onlinePlan;
    }
    
    public void setOnlinePlan(Long onlinePlan) {
        this.onlinePlan = onlinePlan;
    }
    
    @Column(name="ONLINE_PLAN_NAME", nullable=false, length=200)
    public String getOnlinePlanName() {
        return this.onlinePlanName;
    }
    
    public void setOnlinePlanName(String onlinePlanName) {
        this.onlinePlanName = onlinePlanName;
    }
    
    @Column(name="PLAN_STATE", nullable=false, precision=2, scale=0)
    public Long getPlanState() {
        return this.planState;
    }
    
    public void setPlanState(Long planState) {
        this.planState = planState;
    }
    
    @Column(name="CREATE_OP_ID", length=200)
    public String getCreateOpId() {
        return this.createOpId;
    }
    
    public void setCreateOpId(String createOpId) {
        this.createOpId = createOpId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DONE_DATE", length=7)
    public Date getDoneDate() {
        return this.doneDate;
    }
    
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLAN_DATE", length=7)
    public Date getPlanDate() {
        return this.planDate;
    }
    
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }
    
    @Column(name="RESULT", precision=2, scale=0)
    public Byte getResult() {
        return this.result;
    }
    
    public void setResult(Byte result) {
        this.result = result;
    }
    
    @Column(name="REMARK", length=2000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="EXT_1", length=20)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=20)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=20)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }
    
    @Column(name="SIGN", precision=2, scale=0)
    public Byte getSign() {
        return this.sign;
    }
    
    public void setSign(Byte sign) {
        this.sign = sign;
    }
    
    @Column(name="TYPES", precision=2, scale=0)
    public Byte getTypes() {
        return this.types;
    }
    
    public void setTypes(Byte types) {
        this.types = types;
    }
    
    @Column(name="TIMELY", precision=2, scale=0)
    public Byte getTimely() {
        return this.timely;
    }
    
    public void setTimely(Byte timely) {
        this.timely = timely;
    }
    
    @Column(name="IS_FINISHED", precision=2, scale=0)
    public Byte getIsFinished() {
        return this.isFinished;
    }
    
    public void setIsFinished(Byte isFinished) {
        this.isFinished = isFinished;
    }
    
    @Column(name="AUTO_RUN_RESULT", precision=2, scale=0)
    public Byte getAutoRunResult() {
        return this.autoRunResult;
    }
    
    public void setAutoRunResult(Byte autoRunResult) {
        this.autoRunResult = autoRunResult;
    }




}


