package com.ai.aiga.domain;
// Generated 2017-3-29 18:10:15 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaCodePath generated by hbm2java
 */
@Entity
@Table(name="NA_CODE_PATH"
)
public class NaCodePath  implements java.io.Serializable {


     private Long ids;
     private String sysName;
     private String modelName;
     private String packageName;
     private Long state;
     private String remark;
     private Date planDate;
     private String isFinished;
     private Long updateCount;

    public NaCodePath() {
    }

	
    public NaCodePath(Long ids) {
        this.ids = ids;
    }
    public NaCodePath(Long ids, String sysName, String modelName, String packageName, Long state, String remark, Date planDate, String isFinished, Long updateCount) {
       this.ids = ids;
       this.sysName = sysName;
       this.modelName = modelName;
       this.packageName = packageName;
       this.state = state;
       this.remark = remark;
       this.planDate = planDate;
       this.isFinished = isFinished;
       this.updateCount = updateCount;
    }
   
     @Id 
    @Column(name="IDS", precision=22, scale=0)
    public Long getIds() {
        return this.ids;
    }
    
    public void setIds(Long ids) {
        this.ids = ids;
    }
    
    @Column(name="SYS_NAME", length=2000)
    public String getSysName() {
        return this.sysName;
    }
    
    public void setSysName(String sysName) {
        this.sysName = sysName;
    }
    
    @Column(name="MODEL_NAME", length=2000)
    public String getModelName() {
        return this.modelName;
    }
    
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }
    
    @Column(name="PACKAGE_NAME", length=2000)
    public String getPackageName() {
        return this.packageName;
    }
    
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }
    
    @Column(name="STATE", precision=22, scale=0)
    public Long getState() {
        return this.state;
    }
    
    public void setState(Long state) {
        this.state = state;
    }
    
    @Column(name="REMARK", length=4000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLAN_DATE", length=7)
    public Date getPlanDate() {
        return this.planDate;
    }
    
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }
    
    @Column(name="IS_FINISHED", length=20)
    public String getIsFinished() {
        return this.isFinished;
    }
    
    public void setIsFinished(String isFinished) {
        this.isFinished = isFinished;
    }
    
    @Column(name="UPDATE_COUNT", precision=22, scale=0)
    public Long getUpdateCount() {
        return this.updateCount;
    }
    
    public void setUpdateCount(Long updateCount) {
        this.updateCount = updateCount;
    }




}


