package com.ai.aiga.domain;
// Generated 2017-4-11 19:38:50 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaDatabaseConfiScript generated by hbm2java
 */
@Entity
@Table(name="NA_DATABASE_CONFI_SCRIPT"
    ,schema="AIGA"
)
public class NaDatabaseConfiScript  implements java.io.Serializable {


     private Long id;
     private String database;
     private Long scriptNumber;
     private Date executeTime;
     private String ext1;
     private String ext2;
     private String ext3;
     private Long planId;
     @Column(name="PLAN_ID", unique=true, nullable=false, precision=14, scale=0)
   public Long getPlanId() {
		return planId;
	}


	public void setPlanId(Long planId) {
		this.planId = planId;
	}

    public NaDatabaseConfiScript() {
    }

	
    public NaDatabaseConfiScript(Long id) {
        this.id = id;
    }
    public NaDatabaseConfiScript(Long id, String database, Long scriptNumber, Date executeTime, String ext1, String ext2, String ext3) {
       this.id = id;
       this.database = database;
       this.scriptNumber = scriptNumber;
       this.executeTime = executeTime;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=12, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="DATABASE", length=200)
    public String getDatabase() {
        return this.database;
    }
    
    public void setDatabase(String database) {
        this.database = database;
    }
    
    @Column(name="SCRIPT_NUMBER", precision=12, scale=0)
    public Long getScriptNumber() {
        return this.scriptNumber;
    }
    
    public void setScriptNumber(Long scriptNumber) {
        this.scriptNumber = scriptNumber;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXECUTE_TIME", length=7)
    public Date getExecuteTime() {
        return this.executeTime;
    }
    
    public void setExecuteTime(Date executeTime) {
        this.executeTime = executeTime;
    }
    
    @Column(name="EXT_1", length=20)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=20)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=20)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


