package com.ai.aiga.domain;
// Generated 2017-4-13 15:56:17 by Hibernate Tools 3.2.2.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaHostConfigList generated by hbm2java
 */
@Entity
@Table(name="NA_HOST_CONFIG_LIST"
)
public class NaHostConfigList  implements java.io.Serializable {


     private Long id;
     private String configName;
     private String bmConfig;
     private String onlineConfigList;
     private String adjustConfigRecord;
     private String testConfigRecord;
     private String ZConfigRecord;
     private String SConfigRecord;
     private String MConfigRecord;
     private String devMan;
     private String testMan;
     private String bm;
     private String ext1;
     private String ext2;
     private String ext3;
     private Long planId;

    public NaHostConfigList() {
    }

	
    public NaHostConfigList(Long id) {
        this.id = id;
    }
    public NaHostConfigList(Long id, String configName, String bmConfig, String onlineConfigList, String adjustConfigRecord, String testConfigRecord, String ZConfigRecord, String SConfigRecord, String MConfigRecord, String devMan, String testMan, String bm, String ext1, String ext2, String ext3, Long planId) {
       this.id = id;
       this.configName = configName;
       this.bmConfig = bmConfig;
       this.onlineConfigList = onlineConfigList;
       this.adjustConfigRecord = adjustConfigRecord;
       this.testConfigRecord = testConfigRecord;
       this.ZConfigRecord = ZConfigRecord;
       this.SConfigRecord = SConfigRecord;
       this.MConfigRecord = MConfigRecord;
       this.devMan = devMan;
       this.testMan = testMan;
       this.bm = bm;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
       this.planId = planId;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_HOST_CONFIG_LIST$SEQ")
     @SequenceGenerator(name="NA_HOST_CONFIG_LIST$SEQ",sequenceName="NA_HOST_CONFIG_LIST$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="CONFIG_NAME", length=200)
    public String getConfigName() {
        return this.configName;
    }
    
    public void setConfigName(String configName) {
        this.configName = configName;
    }
    
    @Column(name="BM_CONFIG", length=2000)
    public String getBmConfig() {
        return this.bmConfig;
    }
    
    public void setBmConfig(String bmConfig) {
        this.bmConfig = bmConfig;
    }
    
    @Column(name="ONLINE_CONFIG_LIST", length=4000)
    public String getOnlineConfigList() {
        return this.onlineConfigList;
    }
    
    public void setOnlineConfigList(String onlineConfigList) {
        this.onlineConfigList = onlineConfigList;
    }
    
    @Column(name="ADJUST_CONFIG_RECORD", length=200)
    public String getAdjustConfigRecord() {
        return this.adjustConfigRecord;
    }
    
    public void setAdjustConfigRecord(String adjustConfigRecord) {
        this.adjustConfigRecord = adjustConfigRecord;
    }
    
    @Column(name="TEST_CONFIG_RECORD", length=200)
    public String getTestConfigRecord() {
        return this.testConfigRecord;
    }
    
    public void setTestConfigRecord(String testConfigRecord) {
        this.testConfigRecord = testConfigRecord;
    }
    
    @Column(name="Z_CONFIG_RECORD", length=200)
    public String getZConfigRecord() {
        return this.ZConfigRecord;
    }
    
    public void setZConfigRecord(String ZConfigRecord) {
        this.ZConfigRecord = ZConfigRecord;
    }
    
    @Column(name="S_CONFIG_RECORD", length=200)
    public String getSConfigRecord() {
        return this.SConfigRecord;
    }
    
    public void setSConfigRecord(String SConfigRecord) {
        this.SConfigRecord = SConfigRecord;
    }
    
    @Column(name="M_CONFIG_RECORD", length=200)
    public String getMConfigRecord() {
        return this.MConfigRecord;
    }
    
    public void setMConfigRecord(String MConfigRecord) {
        this.MConfigRecord = MConfigRecord;
    }
    
    @Column(name="DEV_MAN", length=200)
    public String getDevMan() {
        return this.devMan;
    }
    
    public void setDevMan(String devMan) {
        this.devMan = devMan;
    }
    
    @Column(name="TEST_MAN", length=200)
    public String getTestMan() {
        return this.testMan;
    }
    
    public void setTestMan(String testMan) {
        this.testMan = testMan;
    }
    
    @Column(name="BM", length=200)
    public String getBm() {
        return this.bm;
    }
    
    public void setBm(String bm) {
        this.bm = bm;
    }
    
    @Column(name="EXT_1", length=200)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=200)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=200)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }




}


