package com.ai.aiga.domain;
// Generated 2017-8-23 15:27:22 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaImageUpload generated by hbm2java
 */
@Entity
@Table(name="NA_IMAGE_UPLOAD")
public class NaImageUpload  implements java.io.Serializable {


     private long id;
     private String fileName;
     private String imgSrc;
     private String title;
     private String description;
     private Long likeCount;
     private Long commentCount;
     private String isShared;
     private Date createTime;
     private Long planId;
     private Long fileType;
     private Long createId;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaImageUpload() {
    }

    
	
    public NaImageUpload(String fileName, String isShared,
			Date createTime, Long fileType, Long createId) {
		super();
		this.fileName = fileName;
		this.isShared = isShared;
		this.createTime = createTime;
		this.fileType = fileType;
		this.createId = createId;
	}

	public NaImageUpload(String fileName, String imgSrc, String isShared,
			Date createTime, Long fileType, Long createId) {
		super();
		this.fileName = fileName;
		this.imgSrc = imgSrc;
		this.isShared = isShared;
		this.createTime = createTime;
		this.fileType = fileType;
		this.createId = createId;
	}
	


	public NaImageUpload(String fileName, String imgSrc, String title,
			String description, Long likeCount, Long commentCount,
			String isShared, Date createTime, Long fileType, Long createId) {
		super();
		this.fileName = fileName;
		this.imgSrc = imgSrc;
		this.title = title;
		this.description = description;
		this.likeCount = likeCount;
		this.commentCount = commentCount;
		this.isShared = isShared;
		this.createTime = createTime;
		this.fileType = fileType;
		this.createId = createId;
	}



	public NaImageUpload(long id, String fileName) {
        this.id = id;
        this.fileName = fileName;
    }
    public NaImageUpload(long id, String fileName, String imgSrc, String title, String description, Long likeCount, Long commentCount, String isShared, Date createTime, Long planId, Long fileType, Long createId, String ext1, String ext2, String ext3) {
       this.id = id;
       this.fileName = fileName;
       this.imgSrc = imgSrc;
       this.title = title;
       this.description = description;
       this.likeCount = likeCount;
       this.commentCount = commentCount;
       this.isShared = isShared;
       this.createTime = createTime;
       this.planId = planId;
       this.fileType = fileType;
       this.createId = createId;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_IMAGE_UPLOAD$SEQ")
     @SequenceGenerator(name="NA_IMAGE_UPLOAD$SEQ",sequenceName="NA_IMAGE_UPLOAD$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="FILE_NAME", nullable=false, length=100)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="IMG_SRC", length=100)
    public String getImgSrc() {
        return this.imgSrc;
    }
    
    public void setImgSrc(String imgSrc) {
        this.imgSrc = imgSrc;
    }
    
    @Column(name="TITLE", length=200)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="LIKE_COUNT", precision=10, scale=0)
    public Long getLikeCount() {
        return this.likeCount;
    }
    
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }
    
    @Column(name="COMMENT_COUNT", precision=10, scale=0)
    public Long getCommentCount() {
        return this.commentCount;
    }
    
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }
    
    @Column(name="IS_SHARED", length=1)
    public String getIsShared() {
        return this.isShared;
    }
    
    public void setIsShared(String isShared) {
        this.isShared = isShared;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", length=7)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="PLAN_ID", precision=10, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="FILE_TYPE", precision=10, scale=0)
    public Long getFileType() {
        return this.fileType;
    }
    
    public void setFileType(Long fileType) {
        this.fileType = fileType;
    }
    
    @Column(name="CREATE_ID", precision=10, scale=0)
    public Long getCreateId() {
        return this.createId;
    }
    
    public void setCreateId(Long createId) {
        this.createId = createId;
    }
    
    @Column(name="EXT_1", length=100)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=100)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=100)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


