package com.ai.aiga.domain;
// Generated 2017-4-11 14:29:27 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaInterfaceList generated by hbm2java
 */
@Entity
@Table(name="NA_INTERFACE_LIST"
    ,schema="AIGA"
)
public class NaInterfaceList  implements java.io.Serializable {


     private Long id;
     private String changeType;
     private String serviceName;
     private String serviceId;
     private String requireCode;
     private String devMan;
     private String requireMan;
     private Long planId;
     private String state;
     private String remarks;

    public NaInterfaceList() {
    }

	
    public NaInterfaceList(Long id) {
        this.id = id;
    }
    public NaInterfaceList(Long id, String changeType, String serviceName, String serviceId, String requireCode, String devMan, String requireMan, Long planId, String state, String remarks) {
       this.id = id;
       this.changeType = changeType;
       this.serviceName = serviceName;
       this.serviceId = serviceId;
       this.requireCode = requireCode;
       this.devMan = devMan;
       this.requireMan = requireMan;
       this.planId = planId;
       this.state = state;
       this.remarks = remarks;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_INTERFACE_LIST$SEQ")
    @SequenceGenerator(name="NA_INTERFACE_LIST$SEQ",sequenceName="NA_INTERFACE_LIST$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="CHANGE_TYPE", length=20)
    public String getChangeType() {
        return this.changeType;
    }
    
    public void setChangeType(String changeType) {
        this.changeType = changeType;
    }
    
    @Column(name="SERVICE_NAME", length=200)
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    
    @Column(name="SERVICE_ID", length=200)
    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }
    
    @Column(name="REQUIRE_CODE", length=200)
    public String getRequireCode() {
        return this.requireCode;
    }
    
    public void setRequireCode(String requireCode) {
        this.requireCode = requireCode;
    }
    
    @Column(name="DEV_MAN", length=200)
    public String getDevMan() {
        return this.devMan;
    }
    
    public void setDevMan(String devMan) {
        this.devMan = devMan;
    }
    
    @Column(name="REQUIRE_MAN", length=200)
    public String getRequireMan() {
        return this.requireMan;
    }
    
    public void setRequireMan(String requireMan) {
        this.requireMan = requireMan;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="STATE", length=100)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="REMARKS", length=1000)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


