package com.ai.aiga.domain;
// Generated 2017-3-27 16:11:40 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaOnlineTaskDistribute generated by hbm2java
 */
@Entity
@Table(name="NA_ONLINE_TASK_DISTRIBUTE"
    ,schema="AIGA"
)
public class NaOnlineTaskDistribute  implements java.io.Serializable {


     private Long taskId;
     private String taskName;
     private Long parentTaskId;
     private Long onlinePlan;
     private Long taskType;
     private Long dealOpId;
     private Long assignId;
     private Date assignDate;
     private Long dealState;
     private String onlinePlanName;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaOnlineTaskDistribute() {
    }

	
    public NaOnlineTaskDistribute(long taskId) {
        this.taskId = taskId;
    }
    public NaOnlineTaskDistribute(Long taskId, String taskName, Long parentTaskId, Long onlinePlan, Long taskType, Long dealOpId, Long assignId, Date assignDate, Long dealState, String onlinePlanName, String ext1, String ext2, String ext3) {
       this.taskId = taskId;
       this.taskName = taskName;
       this.parentTaskId = parentTaskId;
       this.onlinePlan = onlinePlan;
       this.taskType = taskType;
       this.dealOpId = dealOpId;
       this.assignId = assignId;
       this.assignDate = assignDate;
       this.dealState = dealState;
       this.onlinePlanName = onlinePlanName;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_ONLINE_TASK_DISTRIBUTE$SEQ")
    @SequenceGenerator(name="NA_ONLINE_TASK_DISTRIBUTE$SEQ",sequenceName="NA_ONLINE_TASK_DISTRIBUTE$SEQ",allocationSize=1)
    @Column(name="TASK_ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }
    
    @Column(name="TASK_NAME", length=200)
    public String getTaskName() {
        return this.taskName;
    }
    
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }
    
    @Column(name="PARENT_TASK_ID", precision=14, scale=0)
    public Long getParentTaskId() {
        return this.parentTaskId;
    }
    
    public void setParentTaskId(Long parentTaskId) {
        this.parentTaskId = parentTaskId;
    }
    
    @Column(name="ONLINE_PLAN", precision=14, scale=0)
    public Long getOnlinePlan() {
        return this.onlinePlan;
    }
    
    public void setOnlinePlan(Long onlinePlan) {
        this.onlinePlan = onlinePlan;
    }
    
    @Column(name="TASK_TYPE", precision=14, scale=0)
    public Long getTaskType() {
        return this.taskType;
    }
    
    public void setTaskType(Long taskType) {
        this.taskType = taskType;
    }
    
    @Column(name="DEAL_OP_ID", precision=14, scale=0)
    public Long getDealOpId() {
        return this.dealOpId;
    }
    
    public void setDealOpId(Long dealOpId) {
        this.dealOpId = dealOpId;
    }
    
    @Column(name="ASSIGN_ID", precision=14, scale=0)
    public Long getAssignId() {
        return this.assignId;
    }
    
    public void setAssignId(Long assignId) {
        this.assignId = assignId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ASSIGN_DATE", length=7)
    public Date getAssignDate() {
        return this.assignDate;
    }
    
    public void setAssignDate(Date assignDate) {
        this.assignDate = assignDate;
    }
    
    @Column(name="DEAL_STATE", precision=14, scale=0)
    public Long getDealState() {
        return this.dealState;
    }
    
    public void setDealState(Long dealState) {
        this.dealState = dealState;
    }
    
    @Column(name="ONLINE_PLAN_NAME", length=200)
    public String getOnlinePlanName() {
        return this.onlinePlanName;
    }
    
    public void setOnlinePlanName(String onlinePlanName) {
        this.onlinePlanName = onlinePlanName;
    }
    
    @Column(name="EXT1", length=200)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT2", length=200)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT3", length=200)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


