package com.ai.aiga.domain;
// Generated 2017-4-6 15:11:55 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaOnlineTaskResult generated by hbm2java
 */
@Entity
@Table(name="NA_ONLINE_TASK_RESULT"
    ,schema="AIGA"
)
public class NaOnlineTaskResult  implements java.io.Serializable {


     private Long dealId;
     private Long taskId;
     private String result;
     private Byte state;
     private Byte dealType;
     private Long autoPlanId;
     private Date createDate;
     private Date doneDate;
     private Long opId;
     private Date finishDate;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaOnlineTaskResult() {
    }

	
    public NaOnlineTaskResult(long dealId) {
        this.dealId = dealId;
    }
    public NaOnlineTaskResult(Long dealId, Long taskId, String result, Byte state, Byte dealType, Long autoPlanId, Date createDate, Date doneDate, Long opId, Date finishDate, String ext1, String ext2, String ext3) {
       this.dealId = dealId;
       this.taskId = taskId;
       this.result = result;
       this.state = state;
       this.dealType = dealType;
       this.autoPlanId = autoPlanId;
       this.createDate = createDate;
       this.doneDate = doneDate;
       this.opId = opId;
       this.finishDate = finishDate;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_ONLINE_TASK_RESULT$SEQ")
    @SequenceGenerator(name="NA_ONLINE_TASK_RESULT$SEQ",sequenceName="NA_ONLINE_TASK_RESULT$SEQ",allocationSize=1)
    @Column(name="DEAL_ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getDealId() {
        return this.dealId;
    }
    
    public void setDealId(Long dealId) {
        this.dealId = dealId;
    }
    
    @Column(name="TASK_ID", precision=14, scale=0)
    public Long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }
    
    @Column(name="RESULT", length=20)
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    
    @Column(name="STATE", precision=2, scale=0)
    public Byte getState() {
        return this.state;
    }
    
    public void setState(Byte state) {
        this.state = state;
    }
    
    @Column(name="DEAL_TYPE", precision=2, scale=0)
    public Byte getDealType() {
        return this.dealType;
    }
    
    public void setDealType(Byte dealType) {
        this.dealType = dealType;
    }
    
    @Column(name="AUTO_PLAN_ID", precision=14, scale=0)
    public Long getAutoPlanId() {
        return this.autoPlanId;
    }
    
    public void setAutoPlanId(Long autoPlanId) {
        this.autoPlanId = autoPlanId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DONE_DATE", length=7)
    public Date getDoneDate() {
        return this.doneDate;
    }
    
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }
    
    @Column(name="OP_ID", precision=14, scale=0)
    public Long getOpId() {
        return this.opId;
    }
    
    public void setOpId(Long opId) {
        this.opId = opId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FINISH_DATE", length=7)
    public Date getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }
    
    @Column(name="EXT1", length=20)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT2", length=20)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT3", length=20)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


