package com.ai.aiga.domain;
// Generated 2017-4-5 10:22:53 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaOnlinePlanBug generated by hbm2java
 */
@Entity
@Table(name="NA_ONLINE_PLAN_BUG"
    ,schema="AIGA"
)
public class NaOnlinePlanBug  implements java.io.Serializable {


     private Long bugId;
     private Long onlinePlans;
     private Byte bugType;
     private Byte bugLevel;
     private String requireName;
     private String question;
     private String reasons;
     private String methods;
     private String deal;
     private String type;
     private Long createId;
     private Date createDate;
     private Byte resove;
     private String doneDate;
     private String foundDate;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaOnlinePlanBug() {
    }

	
    public NaOnlinePlanBug(Long bugId) {
        this.bugId = bugId;
    }
    public NaOnlinePlanBug(Long bugId, Long onlinePlans, Byte bugType, Byte bugLevel, String requireName, String question, String reasons, String methods, String deal, String type, Long createId, Date createDate, Byte resove, String doneDate, String foundDate, String ext1, String ext2, String ext3) {
       this.bugId = bugId;
       this.onlinePlans = onlinePlans;
       this.bugType = bugType;
       this.bugLevel = bugLevel;
       this.requireName = requireName;
       this.question = question;
       this.reasons = reasons;
       this.methods = methods;
       this.deal = deal;
       this.type = type;
       this.createId = createId;
       this.createDate = createDate;
       this.resove = resove;
       this.doneDate = doneDate;
       this.foundDate = foundDate;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_ONLINE_PLAN_BUG$SEQ")
    @SequenceGenerator(name="NA_ONLINE_PLAN_BUG$SEQ",sequenceName="NA_ONLINE_PLAN_BUG$SEQ",allocationSize=1)
    @Column(name="BUG_ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getBugId() {
        return this.bugId;
    }
    
    public void setBugId(Long bugId) {
        this.bugId = bugId;
    }
    
    @Column(name="ONLINE_PLANS", precision=14, scale=0)
    public Long getOnlinePlans() {
        return this.onlinePlans;
    }
    
    public void setOnlinePlans(Long onlinePlans) {
        this.onlinePlans = onlinePlans;
    }
    
    @Column(name="BUG_TYPE", precision=2, scale=0)
    public Byte getBugType() {
        return this.bugType;
    }
    
    public void setBugType(Byte bugType) {
        this.bugType = bugType;
    }
    
    @Column(name="BUG_LEVEL", precision=2, scale=0)
    public Byte getBugLevel() {
        return this.bugLevel;
    }
    
    public void setBugLevel(Byte bugLevel) {
        this.bugLevel = bugLevel;
    }
    
    @Column(name="REQUIRE_NAME", length=200)
    public String getRequireName() {
        return this.requireName;
    }
    
    public void setRequireName(String requireName) {
        this.requireName = requireName;
    }
    
    @Column(name="QUESTION", length=400)
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    
    @Column(name="REASONS", length=400)
    public String getReasons() {
        return this.reasons;
    }
    
    public void setReasons(String reasons) {
        this.reasons = reasons;
    }
    
    @Column(name="METHODS", length=200)
    public String getMethods() {
        return this.methods;
    }
    
    public void setMethods(String methods) {
        this.methods = methods;
    }
    
    @Column(name="DEAL", length=200)
    public String getDeal() {
        return this.deal;
    }
    
    public void setDeal(String deal) {
        this.deal = deal;
    }
    
    @Column(name="TYPE", length=200)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="CREATE_ID", precision=14, scale=0)
    public Long getCreateId() {
        return this.createId;
    }
    
    public void setCreateId(Long createId) {
        this.createId = createId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    @Column(name="RESOVE", precision=2, scale=0)
    public Byte getResove() {
        return this.resove;
    }
    
    public void setResove(Byte resove) {
        this.resove = resove;
    }
    
    @Column(name="DONE_DATE", length=40)
    public String getDoneDate() {
        return this.doneDate;
    }
    
    public void setDoneDate(String doneDate) {
        this.doneDate = doneDate;
    }
    
    @Column(name="FOUND_DATE", length=40)
    public String getFoundDate() {
        return this.foundDate;
    }
    
    public void setFoundDate(String foundDate) {
        this.foundDate = foundDate;
    }
    
    @Column(name="EXT_1", length=20)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=20)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=20)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


