package com.ai.aiga.domain;
// Generated 2017-4-28 14:19:58 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaPerExecReport generated by hbm2java
 */
@Entity
@Table(name="NA_PER_EXEC_REPORT"
    ,schema="AIGA"
)
public class NaPerExecReport  implements java.io.Serializable {


     private Long reportId;
     private String perName;
     private String perSysId;
     private Long onlinePlanId;
     private String onlinePlanName;
     private Integer manualCaseCount;
     private String execManualTime;
     private Integer autoCaseCount;
     private String execAutoTime;
     private String execMaxTime;
     private String execSuccRate;
     private Integer bugCount;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaPerExecReport() {
    }

	
    public NaPerExecReport(Long reportId) {
        this.reportId = reportId;
    }
    public NaPerExecReport(Long reportId, String perName, String perSysId, Long onlinePlanId, String onlinePlanName, Integer manualCaseCount, String execManualTime, Integer autoCaseCount, String execAutoTime, String execMaxTime, String execSuccRate, Integer bugCount, String ext1, String ext2, String ext3) {
       this.reportId = reportId;
       this.perName = perName;
       this.perSysId = perSysId;
       this.onlinePlanId = onlinePlanId;
       this.onlinePlanName = onlinePlanName;
       this.manualCaseCount = manualCaseCount;
       this.execManualTime = execManualTime;
       this.autoCaseCount = autoCaseCount;
       this.execAutoTime = execAutoTime;
       this.execMaxTime = execMaxTime;
       this.execSuccRate = execSuccRate;
       this.bugCount = bugCount;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_PER_EXEC_REPORT$SEQ")
    @SequenceGenerator(name="NA_PER_EXEC_REPORT$SEQ",sequenceName="NA_PER_EXEC_REPORT$SEQ",allocationSize=1)
    @Column(name="REPORT_ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getReportId() {
        return this.reportId;
    }
    
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }
    
    @Column(name="PER_NAME", length=200)
    public String getPerName() {
        return this.perName;
    }
    
    public void setPerName(String perName) {
        this.perName = perName;
    }
    
    @Column(name="PER_SYS_ID", length=200)
    public String getPerSysId() {
        return this.perSysId;
    }
    
    public void setPerSysId(String perSysId) {
        this.perSysId = perSysId;
    }
    
    @Column(name="ONLINE_PLAN_ID", precision=12, scale=0)
    public Long getOnlinePlanId() {
        return this.onlinePlanId;
    }
    
    public void setOnlinePlanId(Long onlinePlanId) {
        this.onlinePlanId = onlinePlanId;
    }
    
    @Column(name="ONLINE_PLAN_NAME", length=200)
    public String getOnlinePlanName() {
        return this.onlinePlanName;
    }
    
    public void setOnlinePlanName(String onlinePlanName) {
        this.onlinePlanName = onlinePlanName;
    }
    
    @Column(name="MANUAL_CASE_COUNT", precision=22, scale=0)
    public Integer getManualCaseCount() {
        return this.manualCaseCount;
    }
    
    public void setManualCaseCount(Integer manualCaseCount) {
        this.manualCaseCount = manualCaseCount;
    }
    
    @Column(name="EXEC_MANUAL_TIME", length=20)
    public String getExecManualTime() {
        return this.execManualTime;
    }
    
    public void setExecManualTime(String execManualTime) {
        this.execManualTime = execManualTime;
    }
    
    @Column(name="AUTO_CASE_COUNT", precision=22, scale=0)
    public Integer getAutoCaseCount() {
        return this.autoCaseCount;
    }
    
    public void setAutoCaseCount(Integer autoCaseCount) {
        this.autoCaseCount = autoCaseCount;
    }
    
    @Column(name="EXEC_AUTO_TIME", length=20)
    public String getExecAutoTime() {
        return this.execAutoTime;
    }
    
    public void setExecAutoTime(String execAutoTime) {
        this.execAutoTime = execAutoTime;
    }
    
    @Column(name="EXEC_MAX_TIME", length=20)
    public String getExecMaxTime() {
        return this.execMaxTime;
    }
    
    public void setExecMaxTime(String execMaxTime) {
        this.execMaxTime = execMaxTime;
    }
    
    @Column(name="EXEC_SUCC_RATE", length=20)
    public String getExecSuccRate() {
        return this.execSuccRate;
    }
    
    public void setExecSuccRate(String execSuccRate) {
        this.execSuccRate = execSuccRate;
    }
    
    @Column(name="BUG_COUNT", precision=22, scale=0)
    public Integer getBugCount() {
        return this.bugCount;
    }
    
    public void setBugCount(Integer bugCount) {
        this.bugCount = bugCount;
    }
    
    @Column(name="EXT1", length=200)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT2", length=200)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT3", length=200)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


