package com.ai.aiga.domain;
// Generated 2017-4-13 15:56:17 by Hibernate Tools 3.2.2.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaProcessChangeList generated by hbm2java
 */
@Entity
@Table(name="NA_PROCESS_CHANGE_LIST"
)
public class NaProcessChangeList  implements java.io.Serializable {


     private Long id;
     private String requireId;
     private String devTaskId;
     private String devSubTaskName;
     private String devMan;
     private String devCompany;
     private String tfChangeType;
     private String seviceImpRange;
     private String systemScope;
     private String systemSubScope;
     private String sysName;
     private String sysModel;
     private String sysSubModel;
     private String funcDesc;
     private String templeteId;
     private Long concurrentNum;
     private String orginDb;
     private String targetDb;
     private String processName;
     private String exampleName;
     private String isPermanent;
     private String host;
     private String runUser;
     private String consumeMemory;
     private String onlineDate;
     private String offlineDate;
     private String searchCode;
     private String state;
     private String sysLevel;
     private String logName;
     private String runState;
     private String runContent;
     private String monitorScript;
     private String startScript;
     private String stopScript;
     private String logContent;
     private String exampleNum;
     private String sysImpLevel;
     private String isPermanents;
     private String warningType;
     private String maxNum;
     private Long processNum;
     private String warningLevelA;
     private String maxCpu;
     private String warningLevelB;
     private String memoryMax;
     private String warningLevelC;
     private String warningProvideMan;
     private String warningLevelD;
     private String warningTitle;
     private String warningContent;
     private String noticeTime;
     private String  warningDealGroup;//WARNING_DEAL_GROUP
     private Long planId;
    public NaProcessChangeList() {
    }

	
    public NaProcessChangeList(Long id) {
        this.id = id;
    }
    public NaProcessChangeList(Long id, String requireId, String devTaskId, String devSubTaskName, String devMan, String devCompany, String tfChangeType, String seviceImpRange, String systemScope, String systemSubScope, String sysName, String sysModel, String sysSubModel, String funcDesc, String templeteId, Long concurrentNum, String orginDb, String targetDb, String processName, String exampleName, String isPermanent, String host, String runUser, String consumeMemory, String onlineDate, String offlineDate, String searchCode, String state, String sysLevel, String logName, String runState, String runContent, String monitorScript, String startScript, String stopScript, String logContent, String exampleNum, String sysImpLevel, String isPermanents, String warningType, String maxNum, Long processNum, String warningLevelA, String maxCpu, String warningLevelB, String memoryMax, String warningLevelC, String warningProvideMan, String warningLevelD, String warningTitle, String warningContent, String noticeTime) {
       this.id = id;
       this.requireId = requireId;
       this.devTaskId = devTaskId;
       this.devSubTaskName = devSubTaskName;
       this.devMan = devMan;
       this.devCompany = devCompany;
       this.tfChangeType = tfChangeType;
       this.seviceImpRange = seviceImpRange;
       this.systemScope = systemScope;
       this.systemSubScope = systemSubScope;
       this.sysName = sysName;
       this.sysModel = sysModel;
       this.sysSubModel = sysSubModel;
       this.funcDesc = funcDesc;
       this.templeteId = templeteId;
       this.concurrentNum = concurrentNum;
       this.orginDb = orginDb;
       this.targetDb = targetDb;
       this.processName = processName;
       this.exampleName = exampleName;
       this.isPermanent = isPermanent;
       this.host = host;
       this.runUser = runUser;
       this.consumeMemory = consumeMemory;
       this.onlineDate = onlineDate;
       this.offlineDate = offlineDate;
       this.searchCode = searchCode;
       this.state = state;
       this.sysLevel = sysLevel;
       this.logName = logName;
       this.runState = runState;
       this.runContent = runContent;
       this.monitorScript = monitorScript;
       this.startScript = startScript;
       this.stopScript = stopScript;
       this.logContent = logContent;
       this.exampleNum = exampleNum;
       this.sysImpLevel = sysImpLevel;
       this.isPermanents = isPermanents;
       this.warningType = warningType;
       this.maxNum = maxNum;
       this.processNum = processNum;
       this.warningLevelA = warningLevelA;
       this.maxCpu = maxCpu;
       this.warningLevelB = warningLevelB;
       this.memoryMax = memoryMax;
       this.warningLevelC = warningLevelC;
       this.warningProvideMan = warningProvideMan;
       this.warningLevelD = warningLevelD;
       this.warningTitle = warningTitle;
       this.warningContent = warningContent;
       this.noticeTime = noticeTime;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_PROCESS_CHANGE_LIST$SEQ")
     @SequenceGenerator(name="NA_PROCESS_CHANGE_LIST$SEQ",sequenceName="NA_PROCESS_CHANGE_LIST$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="REQUIRE_ID", length=1000)
    public String getRequireId() {
        return this.requireId;
    }
    
    public void setRequireId(String requireId) {
        this.requireId = requireId;
    }
    @Column(name="WARNING_DEAL_GROUP", length=1000)
    public String getWarningDealGroup() {
		return warningDealGroup;
	}


	public void setWarningDealGroup(String warningDealGroup) {
		this.warningDealGroup = warningDealGroup;
	}


	@Column(name="DEV_TASK_ID", length=1000)
    public String getDevTaskId() {
        return this.devTaskId;
    }
    
    public void setDevTaskId(String devTaskId) {
        this.devTaskId = devTaskId;
    }
    
    @Column(name="DEV_SUB_TASK_NAME", length=1000)
    public String getDevSubTaskName() {
        return this.devSubTaskName;
    }
    
    public void setDevSubTaskName(String devSubTaskName) {
        this.devSubTaskName = devSubTaskName;
    }
    
    @Column(name="DEV_MAN", length=100)
    public String getDevMan() {
        return this.devMan;
    }
    
    public void setDevMan(String devMan) {
        this.devMan = devMan;
    }
    
    @Column(name="DEV_COMPANY", length=100)
    public String getDevCompany() {
        return this.devCompany;
    }
    
    public void setDevCompany(String devCompany) {
        this.devCompany = devCompany;
    }
    
    @Column(name="TF_CHANGE_TYPE", length=100)
    public String getTfChangeType() {
        return this.tfChangeType;
    }
    
    public void setTfChangeType(String tfChangeType) {
        this.tfChangeType = tfChangeType;
    }
    
    @Column(name="SEVICE_IMP_RANGE", length=10)
    public String getSeviceImpRange() {
        return this.seviceImpRange;
    }
    
    public void setSeviceImpRange(String seviceImpRange) {
        this.seviceImpRange = seviceImpRange;
    }
    
    @Column(name="SYSTEM_SCOPE", length=100)
    public String getSystemScope() {
        return this.systemScope;
    }
    
    public void setSystemScope(String systemScope) {
        this.systemScope = systemScope;
    }
    
    @Column(name="SYSTEM_SUB_SCOPE", length=1000)
    public String getSystemSubScope() {
        return this.systemSubScope;
    }
    
    public void setSystemSubScope(String systemSubScope) {
        this.systemSubScope = systemSubScope;
    }
    
    @Column(name="SYS_NAME", length=1000)
    public String getSysName() {
        return this.sysName;
    }
    
    public void setSysName(String sysName) {
        this.sysName = sysName;
    }
    
    @Column(name="SYS_MODEL", length=1000)
    public String getSysModel() {
        return this.sysModel;
    }
    
    public void setSysModel(String sysModel) {
        this.sysModel = sysModel;
    }
    
    @Column(name="SYS_SUB_MODEL", length=1000)
    public String getSysSubModel() {
        return this.sysSubModel;
    }
    
    public void setSysSubModel(String sysSubModel) {
        this.sysSubModel = sysSubModel;
    }
    
    @Column(name="FUNC_DESC", length=2000)
    public String getFuncDesc() {
        return this.funcDesc;
    }
    
    public void setFuncDesc(String funcDesc) {
        this.funcDesc = funcDesc;
    }
    
    @Column(name="TEMPLETE_ID", length=200)
    public String getTempleteId() {
        return this.templeteId;
    }
    
    public void setTempleteId(String templeteId) {
        this.templeteId = templeteId;
    }
    
    @Column(name="CONCURRENT_NUM", precision=22, scale=0)
    public Long getConcurrentNum() {
        return this.concurrentNum;
    }
    
    public void setConcurrentNum(Long concurrentNum) {
        this.concurrentNum = concurrentNum;
    }
    
    @Column(name="ORGIN_DB", length=200)
    public String getOrginDb() {
        return this.orginDb;
    }
    
    public void setOrginDb(String orginDb) {
        this.orginDb = orginDb;
    }
    
    @Column(name="TARGET_DB", length=200)
    public String getTargetDb() {
        return this.targetDb;
    }
    
    public void setTargetDb(String targetDb) {
        this.targetDb = targetDb;
    }
    
    @Column(name="PROCESS_NAME", length=200)
    public String getProcessName() {
        return this.processName;
    }
    
    public void setProcessName(String processName) {
        this.processName = processName;
    }
    
    @Column(name="EXAMPLE_NAME", length=200)
    public String getExampleName() {
        return this.exampleName;
    }
    
    public void setExampleName(String exampleName) {
        this.exampleName = exampleName;
    }
    
    @Column(name="IS_PERMANENT", length=200)
    public String getIsPermanent() {
        return this.isPermanent;
    }
    
    public void setIsPermanent(String isPermanent) {
        this.isPermanent = isPermanent;
    }
    
    @Column(name="HOST", length=200)
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    
    @Column(name="RUN_USER", length=200)
    public String getRunUser() {
        return this.runUser;
    }
    
    public void setRunUser(String runUser) {
        this.runUser = runUser;
    }
    
    @Column(name="CONSUME_MEMORY", length=200)
    public String getConsumeMemory() {
        return this.consumeMemory;
    }
    
    public void setConsumeMemory(String consumeMemory) {
        this.consumeMemory = consumeMemory;
    }
    
    @Column(name="ONLINE_DATE", length=200)
    public String getOnlineDate() {
        return this.onlineDate;
    }
    
    public void setOnlineDate(String onlineDate) {
        this.onlineDate = onlineDate;
    }
    
    @Column(name="OFFLINE_DATE", length=200)
    public String getOfflineDate() {
        return this.offlineDate;
    }
    
    public void setOfflineDate(String offlineDate) {
        this.offlineDate = offlineDate;
    }
    
    @Column(name="SEARCH_CODE", length=200)
    public String getSearchCode() {
        return this.searchCode;
    }
    
    public void setSearchCode(String searchCode) {
        this.searchCode = searchCode;
    }
    
    @Column(name="STATE", length=200)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="SYS_LEVEL", length=200)
    public String getSysLevel() {
        return this.sysLevel;
    }
    
    public void setSysLevel(String sysLevel) {
        this.sysLevel = sysLevel;
    }
    
    @Column(name="LOG_NAME", length=200)
    public String getLogName() {
        return this.logName;
    }
    
    public void setLogName(String logName) {
        this.logName = logName;
    }
    
    @Column(name="RUN_STATE", length=200)
    public String getRunState() {
        return this.runState;
    }
    
    public void setRunState(String runState) {
        this.runState = runState;
    }
    
    @Column(name="RUN_CONTENT", length=200)
    public String getRunContent() {
        return this.runContent;
    }
    
    public void setRunContent(String runContent) {
        this.runContent = runContent;
    }
    
    @Column(name="MONITOR_SCRIPT", length=200)
    public String getMonitorScript() {
        return this.monitorScript;
    }
    
    public void setMonitorScript(String monitorScript) {
        this.monitorScript = monitorScript;
    }
    
    @Column(name="START_SCRIPT", length=200)
    public String getStartScript() {
        return this.startScript;
    }
    
    public void setStartScript(String startScript) {
        this.startScript = startScript;
    }
    
    @Column(name="STOP_SCRIPT", length=200)
    public String getStopScript() {
        return this.stopScript;
    }
    
    public void setStopScript(String stopScript) {
        this.stopScript = stopScript;
    }
    
    @Column(name="LOG_CONTENT", length=200)
    public String getLogContent() {
        return this.logContent;
    }
    
    public void setLogContent(String logContent) {
        this.logContent = logContent;
    }
    
    @Column(name="EXAMPLE_NUM", length=200)
    public String getExampleNum() {
        return this.exampleNum;
    }
    
    public void setExampleNum(String exampleNum) {
        this.exampleNum = exampleNum;
    }
    
    @Column(name="SYS_IMP_LEVEL", length=200)
    public String getSysImpLevel() {
        return this.sysImpLevel;
    }
    
    public void setSysImpLevel(String sysImpLevel) {
        this.sysImpLevel = sysImpLevel;
    }
    
    @Column(name="IS_PERMANENTS", length=200)
    public String getIsPermanents() {
        return this.isPermanents;
    }
    
    public void setIsPermanents(String isPermanents) {
        this.isPermanents = isPermanents;
    }
    
    @Column(name="WARNING_TYPE", length=200)
    public String getWarningType() {
        return this.warningType;
    }
    
    public void setWarningType(String warningType) {
        this.warningType = warningType;
    }
    
    @Column(name="MAX_NUM", length=200)
    public String getMaxNum() {
        return this.maxNum;
    }
    
    public void setMaxNum(String maxNum) {
        this.maxNum = maxNum;
    }
    
    @Column(name="PROCESS_NUM", precision=22, scale=0)
    public Long getProcessNum() {
        return this.processNum;
    }
    
    public void setProcessNum(Long processNum) {
        this.processNum = processNum;
    }
    
    @Column(name="WARNING_LEVEL_A", length=200)
    public String getWarningLevelA() {
        return this.warningLevelA;
    }
    
    public void setWarningLevelA(String warningLevelA) {
        this.warningLevelA = warningLevelA;
    }
    
    @Column(name="MAX_CPU", length=200)
    public String getMaxCpu() {
        return this.maxCpu;
    }
    
    public void setMaxCpu(String maxCpu) {
        this.maxCpu = maxCpu;
    }
    
    @Column(name="WARNING_LEVEL_B", length=200)
    public String getWarningLevelB() {
        return this.warningLevelB;
    }
    
    public void setWarningLevelB(String warningLevelB) {
        this.warningLevelB = warningLevelB;
    }
    
    @Column(name="MEMORY_MAX", length=200)
    public String getMemoryMax() {
        return this.memoryMax;
    }
    
    public void setMemoryMax(String memoryMax) {
        this.memoryMax = memoryMax;
    }
    
    @Column(name="WARNING_LEVEL_C", length=200)
    public String getWarningLevelC() {
        return this.warningLevelC;
    }
    
    public void setWarningLevelC(String warningLevelC) {
        this.warningLevelC = warningLevelC;
    }
    
    @Column(name="WARNING_PROVIDE_MAN", length=200)
    public String getWarningProvideMan() {
        return this.warningProvideMan;
    }
    
    public void setWarningProvideMan(String warningProvideMan) {
        this.warningProvideMan = warningProvideMan;
    }
    
    @Column(name="WARNING_LEVEL_D", length=200)
    public String getWarningLevelD() {
        return this.warningLevelD;
    }
    
    public void setWarningLevelD(String warningLevelD) {
        this.warningLevelD = warningLevelD;
    }
    
    @Column(name="WARNING_TITLE", length=200)
    public String getWarningTitle() {
        return this.warningTitle;
    }
    
    public void setWarningTitle(String warningTitle) {
        this.warningTitle = warningTitle;
    }
    
    @Column(name="WARNING_CONTENT", length=200)
    public String getWarningContent() {
        return this.warningContent;
    }
    
    public void setWarningContent(String warningContent) {
        this.warningContent = warningContent;
    }
    
    @Column(name="NOTICE_TIME", length=200)
    public String getNoticeTime() {
        return this.noticeTime;
    }
    
    public void setNoticeTime(String noticeTime) {
        this.noticeTime = noticeTime;
    }




}


