package com.ai.aiga.domain;
// Generated 2017-4-26 11:08:56 by Hibernate Tools 3.2.2.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaQuantitativeRisk generated by hbm2java
 */
@Entity
@Table(name="NA_QUANTITATIVE_RISK"
)
public class NaQuantitativeRisk  implements java.io.Serializable {


     private Long id;
     private String totalScore;
     private String actualScore;
     private String riskGrade;
     private String approvalLevel;
     private String guaranteeMechanism;
     private Long planId;
     private String fileName;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaQuantitativeRisk() {
    }

	
    public NaQuantitativeRisk(Long id) {
        this.id = id;
    }
    public NaQuantitativeRisk(Long id, String totalScore, String actualScore, String riskGrade, String approvalLevel, String guaranteeMechanism, Long planId, String fileName, String ext1, String ext2, String ext3) {
       this.id = id;
       this.totalScore = totalScore;
       this.actualScore = actualScore;
       this.riskGrade = riskGrade;
       this.approvalLevel = approvalLevel;
       this.guaranteeMechanism = guaranteeMechanism;
       this.planId = planId;
       this.fileName = fileName;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_QUANTITATIVE_RISK$SEQ")
     @SequenceGenerator(name="NA_QUANTITATIVE_RISK$SEQ",sequenceName="NA_QUANTITATIVE_RISK$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="TOTAL_SCORE", length=200)
    public String getTotalScore() {
        return this.totalScore;
    }
    
    public void setTotalScore(String totalScore) {
        this.totalScore = totalScore;
    }
    
    @Column(name="ACTUAL_SCORE", length=200)
    public String getActualScore() {
        return this.actualScore;
    }
    
    public void setActualScore(String actualScore) {
        this.actualScore = actualScore;
    }
    
    @Column(name="RISK_GRADE", length=200)
    public String getRiskGrade() {
        return this.riskGrade;
    }
    
    public void setRiskGrade(String riskGrade) {
        this.riskGrade = riskGrade;
    }
    
    @Column(name="APPROVAL_LEVEL", length=200)
    public String getApprovalLevel() {
        return this.approvalLevel;
    }
    
    public void setApprovalLevel(String approvalLevel) {
        this.approvalLevel = approvalLevel;
    }
    
    @Column(name="GUARANTEE_MECHANISM", length=200)
    public String getGuaranteeMechanism() {
        return this.guaranteeMechanism;
    }
    
    public void setGuaranteeMechanism(String guaranteeMechanism) {
        this.guaranteeMechanism = guaranteeMechanism;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="FILE_NAME", length=200)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="EXT_1", length=200)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=200)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=200)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


