package com.ai.aiga.domain;
// Generated 2017-4-18 17:29:13 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaReleaseMessage generated by hbm2java
 */
@Entity
@Table(name="NA_RELEASE_MESSAGE"
    ,schema="AIGA"
)
public class NaReleaseMessage  implements java.io.Serializable {


     private Long id;
     private String newOnlineSituation;
     private String versionSituation;
     private String dbScriptSituation;
     private String testSituation;
     private String item;
     private Long planId;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaReleaseMessage() {
    }

	
    public NaReleaseMessage(Long id) {
        this.id = id;
    }
    public NaReleaseMessage(Long id, String newOnlineSituation, String versionSituation, String dbScriptSituation, String testSituation, String item, Long planId, String ext1, String ext2, String ext3) {
       this.id = id;
       this.newOnlineSituation = newOnlineSituation;
       this.versionSituation = versionSituation;
       this.dbScriptSituation = dbScriptSituation;
       this.testSituation = testSituation;
       this.item = item;
       this.planId = planId;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_RELEASE_MESSAGE$SEQ")
     @SequenceGenerator(name="NA_RELEASE_MESSAGE$SEQ",sequenceName="NA_RELEASE_MESSAGE$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="NEW_ONLINE_SITUATION", length=2000)
    public String getNewOnlineSituation() {
        return this.newOnlineSituation;
    }
    
    public void setNewOnlineSituation(String newOnlineSituation) {
        this.newOnlineSituation = newOnlineSituation;
    }
    
    @Column(name="VERSION_SITUATION", length=2000)
    public String getVersionSituation() {
        return this.versionSituation;
    }
    
    public void setVersionSituation(String versionSituation) {
        this.versionSituation = versionSituation;
    }
    
    @Column(name="DB_SCRIPT_SITUATION", length=2000)
    public String getDbScriptSituation() {
        return this.dbScriptSituation;
    }
    
    public void setDbScriptSituation(String dbScriptSituation) {
        this.dbScriptSituation = dbScriptSituation;
    }
    
    @Column(name="TEST_SITUATION", length=2000)
    public String getTestSituation() {
        return this.testSituation;
    }
    
    public void setTestSituation(String testSituation) {
        this.testSituation = testSituation;
    }
    
    @Column(name="ITEM", length=2000)
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    
    @Column(name="PLAN_ID", precision=14, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="EXT_1", length=20)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=20)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=20)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


