package com.ai.aiga.domain;
// Generated 2017-4-26 15:46:56 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaStaffConstructionReport generated by hbm2java
 */
@Entity
@Table(name="NA_STAFF_CONSTRUCTION_REPORT"
    ,schema="AIGA"
)
public class NaStaffConstructionReport  implements java.io.Serializable {


     private Long realId;
     private String statisticalMonth;
     private Date createTime;
     private Date updateTime;
     private Long staffId;
     private String staffName;
     private Integer caseNumQrelease;
     private Integer caseNumIncrQrelease;
     private Integer autoCaseNumQrelease;
     private Integer autoCaseNumIncrQrelease;
     private BigDecimal autoCaseCoverQrelease;
     private BigDecimal autoCaseCoverIncrQrelease;
     private Integer caseNumRelease;
     private Integer caseNumIncrRelease;
     private Integer autoCaseNumRelease;
     private Integer autoCaseNumIncrRelease;
     private BigDecimal autoCaseCoverRelease;
     private BigDecimal autoCaseCoverIncrRelease;

    public NaStaffConstructionReport() {
    }

	
    public NaStaffConstructionReport(Long realId) {
        this.realId = realId;
    }
    public NaStaffConstructionReport(Long realId, String statisticalMonth, Date createTime, Date updateTime, Long staffId, String staffName, Integer caseNumQrelease, Integer caseNumIncrQrelease, Integer autoCaseNumQrelease, Integer autoCaseNumIncrQrelease, BigDecimal autoCaseCoverQrelease, BigDecimal autoCaseCoverIncrQrelease, Integer caseNumRelease, Integer caseNumIncrRelease, Integer autoCaseNumRelease, Integer autoCaseNumIncrRelease, BigDecimal autoCaseCoverRelease, BigDecimal autoCaseCoverIncrRelease) {
       this.realId = realId;
       this.statisticalMonth = statisticalMonth;
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.staffId = staffId;
       this.staffName = staffName;
       this.caseNumQrelease = caseNumQrelease;
       this.caseNumIncrQrelease = caseNumIncrQrelease;
       this.autoCaseNumQrelease = autoCaseNumQrelease;
       this.autoCaseNumIncrQrelease = autoCaseNumIncrQrelease;
       this.autoCaseCoverQrelease = autoCaseCoverQrelease;
       this.autoCaseCoverIncrQrelease = autoCaseCoverIncrQrelease;
       this.caseNumRelease = caseNumRelease;
       this.caseNumIncrRelease = caseNumIncrRelease;
       this.autoCaseNumRelease = autoCaseNumRelease;
       this.autoCaseNumIncrRelease = autoCaseNumIncrRelease;
       this.autoCaseCoverRelease = autoCaseCoverRelease;
       this.autoCaseCoverIncrRelease = autoCaseCoverIncrRelease;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="STAFF_CONSTRUCTION_REPORT$SEQ")
    @SequenceGenerator(name="STAFF_CONSTRUCTION_REPORT$SEQ",sequenceName="STAFF_CONSTRUCTION_REPORT$SEQ",allocationSize=1)
    @Column(name="REAL_ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getRealId() {
        return this.realId;
    }
    
    public void setRealId(Long realId) {
        this.realId = realId;
    }
    
    @Column(name="STATISTICAL_MONTH", length=8)
    public String getStatisticalMonth() {
        return this.statisticalMonth;
    }
    
    public void setStatisticalMonth(String statisticalMonth) {
        this.statisticalMonth = statisticalMonth;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", length=7)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_TIME", length=7)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    @Column(name="STAFF_ID", precision=14, scale=0)
    public Long getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }
    
    @Column(name="STAFF_NAME", length=2000)
    public String getStaffName() {
        return this.staffName;
    }
    
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }
    
    @Column(name="CASE_NUM_QRELEASE", precision=8, scale=0)
    public Integer getCaseNumQrelease() {
        return this.caseNumQrelease;
    }
    
    public void setCaseNumQrelease(Integer caseNumQrelease) {
        this.caseNumQrelease = caseNumQrelease;
    }
    
    @Column(name="CASE_NUM_INCR_QRELEASE", precision=8, scale=0)
    public Integer getCaseNumIncrQrelease() {
        return this.caseNumIncrQrelease;
    }
    
    public void setCaseNumIncrQrelease(Integer caseNumIncrQrelease) {
        this.caseNumIncrQrelease = caseNumIncrQrelease;
    }
    
    @Column(name="AUTO_CASE_NUM_QRELEASE", precision=8, scale=0)
    public Integer getAutoCaseNumQrelease() {
        return this.autoCaseNumQrelease;
    }
    
    public void setAutoCaseNumQrelease(Integer autoCaseNumQrelease) {
        this.autoCaseNumQrelease = autoCaseNumQrelease;
    }
    
    @Column(name="AUTO_CASE_NUM_INCR_QRELEASE", precision=8, scale=0)
    public Integer getAutoCaseNumIncrQrelease() {
        return this.autoCaseNumIncrQrelease;
    }
    
    public void setAutoCaseNumIncrQrelease(Integer autoCaseNumIncrQrelease) {
        this.autoCaseNumIncrQrelease = autoCaseNumIncrQrelease;
    }
    
    @Column(name="AUTO_CASE_COVER_QRELEASE", precision=8, scale=4)
    public BigDecimal getAutoCaseCoverQrelease() {
        return this.autoCaseCoverQrelease;
    }
    
    public void setAutoCaseCoverQrelease(BigDecimal autoCaseCoverQrelease) {
        this.autoCaseCoverQrelease = autoCaseCoverQrelease;
    }
    
    @Column(name="AUTO_CASE_COVER_INCR_QRELEASE", precision=8, scale=4)
    public BigDecimal getAutoCaseCoverIncrQrelease() {
        return this.autoCaseCoverIncrQrelease;
    }
    
    public void setAutoCaseCoverIncrQrelease(BigDecimal autoCaseCoverIncrQrelease) {
        this.autoCaseCoverIncrQrelease = autoCaseCoverIncrQrelease;
    }
    
    @Column(name="CASE_NUM_RELEASE", precision=8, scale=0)
    public Integer getCaseNumRelease() {
        return this.caseNumRelease;
    }
    
    public void setCaseNumRelease(Integer caseNumRelease) {
        this.caseNumRelease = caseNumRelease;
    }
    
    @Column(name="CASE_NUM_INCR_RELEASE", precision=8, scale=0)
    public Integer getCaseNumIncrRelease() {
        return this.caseNumIncrRelease;
    }
    
    public void setCaseNumIncrRelease(Integer caseNumIncrRelease) {
        this.caseNumIncrRelease = caseNumIncrRelease;
    }
    
    @Column(name="AUTO_CASE_NUM_RELEASE", precision=8, scale=0)
    public Integer getAutoCaseNumRelease() {
        return this.autoCaseNumRelease;
    }
    
    public void setAutoCaseNumRelease(Integer autoCaseNumRelease) {
        this.autoCaseNumRelease = autoCaseNumRelease;
    }
    
    @Column(name="AUTO_CASE_NUM_INCR_RELEASE", precision=8, scale=0)
    public Integer getAutoCaseNumIncrRelease() {
        return this.autoCaseNumIncrRelease;
    }
    
    public void setAutoCaseNumIncrRelease(Integer autoCaseNumIncrRelease) {
        this.autoCaseNumIncrRelease = autoCaseNumIncrRelease;
    }
    
    @Column(name="AUTO_CASE_COVER_RELEASE", precision=8, scale=4)
    public BigDecimal getAutoCaseCoverRelease() {
        return this.autoCaseCoverRelease;
    }
    
    public void setAutoCaseCoverRelease(BigDecimal autoCaseCoverRelease) {
        this.autoCaseCoverRelease = autoCaseCoverRelease;
    }
    
    @Column(name="AUTO_CASE_COVER_INCR_RELEASE", precision=8, scale=4)
    public BigDecimal getAutoCaseCoverIncrRelease() {
        return this.autoCaseCoverIncrRelease;
    }
    
    public void setAutoCaseCoverIncrRelease(BigDecimal autoCaseCoverIncrRelease) {
        this.autoCaseCoverIncrRelease = autoCaseCoverIncrRelease;
    }




}


