package com.ai.aiga.domain;
// Generated 2017-3-1 10:25:12 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaTestCaseParam generated by hbm2java
 */
@Entity
@Table(name = "NA_TEST_CASE_PARAM")
public class NaTestCaseParam implements java.io.Serializable {

	private long paramId;
	private long factorId;
	private long testId;
	private String factorName;
	private String factorValue;
	private short factorOrder;
	private String remark;
	private Long creatorId;
	private Date createTime;
	private Long updateId;
	private Date updateTime;

	public NaTestCaseParam() {
	}

	public NaTestCaseParam(long paramId, long factorId, long testId, String factorName, short factorOrder) {
		this.paramId = paramId;
		this.factorId = factorId;
		this.testId = testId;
		this.factorName = factorName;
		this.factorOrder = factorOrder;
	}

	public NaTestCaseParam(long paramId, long factorId, long testId, String factorName, String factorValue,
			short factorOrder, Long creatorId, Date createTime, Long updateId, Date updateTime) {
		this.paramId = paramId;
		this.factorId = factorId;
		this.testId = testId;
		this.factorName = factorName;
		this.factorValue = factorValue;
		this.factorOrder = factorOrder;
		this.creatorId = creatorId;
		this.createTime = createTime;
		this.updateId = updateId;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NA_TEST_CASE_PARAM$SEQ")
	@SequenceGenerator(name = "NA_TEST_CASE_PARAM$SEQ", sequenceName = "NA_TEST_CASE_PARAM$SEQ", allocationSize = 1)
	@Column(name = "PARAM_ID", unique = true, nullable = false, precision = 14, scale = 0)
	public long getParamId() {
		return this.paramId;
	}

	public void setParamId(long paramId) {
		this.paramId = paramId;
	}

	@Column(name = "FACTOR_ID", nullable = false, precision = 14, scale = 0)
	public long getFactorId() {
		return this.factorId;
	}

	public void setFactorId(long factorId) {
		this.factorId = factorId;
	}

	@Column(name = "TEST_ID", nullable = false, precision = 14, scale = 0)
	public long getTestId() {
		return this.testId;
	}

	public void setTestId(long testId) {
		this.testId = testId;
	}

	@Column(name = "FACTOR_NAME", nullable = false, length = 100)
	public String getFactorName() {
		return this.factorName;
	}

	public void setFactorName(String factorName) {
		this.factorName = factorName;
	}

	@Column(name = "FACTOR_VALUE", length = 1000)
	public String getFactorValue() {
		return this.factorValue;
	}

	public void setFactorValue(String factorValue) {
		this.factorValue = factorValue;
	}

	@Column(name = "FACTOR_ORDER", nullable = false, precision = 3, scale = 0)
	public short getFactorOrder() {
		return this.factorOrder;
	}

	public void setFactorOrder(short factorOrder) {
		this.factorOrder = factorOrder;
	}

	@Column(name = "CREATOR_ID", precision = 14, scale = 0)
	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 11)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "UPDATE_ID", precision = 14, scale = 0)
	public Long getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(Long updateId) {
		this.updateId = updateId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", length = 11)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "REMARK", length = 400)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	

}
