package com.ai.aiga.domain;
// Generated 2017-4-5 17:35:50 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaTeamEmployeeRel generated by hbm2java
 */
@Entity
@Table(name="NA_TEAM_EMPLOYEE_REL"
    ,schema="AIGA"
)
public class NaTeamEmployeeRel  implements java.io.Serializable {


     private Long id;
     private Long teamId;
     private Long empId;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaTeamEmployeeRel() {
    }

	
    public NaTeamEmployeeRel(Long id) {
        this.id = id;
    }
    public NaTeamEmployeeRel(Long id, Long teamId, Long empId, String ext1, String ext2, String ext3) {
       this.id = id;
       this.teamId = teamId;
       this.empId = empId;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_TEAM_EMPLOYEE_REL$SEQ")
     @SequenceGenerator(name="NA_TEAM_EMPLOYEE_REL$SEQ",sequenceName="NA_TEAM_EMPLOYEE_REL$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=12, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="TEAM_ID", precision=12, scale=0)
    public Long getTeamId() {
        return this.teamId;
    }
    
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }
    
    @Column(name="EMP_ID", precision=12, scale=0)
    public Long getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Long empId) {
        this.empId = empId;
    }
    
    @Column(name="EXT_1", length=20)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=20)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=20)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


