package com.ai.aiga.domain;
// Generated 2017-3-1 15:45:07 by Hibernate Tools 3.2.2.GA


import java.sql.Clob;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * NaUiComponent generated by hbm2java
 */
@Entity
@Table(name="NA_UI_COMPONENT"
    ,schema="AIGA"
)
public class NaUiComponent  implements java.io.Serializable {


     private Long compId;
     private Long parentId;
     private String ifLeaf;
     private String compName;
     private String compDesc;
     private String compScript;
     private Long sysId;
     private Long sysSubId;
     private Long funId;
     private Long creatorId;
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date createTime;
     private Long updateId;
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date updateTime;

    public NaUiComponent() {
    }

	
    public NaUiComponent(Long compId) {
        this.compId = compId;
    }
    public NaUiComponent(Long compId, Long parentId, String ifLeaf, String compName, String compDesc, String compScript, Long sysId, Long sysSubId, Long funId, Long creatorId, Date createTime, Long updateId, Date updateTime) {
       this.compId = compId;
       this.parentId = parentId;
       this.ifLeaf = ifLeaf;
       this.compName = compName;
       this.compDesc = compDesc;
       this.compScript = compScript;
       this.sysId = sysId;
       this.sysSubId = sysSubId;
       this.funId = funId;
       this.creatorId = creatorId;
       this.createTime = createTime;
       this.updateId = updateId;
       this.updateTime = updateTime;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_UI_COMPONENT$SEQ")
    @SequenceGenerator(name="NA_UI_COMPONENT$SEQ",sequenceName="NA_UI_COMPONENT$SEQ",allocationSize=1)
    @Column(name="COMP_ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getCompId() {
        return this.compId;
    }
    
    public void setCompId(Long compId) {
        this.compId = compId;
    }
    
    @Column(name="PARENT_ID", precision=14, scale=0)
    public Long getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
    
    @Column(name="IF_LEAF", length=2)
    public String getIfLeaf() {
        return this.ifLeaf;
    }
    
    public void setIfLeaf(String ifLeaf) {
        this.ifLeaf = ifLeaf;
    }
    
    @Column(name="COMP_NAME")
    public String getCompName() {
        return this.compName;
    }
    
    public void setCompName(String compName) {
        this.compName = compName;
    }
    
    @Column(name="COMP_DESC", length=4000)
    public String getCompDesc() {
        return this.compDesc;
    }
    
    public void setCompDesc(String compDesc) {
        this.compDesc = compDesc;
    }
    @Lob
	@Basic(fetch = FetchType.LAZY)
    @Column(name="COMP_SCRIPT", columnDefinition = "CLOB")
    public String getCompScript() {
        return this.compScript;
    }
    
    public void setCompScript(String compScript) {
        this.compScript = compScript;
    }
    
    @Column(name="SYS_ID", precision=14, scale=0)
    public Long getSysId() {
        return this.sysId;
    }
    
    public void setSysId(Long sysId) {
        this.sysId = sysId;
    }
    
    @Column(name="SYS_SUB_ID", precision=14, scale=0)
    public Long getSysSubId() {
        return this.sysSubId;
    }
    
    public void setSysSubId(Long sysSubId) {
        this.sysSubId = sysSubId;
    }
    
    @Column(name="FUN_ID", precision=14, scale=0)
    public Long getFunId() {
        return this.funId;
    }
    
    public void setFunId(Long funId) {
        this.funId = funId;
    }
    
    @Column(name="CREATOR_ID", precision=14, scale=0)
    public Long getCreatorId() {
        return this.creatorId;
    }
    
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", length=7)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="UPDATE_ID", precision=14, scale=0)
    public Long getUpdateId() {
        return this.updateId;
    }
    
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_TIME", length=7)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }




}


