package com.ai.aiga.domain;
// Generated 2017-3-1 15:48:25 by Hibernate Tools 3.2.2.GA


import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaUiParam generated by hbm2java
 */
@Entity
@Table(name="NA_UI_PARAM"
    ,schema="AIGA"
)
public class NaUiParam  implements java.io.Serializable {


     private Long paramId;
     private Long parentId;
     private String ifLeaf;
     private String paramName;
     private Clob paramValue;
     private String paramDesc;
     private String paramSql;
     private String paramExpect;
     private Long compId;
     private Long creatorId;
     private Date createTime;

    public NaUiParam() {
    }

	
    public NaUiParam(Long paramId) {
        this.paramId = paramId;
    }
    public NaUiParam(Long paramId, Long parentId, String ifLeaf, String paramName, Clob paramValue, String paramDesc, String paramSql, String paramExpect, Long compId, Long creatorId, Date createTime) {
       this.paramId = paramId;
       this.parentId = parentId;
       this.ifLeaf = ifLeaf;
       this.paramName = paramName;
       this.paramValue = paramValue;
       this.paramDesc = paramDesc;
       this.paramSql = paramSql;
       this.paramExpect = paramExpect;
       this.compId = compId;
       this.creatorId = creatorId;
       this.createTime = createTime;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_UI_PARAM$SEQ")
    @SequenceGenerator(name="NA_UI_PARAM$SEQ",sequenceName="NA_UI_PARAM$SEQ",allocationSize=1)
    @Column(name="PARAM_ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getParamId() {
        return this.paramId;
    }
    
    public void setParamId(Long paramId) {
        this.paramId = paramId;
    }
    
    @Column(name="PARENT_ID", precision=14, scale=0)
    public Long getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
    
    @Column(name="IF_LEAF", length=2)
    public String getIfLeaf() {
        return this.ifLeaf;
    }
    
    public void setIfLeaf(String ifLeaf) {
        this.ifLeaf = ifLeaf;
    }
    
    @Column(name="PARAM_NAME")
    public String getParamName() {
        return this.paramName;
    }
    
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }
    
    @Column(name="PARAM_VALUE")
    public Clob getParamValue() {
        return this.paramValue;
    }
    
    public void setParamValue(Clob paramValue) {
        this.paramValue = paramValue;
    }
    
    @Column(name="PARAM_DESC", length=4000)
    public String getParamDesc() {
        return this.paramDesc;
    }
    
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc;
    }
    
    @Column(name="PARAM_SQL", length=4000)
    public String getParamSql() {
        return this.paramSql;
    }
    
    public void setParamSql(String paramSql) {
        this.paramSql = paramSql;
    }
    
    @Column(name="PARAM_EXPECT", length=4000)
    public String getParamExpect() {
        return this.paramExpect;
    }
    
    public void setParamExpect(String paramExpect) {
        this.paramExpect = paramExpect;
    }
    
    @Column(name="COMP_ID", precision=14, scale=0)
    public Long getCompId() {
        return this.compId;
    }
    
    public void setCompId(Long compId) {
        this.compId = compId;
    }
    
    @Column(name="CREATOR_ID", precision=14, scale=0)
    public Long getCreatorId() {
        return this.creatorId;
    }
    
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", length=7)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


