package com.ai.aiga.domain;
// Generated 2017-4-24 15:00:18 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaWarningShield generated by hbm2java
 */
@Entity
@Table(name="NA_WARNING_SHIELD"
)
public class NaWarningShield  implements java.io.Serializable {


     private BigDecimal id;
     private String shieldHost;
     private String ipAddress;
     private String shieldTime;
     private String shieldContent;
     private BigDecimal planId;
     private String fileName;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaWarningShield() {
    }

	
    public NaWarningShield(BigDecimal id) {
        this.id = id;
    }
    public NaWarningShield(BigDecimal id, String shieldHost, String ipAddress, String shieldTime, String shieldContent, BigDecimal planId, String fileName, String ext1, String ext2, String ext3) {
       this.id = id;
       this.shieldHost = shieldHost;
       this.ipAddress = ipAddress;
       this.shieldTime = shieldTime;
       this.shieldContent = shieldContent;
       this.planId = planId;
       this.fileName = fileName;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_WARNING_SHIELD$SEQ")
     @SequenceGenerator(name="NA_WARNING_SHIELD$SEQ",sequenceName="NA_WARNING_SHIELD$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    
    @Column(name="SHIELD_HOST", length=100)
    public String getShieldHost() {
        return this.shieldHost;
    }
    
    public void setShieldHost(String shieldHost) {
        this.shieldHost = shieldHost;
    }
    
    @Column(name="IP_ADDRESS", length=100)
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    
    @Column(name="SHIELD_TIME", length=100)
    public String getShieldTime() {
        return this.shieldTime;
    }
    
    public void setShieldTime(String shieldTime) {
        this.shieldTime = shieldTime;
    }
    
    @Column(name="SHIELD_CONTENT", length=100)
    public String getShieldContent() {
        return this.shieldContent;
    }
    
    public void setShieldContent(String shieldContent) {
        this.shieldContent = shieldContent;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public BigDecimal getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(BigDecimal planId) {
        this.planId = planId;
    }
    
    @Column(name="FILE_NAME", length=100)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="EXT_1", length=100)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=100)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=100)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


