package com.ai.aiga.domain;
// Generated 2017-4-25 17:08:57 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OnlineSituationReport generated by hbm2java
 */
@Entity
@Table(name="ONLINE_SITUATION_REPORT"
    ,schema="AIGA"
)
public class OnlineSituationReport  implements java.io.Serializable {


     private long onlinePlan;
     private String onlinePlanName;
     private BigDecimal types;
     private String month;
     private Date planDate;
     private BigDecimal isApplyTime;
     private String onlineReqRevPassRate;
     private Integer exceptionNum;
     private Integer faultNum;
     private Integer bugNum;
     private Integer remainNum;
     private String funCheckDuration;
     private String proCheckDuration;
     private String bossCheckDuration;
     private String allDuration;
     private Integer faultValidNum;
     private Integer faultInvalidNum;
     private String productCheckDuration;

    public OnlineSituationReport() {
    }

	
    public OnlineSituationReport(long onlinePlan, String onlinePlanName) {
        this.onlinePlan = onlinePlan;
        this.onlinePlanName = onlinePlanName;
    }
    public OnlineSituationReport(long onlinePlan, String onlinePlanName, BigDecimal types, String month, Date planDate, BigDecimal isApplyTime, String onlineReqRevPassRate, Integer exceptionNum, Integer faultNum, Integer bugNum, Integer remainNum, String funCheckDuration, String proCheckDuration, String bossCheckDuration, String allDuration, Integer faultValidNum, Integer faultInvalidNum, String productCheckDuration) {
       this.onlinePlan = onlinePlan;
       this.onlinePlanName = onlinePlanName;
       this.types = types;
       this.month = month;
       this.planDate = planDate;
       this.isApplyTime = isApplyTime;
       this.onlineReqRevPassRate = onlineReqRevPassRate;
       this.exceptionNum = exceptionNum;
       this.faultNum = faultNum;
       this.bugNum = bugNum;
       this.remainNum = remainNum;
       this.funCheckDuration = funCheckDuration;
       this.proCheckDuration = proCheckDuration;
       this.bossCheckDuration = bossCheckDuration;
       this.allDuration = allDuration;
       this.faultValidNum = faultValidNum;
       this.faultInvalidNum = faultInvalidNum;
       this.productCheckDuration = productCheckDuration;
    }
   
     @Id 
    
    @Column(name="ONLINE_PLAN", unique=true, nullable=false, precision=12, scale=0)
    public long getOnlinePlan() {
        return this.onlinePlan;
    }
    
    public void setOnlinePlan(long onlinePlan) {
        this.onlinePlan = onlinePlan;
    }
    
    @Column(name="ONLINE_PLAN_NAME", nullable=false, length=200)
    public String getOnlinePlanName() {
        return this.onlinePlanName;
    }
    
    public void setOnlinePlanName(String onlinePlanName) {
        this.onlinePlanName = onlinePlanName;
    }
    
    @Column(name="TYPES", precision=22, scale=0)
    public BigDecimal getTypes() {
        return this.types;
    }
    
    public void setTypes(BigDecimal types) {
        this.types = types;
    }
    
    @Column(name="MONTH", length=8)
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLAN_DATE", length=7)
    public Date getPlanDate() {
        return this.planDate;
    }
    
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }
    
    @Column(name="IS_APPLY_TIME", precision=22, scale=0)
    public BigDecimal getIsApplyTime() {
        return this.isApplyTime;
    }
    
    public void setIsApplyTime(BigDecimal isApplyTime) {
        this.isApplyTime = isApplyTime;
    }
    
    @Column(name="ONLINE_REQ_REV_PASS_RATE", length=8)
    public String getOnlineReqRevPassRate() {
        return this.onlineReqRevPassRate;
    }
    
    public void setOnlineReqRevPassRate(String onlineReqRevPassRate) {
        this.onlineReqRevPassRate = onlineReqRevPassRate;
    }
    
    @Column(name="EXCEPTION_NUM", precision=8, scale=0)
    public Integer getExceptionNum() {
        return this.exceptionNum;
    }
    
    public void setExceptionNum(Integer exceptionNum) {
        this.exceptionNum = exceptionNum;
    }
    
    @Column(name="FAULT_NUM", precision=8, scale=0)
    public Integer getFaultNum() {
        return this.faultNum;
    }
    
    public void setFaultNum(Integer faultNum) {
        this.faultNum = faultNum;
    }
    
    @Column(name="BUG_NUM", precision=8, scale=0)
    public Integer getBugNum() {
        return this.bugNum;
    }
    
    public void setBugNum(Integer bugNum) {
        this.bugNum = bugNum;
    }
    
    @Column(name="REMAIN_NUM", precision=8, scale=0)
    public Integer getRemainNum() {
        return this.remainNum;
    }
    
    public void setRemainNum(Integer remainNum) {
        this.remainNum = remainNum;
    }
    
    @Column(name="FUN_CHECK_DURATION", length=100)
    public String getFunCheckDuration() {
        return this.funCheckDuration;
    }
    
    public void setFunCheckDuration(String funCheckDuration) {
        this.funCheckDuration = funCheckDuration;
    }
    
    @Column(name="PRO_CHECK_DURATION", length=100)
    public String getProCheckDuration() {
        return this.proCheckDuration;
    }
    
    public void setProCheckDuration(String proCheckDuration) {
        this.proCheckDuration = proCheckDuration;
    }
    
    @Column(name="BOSS_CHECK_DURATION", length=100)
    public String getBossCheckDuration() {
        return this.bossCheckDuration;
    }
    
    public void setBossCheckDuration(String bossCheckDuration) {
        this.bossCheckDuration = bossCheckDuration;
    }
    
    @Column(name="ALL_DURATION", length=100)
    public String getAllDuration() {
        return this.allDuration;
    }
    
    public void setAllDuration(String allDuration) {
        this.allDuration = allDuration;
    }
    
    @Column(name="FAULT_VALID_NUM", precision=8, scale=0)
    public Integer getFaultValidNum() {
        return this.faultValidNum;
    }
    
    public void setFaultValidNum(Integer faultValidNum) {
        this.faultValidNum = faultValidNum;
    }
    
    @Column(name="FAULT_INVALID_NUM", precision=8, scale=0)
    public Integer getFaultInvalidNum() {
        return this.faultInvalidNum;
    }
    
    public void setFaultInvalidNum(Integer faultInvalidNum) {
        this.faultInvalidNum = faultInvalidNum;
    }
    
    @Column(name="PRODUCT_CHECK_DURATION", length=100)
    public String getProductCheckDuration() {
        return this.productCheckDuration;
    }
    
    public void setProductCheckDuration(String productCheckDuration) {
        this.productCheckDuration = productCheckDuration;
    }




}


