package com.ai.aiga.domain;
// Generated 2018-3-20 16:05:25 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PCsfReportBymonth generated by hbm2java
 */
@Entity
@Table(name="P_CSF_REPORT_BYMONTH")
public class PCsfReportBymonth  implements java.io.Serializable {


     private int id;
     private String monthDate;
     private String centerCode;
     private String centerName;
     private Long csfRegisterNum;
     private Long csfRegisterAdd;
     private Long csfActivityNum;
     private BigDecimal csfMonthlyAdjustment;
     private BigDecimal lastCsfMonthlyAdjustment;
     private String adjustmentRateChange;
     private String csfAvgTime;
     private String lastCsfAvgTime;
     private String avgtimeRateChange;
     private String csfSuccRate;
     private String lastCsfSuccRate;
     private String succRateChage;
     private Date insertDate;

    public PCsfReportBymonth() {
    }

	
    public PCsfReportBymonth(int id) {
        this.id = id;
    }
    public PCsfReportBymonth(int id, String monthDate, String centerCode, String centerName, Long csfRegisterNum, Long csfRegisterAdd, Long csfActivityNum, BigDecimal csfMonthlyAdjustment, BigDecimal lastCsfMonthlyAdjustment, String adjustmentRateChange, String csfAvgTime, String lastCsfAvgTime, String avgtimeRateChange, String csfSuccRate, String lastCsfSuccRate, String succRateChage, Date insertDate) {
       this.id = id;
       this.monthDate = monthDate;
       this.centerCode = centerCode;
       this.centerName = centerName;
       this.csfRegisterNum = csfRegisterNum;
       this.csfRegisterAdd = csfRegisterAdd;
       this.csfActivityNum = csfActivityNum;
       this.csfMonthlyAdjustment = csfMonthlyAdjustment;
       this.lastCsfMonthlyAdjustment = lastCsfMonthlyAdjustment;
       this.adjustmentRateChange = adjustmentRateChange;
       this.csfAvgTime = csfAvgTime;
       this.lastCsfAvgTime = lastCsfAvgTime;
       this.avgtimeRateChange = avgtimeRateChange;
       this.csfSuccRate = csfSuccRate;
       this.lastCsfSuccRate = lastCsfSuccRate;
       this.succRateChage = succRateChage;
       this.insertDate = insertDate;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=8, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="MONTH_DATE", length=8)
    public String getMonthDate() {
        return this.monthDate;
    }
    
    public void setMonthDate(String monthDate) {
        this.monthDate = monthDate;
    }
    
    @Column(name="CENTER_CODE", length=32)
    public String getCenterCode() {
        return this.centerCode;
    }
    
    public void setCenterCode(String centerCode) {
        this.centerCode = centerCode;
    }
    
    @Column(name="CENTER_NAME", length=32)
    public String getCenterName() {
        return this.centerName;
    }
    
    public void setCenterName(String centerName) {
        this.centerName = centerName;
    }
    
    @Column(name="CSF_REGISTER_NUM", precision=16, scale=0)
    public Long getCsfRegisterNum() {
        return this.csfRegisterNum;
    }
    
    public void setCsfRegisterNum(Long csfRegisterNum) {
        this.csfRegisterNum = csfRegisterNum;
    }
    
    @Column(name="CSF_REGISTER_ADD", precision=16, scale=0)
    public Long getCsfRegisterAdd() {
        return this.csfRegisterAdd;
    }
    
    public void setCsfRegisterAdd(Long csfRegisterAdd) {
        this.csfRegisterAdd = csfRegisterAdd;
    }
    
    @Column(name="CSF_ACTIVITY_NUM", precision=16, scale=0)
    public Long getCsfActivityNum() {
        return this.csfActivityNum;
    }
    
    public void setCsfActivityNum(Long csfActivityNum) {
        this.csfActivityNum = csfActivityNum;
    }
    
    @Column(name="CSF_MONTHLY_ADJUSTMENT", precision=32, scale=0)
    public BigDecimal getCsfMonthlyAdjustment() {
        return this.csfMonthlyAdjustment;
    }
    
    public void setCsfMonthlyAdjustment(BigDecimal csfMonthlyAdjustment) {
        this.csfMonthlyAdjustment = csfMonthlyAdjustment;
    }
    
    @Column(name="LAST_CSF_MONTHLY_ADJUSTMENT", precision=32, scale=0)
    public BigDecimal getLastCsfMonthlyAdjustment() {
        return this.lastCsfMonthlyAdjustment;
    }
    
    public void setLastCsfMonthlyAdjustment(BigDecimal lastCsfMonthlyAdjustment) {
        this.lastCsfMonthlyAdjustment = lastCsfMonthlyAdjustment;
    }
    
    @Column(name="ADJUSTMENT_RATE_CHANGE", length=32)
    public String getAdjustmentRateChange() {
        return this.adjustmentRateChange;
    }
    
    public void setAdjustmentRateChange(String adjustmentRateChange) {
        this.adjustmentRateChange = adjustmentRateChange;
    }
    
    @Column(name="CSF_AVG_TIME", length=32)
    public String getCsfAvgTime() {
        return this.csfAvgTime;
    }
    
    public void setCsfAvgTime(String csfAvgTime) {
        this.csfAvgTime = csfAvgTime;
    }
    
    @Column(name="LAST_CSF_AVG_TIME", length=32)
    public String getLastCsfAvgTime() {
        return this.lastCsfAvgTime;
    }
    
    public void setLastCsfAvgTime(String lastCsfAvgTime) {
        this.lastCsfAvgTime = lastCsfAvgTime;
    }
    
    @Column(name="AVGTIME_RATE_CHANGE", length=32)
    public String getAvgtimeRateChange() {
        return this.avgtimeRateChange;
    }
    
    public void setAvgtimeRateChange(String avgtimeRateChange) {
        this.avgtimeRateChange = avgtimeRateChange;
    }
    
    @Column(name="CSF_SUCC_RATE", length=32)
    public String getCsfSuccRate() {
        return this.csfSuccRate;
    }
    
    public void setCsfSuccRate(String csfSuccRate) {
        this.csfSuccRate = csfSuccRate;
    }
    
    @Column(name="LAST_CSF_SUCC_RATE", length=32)
    public String getLastCsfSuccRate() {
        return this.lastCsfSuccRate;
    }
    
    public void setLastCsfSuccRate(String lastCsfSuccRate) {
        this.lastCsfSuccRate = lastCsfSuccRate;
    }
    
    @Column(name="SUCC_RATE_CHAGE", length=32)
    public String getSuccRateChage() {
        return this.succRateChage;
    }
    
    public void setSuccRateChage(String succRateChage) {
        this.succRateChage = succRateChage;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INSERT_DATE", length=7)
    public Date getInsertDate() {
        return this.insertDate;
    }
    
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }




}


