package com.ai.aiga.domain;
// Generated 2018-3-22 10:46:38 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PTopCsfReportBymonth generated by hbm2java
 */
@Entity
@Table(name="P_TOP_CSF_REPORT_BYMONTH")
public class PTopCsfReportBymonth  implements java.io.Serializable {


     private int id;
     private String monthDate;
     private String topType;
     private String topNo;
     private String lastMonthTopNo;
     private String serviceCode;
     private String serviceName;
     private String centerName;
     private BigDecimal csfMonthlyAdjustment;
     private BigDecimal lastCsfMonthlyAdjustment;
     private String adjustmentRateChange;
     private Integer csfAvgTime;
     private Integer lastCsfAvgTime;
     private String avgtimeRateChange;
     private String csfSuccRate;
     private String lastCsfSuccRate;
     private String succRateChage;
     private Date insertDate;

    public PTopCsfReportBymonth() {
    }

	
    public PTopCsfReportBymonth(int id) {
        this.id = id;
    }
    public PTopCsfReportBymonth(int id, String monthDate, String topType, String topNo, String lastMonthTopNo, String serviceCode, String serviceName, String centerName, BigDecimal csfMonthlyAdjustment, BigDecimal lastCsfMonthlyAdjustment, String adjustmentRateChange, Integer csfAvgTime, Integer lastCsfAvgTime, String avgtimeRateChange, String csfSuccRate, String lastCsfSuccRate, String succRateChage, Date insertDate) {
       this.id = id;
       this.monthDate = monthDate;
       this.topType = topType;
       this.topNo = topNo;
       this.lastMonthTopNo = lastMonthTopNo;
       this.serviceCode = serviceCode;
       this.serviceName = serviceName;
       this.centerName = centerName;
       this.csfMonthlyAdjustment = csfMonthlyAdjustment;
       this.lastCsfMonthlyAdjustment = lastCsfMonthlyAdjustment;
       this.adjustmentRateChange = adjustmentRateChange;
       this.csfAvgTime = csfAvgTime;
       this.lastCsfAvgTime = lastCsfAvgTime;
       this.avgtimeRateChange = avgtimeRateChange;
       this.csfSuccRate = csfSuccRate;
       this.lastCsfSuccRate = lastCsfSuccRate;
       this.succRateChage = succRateChage;
       this.insertDate = insertDate;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=8, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="MONTH_DATE", length=8)
    public String getMonthDate() {
        return this.monthDate;
    }
    
    public void setMonthDate(String monthDate) {
        this.monthDate = monthDate;
    }
    
    @Column(name="TOP_TYPE", length=8)
    public String getTopType() {
        return this.topType;
    }
    
    public void setTopType(String topType) {
        this.topType = topType;
    }
    
    @Column(name="TOP_NO", length=32)
    public String getTopNo() {
        return this.topNo;
    }
    
    public void setTopNo(String topNo) {
        this.topNo = topNo;
    }
    
    @Column(name="LAST_MONTH_TOP_NO", length=32)
    public String getLastMonthTopNo() {
        return this.lastMonthTopNo;
    }
    
    public void setLastMonthTopNo(String lastMonthTopNo) {
        this.lastMonthTopNo = lastMonthTopNo;
    }
    
    @Column(name="SERVICE_CODE")
    public String getServiceCode() {
        return this.serviceCode;
    }
    
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }
    
    @Column(name="SERVICE_NAME")
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    
    @Column(name="CENTER_NAME")
    public String getCenterName() {
        return this.centerName;
    }
    
    public void setCenterName(String centerName) {
        this.centerName = centerName;
    }
    
    @Column(name="CSF_MONTHLY_ADJUSTMENT", precision=32, scale=0)
    public BigDecimal getCsfMonthlyAdjustment() {
        return this.csfMonthlyAdjustment;
    }
    
    public void setCsfMonthlyAdjustment(BigDecimal csfMonthlyAdjustment) {
        this.csfMonthlyAdjustment = csfMonthlyAdjustment;
    }
    
    @Column(name="LAST_CSF_MONTHLY_ADJUSTMENT", precision=32, scale=0)
    public BigDecimal getLastCsfMonthlyAdjustment() {
        return this.lastCsfMonthlyAdjustment;
    }
    
    public void setLastCsfMonthlyAdjustment(BigDecimal lastCsfMonthlyAdjustment) {
        this.lastCsfMonthlyAdjustment = lastCsfMonthlyAdjustment;
    }
    
    @Column(name="ADJUSTMENT_RATE_CHANGE", length=32)
    public String getAdjustmentRateChange() {
        return this.adjustmentRateChange;
    }
    
    public void setAdjustmentRateChange(String adjustmentRateChange) {
        this.adjustmentRateChange = adjustmentRateChange;
    }
    
    @Column(name="CSF_AVG_TIME", precision=8, scale=0)
    public Integer getCsfAvgTime() {
        return this.csfAvgTime;
    }
    
    public void setCsfAvgTime(Integer csfAvgTime) {
        this.csfAvgTime = csfAvgTime;
    }
    
    @Column(name="LAST_CSF_AVG_TIME", precision=8, scale=0)
    public Integer getLastCsfAvgTime() {
        return this.lastCsfAvgTime;
    }
    
    public void setLastCsfAvgTime(Integer lastCsfAvgTime) {
        this.lastCsfAvgTime = lastCsfAvgTime;
    }
    
    @Column(name="AVGTIME_RATE_CHANGE", length=32)
    public String getAvgtimeRateChange() {
        return this.avgtimeRateChange;
    }
    
    public void setAvgtimeRateChange(String avgtimeRateChange) {
        this.avgtimeRateChange = avgtimeRateChange;
    }
    
    @Column(name="CSF_SUCC_RATE", length=32)
    public String getCsfSuccRate() {
        return this.csfSuccRate;
    }
    
    public void setCsfSuccRate(String csfSuccRate) {
        this.csfSuccRate = csfSuccRate;
    }
    
    @Column(name="LAST_CSF_SUCC_RATE", length=32)
    public String getLastCsfSuccRate() {
        return this.lastCsfSuccRate;
    }
    
    public void setLastCsfSuccRate(String lastCsfSuccRate) {
        this.lastCsfSuccRate = lastCsfSuccRate;
    }
    
    @Column(name="SUCC_RATE_CHAGE", length=32)
    public String getSuccRateChage() {
        return this.succRateChage;
    }
    
    public void setSuccRateChage(String succRateChage) {
        this.succRateChage = succRateChage;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INSERT_DATE", length=7)
    public Date getInsertDate() {
        return this.insertDate;
    }
    
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }




}


