package com.ai.aiga.domain;
// Generated 2017-6-14 15:31:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SecondCategory generated by hbm2java
 */
@Entity
@Table(name="SECOND_CATEGORY")
public class SecondCategory  implements java.io.Serializable {


     private long secondId;
     private String name;
     private Long rootId;
     private long firstId;

    public SecondCategory() {
    }

	
    public SecondCategory(long secondId, String name, long firstId) {
        this.secondId = secondId;
        this.name = name;
        this.firstId = firstId;
    }
    public SecondCategory(long secondId, String name, Long rootId, long firstId) {
       this.secondId = secondId;
       this.name = name;
       this.rootId = rootId;
       this.firstId = firstId;
    }
   
     @Id 
    @Column(name="SECOND_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getSecondId() {
        return this.secondId;
    }
    
    public void setSecondId(long secondId) {
        this.secondId = secondId;
    }
    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="ROOT_ID", precision=10, scale=0)
    public Long getRootId() {
        return this.rootId;
    }
    
    public void setRootId(Long rootId) {
        this.rootId = rootId;
    }
    
    @Column(name="FIRST_ID", nullable=false, precision=10, scale=0)
    public long getFirstId() {
        return this.firstId;
    }
    
    public void setFirstId(long firstId) {
        this.firstId = firstId;
    }




}


