package com.ai.aiga.domain;
// Generated 2017-2-22 9:11:58 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SysConstant generated by hbm2java
 */
@Entity
@Table(name="SYS_CONSTANT")
public class SysConstant  implements java.io.Serializable {


     private BigDecimal constantId;
     private String categoryName;
     private String category;
     private String show;
     private long value;
     private String other1;
     private String other2;
     private String memo;
     private String author;
     private String remark;
     private String escapeShow;
     private String escapeField;
     private String firstSpell;
     private String fullSpelling;
     private Long status;

    public SysConstant() {
    }

	
    public SysConstant(BigDecimal constantId, String category, long value) {
        this.constantId = constantId;
        this.category = category;
        this.value = value;
    }
    public SysConstant(BigDecimal constantId, String categoryName, String category, String show, long value, String other1, String other2, String memo, String author, String remark, String escapeShow, String escapeField, String firstSpell, String fullSpelling, Long status) {
       this.constantId = constantId;
       this.categoryName = categoryName;
       this.category = category;
       this.show = show;
       this.value = value;
       this.other1 = other1;
       this.other2 = other2;
       this.memo = memo;
       this.author = author;
       this.remark = remark;
       this.escapeShow = escapeShow;
       this.escapeField = escapeField;
       this.firstSpell = firstSpell;
       this.fullSpelling = fullSpelling;
       this.status = status;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="SYS_CONSTANT$SEQ")
     @SequenceGenerator(name="SYS_CONSTANT$SEQ",sequenceName="SYS_CONSTANT$SEQ",allocationSize=1)
    @Column(name="CONSTANT_ID", nullable=false, precision=20, scale=0)
    public BigDecimal getConstantId() {
        return this.constantId;
    }
    
    public void setConstantId(BigDecimal constantId) {
        this.constantId = constantId;
    }
    
    @Column(name="CATEGORY_NAME", length=256)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    
    @Column(name="CATEGORY", nullable=false, length=256)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    
    @Column(name="SHOW", length=256)
    public String getShow() {
        return this.show;
    }
    
    public void setShow(String show) {
        this.show = show;
    }
    
    @Column(name="VALUE", nullable=false, precision=11, scale=0)
    public long getValue() {
        return this.value;
    }
    
    public void setValue(long value) {
        this.value = value;
    }
    
    @Column(name="OTHER1", length=256)
    public String getOther1() {
        return this.other1;
    }
    
    public void setOther1(String other1) {
        this.other1 = other1;
    }
    
    @Column(name="OTHER2", length=256)
    public String getOther2() {
        return this.other2;
    }
    
    public void setOther2(String other2) {
        this.other2 = other2;
    }
    
    @Column(name="MEMO", length=1025)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    
    @Column(name="AUTHOR", length=100)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    
    @Column(name="REMARK", length=1025)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="ESCAPE_SHOW", length=100)
    public String getEscapeShow() {
        return this.escapeShow;
    }
    
    public void setEscapeShow(String escapeShow) {
        this.escapeShow = escapeShow;
    }
    
    @Column(name="ESCAPE_FIELD", length=100)
    public String getEscapeField() {
        return this.escapeField;
    }
    
    public void setEscapeField(String escapeField) {
        this.escapeField = escapeField;
    }
    
    @Column(name="FIRST_SPELL", length=100)
    public String getFirstSpell() {
        return this.firstSpell;
    }
    
    public void setFirstSpell(String firstSpell) {
        this.firstSpell = firstSpell;
    }
    
    @Column(name="FULL_SPELLING", length=200)
    public String getFullSpelling() {
        return this.fullSpelling;
    }
    
    public void setFullSpelling(String fullSpelling) {
        this.fullSpelling = fullSpelling;
    }
    
    @Column(name="STATUS", precision=10, scale=0)
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }




}


