package com.huawei.msp.mmap.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.huawei.msp.mmap.server.domain.AddTaskRsp;
import com.huawei.msp.mmap.server.domain.TaskValue;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MspWebServicePortType", targetNamespace = "http://server.mmap.msp.huawei.com")
public interface MspWebServicePortType {


	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "addTask", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.AddTask")
	@ResponseWrapper(localName = "addTaskResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.AddTaskResponse")
	public AddTaskRsp addTask(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") TaskValue in0);


}
