package com.huawei.msp.mmap.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.huawei.msp.mmap.server.domain.AddPlanRsp;
import com.huawei.msp.mmap.server.domain.AddTaskByFileRsp;
import com.huawei.msp.mmap.server.domain.AddTaskRsp;
import com.huawei.msp.mmap.server.domain.ArrayOfTaskValue;
import com.huawei.msp.mmap.server.domain.BatchAddTaskRsp;
import com.huawei.msp.mmap.server.domain.CommonResponse;
import com.huawei.msp.mmap.server.domain.PlanValue;
import com.huawei.msp.mmap.server.domain.QueryHisTaskReq;
import com.huawei.msp.mmap.server.domain.QueryPlanRsp;
import com.huawei.msp.mmap.server.domain.QueryTaskRsp;
import com.huawei.msp.mmap.server.domain.ReceiveMsgReq;
import com.huawei.msp.mmap.server.domain.ReceiveMsgRsp;
import com.huawei.msp.mmap.server.domain.TaskValue;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MspWebServicePortType", targetNamespace = "http://server.mmap.msp.huawei.com")
public interface MspWebServicePortType {

	/**
	 * 
	 * @param in0
	 * @return returns com.huawei.msp.mmap.server.domain.CommonResponse
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "modifyPlan", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.ModifyPlan")
	@ResponseWrapper(localName = "modifyPlanResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.ModifyPlanResponse")
	public CommonResponse modifyPlan(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") PlanValue in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.huawei.msp.mmap.server.domain.ReceiveMsgRsp
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "receiveMessage", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.ReceiveMessage")
	@ResponseWrapper(localName = "receiveMessageResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.ReceiveMessageResponse")
	public ReceiveMsgRsp receiveMessage(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") ReceiveMsgReq in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.huawei.msp.mmap.server.domain.AddTaskRsp
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "addTask", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.AddTask")
	@ResponseWrapper(localName = "addTaskResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.AddTaskResponse")
	public AddTaskRsp addTask(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") TaskValue in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.huawei.msp.mmap.server.domain.AddPlanRsp
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "addPlan", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.AddPlan")
	@ResponseWrapper(localName = "addPlanResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.AddPlanResponse")
	public AddPlanRsp addPlan(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") PlanValue in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.huawei.msp.mmap.server.domain.QueryTaskRsp
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "queryTask", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.QueryTask")
	@ResponseWrapper(localName = "queryTaskResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.QueryTaskResponse")
	public QueryTaskRsp queryTask(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") String in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.huawei.msp.mmap.server.domain.QueryTaskRsp
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "queryHisTask", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.QueryHisTask")
	@ResponseWrapper(localName = "queryHisTaskResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.QueryHisTaskResponse")
	public QueryTaskRsp queryHisTask(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") QueryHisTaskReq in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.huawei.msp.mmap.server.domain.QueryPlanRsp
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "queryPlan", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.QueryPlan")
	@ResponseWrapper(localName = "queryPlanResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.QueryPlanResponse")
	public QueryPlanRsp queryPlan(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") String in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.huawei.msp.mmap.server.domain.CommonResponse
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "deletePlan", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.DeletePlan")
	@ResponseWrapper(localName = "deletePlanResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.DeletePlanResponse")
	public CommonResponse deletePlan(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") String in0);

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "querySendTask", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.QuerySendTask")
	@ResponseWrapper(localName = "querySendTaskResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.QuerySendTaskResponse")
	public String querySendTask(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") String in0);

	/**
	 * 
	 * @return returns com.huawei.msp.mmap.server.domain.CommonResponse
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "handShake", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.HandShake")
	@ResponseWrapper(localName = "handShakeResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.HandShakeResponse")
	public CommonResponse handShake();

	/**
	 * 
	 * @param in0
	 * @return returns com.huawei.msp.mmap.server.domain.CommonResponse
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "repealTask", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.RepealTask")
	@ResponseWrapper(localName = "repealTaskResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.RepealTaskResponse")
	public CommonResponse repealTask(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") String in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.huawei.msp.mmap.server.domain.AddTaskByFileRsp
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "addTaskByFile", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.AddTaskByFile")
	@ResponseWrapper(localName = "addTaskByFileResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.AddTaskByFileResponse")
	public AddTaskByFileRsp addTaskByFile(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") String in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.huawei.msp.mmap.server.domain.BatchAddTaskRsp
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://server.mmap.msp.huawei.com")
	@RequestWrapper(localName = "addBatchTask", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.AddBatchTask")
	@ResponseWrapper(localName = "addBatchTaskResponse", targetNamespace = "http://server.mmap.msp.huawei.com", className = "com.huawei.msp.mmap.server.AddBatchTaskResponse")
	public BatchAddTaskRsp addBatchTask(
			@WebParam(name = "in0", targetNamespace = "http://server.mmap.msp.huawei.com") ArrayOfTaskValue in0);

}
