package com.huawei.msp.mmap.server;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MspWebService service = new MspWebService();
 * MspWebServicePortType portType = service.getMspWebServiceHttpPort();
 * portType.modifyPlan(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MspWebService", targetNamespace = "http://server.mmap.msp.huawei.com", wsdlLocation = "http://10.70.181.7:8080/MSP/services/MSPWebService?wsdl")
public class MspWebService extends Service {

	private final static URL MSPWEBSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.huawei.msp.mmap.server.MspWebService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.huawei.msp.mmap.server.MspWebService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.70.181.7:8080/MSP/services/MSPWebService?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://10.70.181.7:8080/MSP/services/MSPWebService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MSPWEBSERVICE_WSDL_LOCATION = url;
	}

	public MspWebService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MspWebService() {
		super(MSPWEBSERVICE_WSDL_LOCATION, new QName(
				"http://server.mmap.msp.huawei.com", "MspWebService"));
	}

	/**
	 * 
	 * @return returns MspWebServicePortType
	 */
	@WebEndpoint(name = "MspWebServiceHttpPort")
	public MspWebServicePortType getMspWebServiceHttpPort() {
		return super.getPort(new QName("http://server.mmap.msp.huawei.com",
				"MspWebServiceHttpPort"), MspWebServicePortType.class);
	}

}
