package com.ai.aiga.domain.inspectradar;
// Generated 2018-8-20 17:28:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InspectRadarError generated by hbm2java
 */
@Entity
@Table(name="INSPECT_RADAR_ERROR")
public class InspectRadarError  implements java.io.Serializable {


     private long errId;
     private Long ruleId;
     private Long sysId;
     private String indexName;
     private String indexInfo;
     private String parantName;
     private String indexMark;
     private String indexValue;
     private Date indexTime;
     private String ruleType;
     private String ruleFunction;
     private String ruleValue;
     private Date createTime;
     private String ext1;
     private String ext2;
     private String ext3;

    public InspectRadarError() {
    }

	
    public InspectRadarError(long errId) {
        this.errId = errId;
    }
    public InspectRadarError(long errId, Long ruleId, Long sysId, String indexName, String indexInfo, String parantName, String indexMark, String indexValue, Date indexTime, String ruleType, String ruleFunction, String ruleValue, Date createTime, String ext1, String ext2, String ext3) {
       this.errId = errId;
       this.ruleId = ruleId;
       this.sysId = sysId;
       this.indexName = indexName;
       this.indexInfo = indexInfo;
       this.parantName = parantName;
       this.indexMark = indexMark;
       this.indexValue = indexValue;
       this.indexTime = indexTime;
       this.ruleType = ruleType;
       this.ruleFunction = ruleFunction;
       this.ruleValue = ruleValue;
       this.createTime = createTime;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="INSPECT_RADAR_ERROR$SEQ")
     @SequenceGenerator(name="INSPECT_RADAR_ERROR$SEQ",sequenceName="INSPECT_RADAR_ERROR$SEQ",allocationSize=1)    
    @Column(name="ERR_ID", nullable=false, precision=10, scale=0)
    public long getErrId() {
        return this.errId;
    }
    
    public void setErrId(long errId) {
        this.errId = errId;
    }
    
    @Column(name="RULE_ID", precision=10, scale=0)
    public Long getRuleId() {
        return this.ruleId;
    }
    
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }
    
    @Column(name="SYS_ID", precision=10, scale=0)
    public Long getSysId() {
        return this.sysId;
    }
    
    public void setSysId(Long sysId) {
        this.sysId = sysId;
    }
    
    @Column(name="INDEX_NAME")
    public String getIndexName() {
        return this.indexName;
    }
    
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }
    
    @Column(name="INDEX_INFO", length=2000)
    public String getIndexInfo() {
        return this.indexInfo;
    }
    
    public void setIndexInfo(String indexInfo) {
        this.indexInfo = indexInfo;
    }
    
    @Column(name="PARANT_NAME")
    public String getParantName() {
        return this.parantName;
    }
    
    public void setParantName(String parantName) {
        this.parantName = parantName;
    }
    
    @Column(name="INDEX_MARK")
    public String getIndexMark() {
        return this.indexMark;
    }
    
    public void setIndexMark(String indexMark) {
        this.indexMark = indexMark;
    }
    
    @Column(name="INDEX_VALUE")
    public String getIndexValue() {
        return this.indexValue;
    }
    
    public void setIndexValue(String indexValue) {
        this.indexValue = indexValue;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INDEX_TIME", length=7)
    public Date getIndexTime() {
        return this.indexTime;
    }
    
    public void setIndexTime(Date indexTime) {
        this.indexTime = indexTime;
    }
    
    @Column(name="RULE_TYPE")
    public String getRuleType() {
        return this.ruleType;
    }
    
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType;
    }
    
    @Column(name="RULE_FUNCTION")
    public String getRuleFunction() {
        return this.ruleFunction;
    }
    
    public void setRuleFunction(String ruleFunction) {
        this.ruleFunction = ruleFunction;
    }
    
    @Column(name="RULE_VALUE")
    public String getRuleValue() {
        return this.ruleValue;
    }
    
    public void setRuleValue(String ruleValue) {
        this.ruleValue = ruleValue;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", length=7)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="EXT1")
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT2")
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT3")
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


