package com.ai.aiga.domain.inspectradar;
// Generated 2018-8-20 17:28:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InspectRadarTemp generated by hbm2java
 */
@Entity
@Table(name="INSPECT_RADAR_TEMP")
public class InspectRadarTemp  implements java.io.Serializable {


     private long tempId;
     private String indexName;
     private String indexInfo;
     private String indexType;
     private Long parentId;
     private String indexWeight;
     private Character state;
     private Date createTime;
     private String ext1;
     private String ext2;
     private String ext3;

    public InspectRadarTemp() {
    }

	
    public InspectRadarTemp(long tempId) {
        this.tempId = tempId;
    }
    public InspectRadarTemp(long tempId, String indexName, String indexInfo, String indexType, Long parentId, String indexWeight, Character state, Date createTime, String ext1, String ext2, String ext3) {
       this.tempId = tempId;
       this.indexName = indexName;
       this.indexInfo = indexInfo;
       this.indexType = indexType;
       this.parentId = parentId;
       this.indexWeight = indexWeight;
       this.state = state;
       this.createTime = createTime;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="INSPECT_RADAR_TEMP$SEQ")
     @SequenceGenerator(name="INSPECT_RADAR_TEMP$SEQ",sequenceName="INSPECT_RADAR_TEMP$SEQ",allocationSize=1)    
    @Column(name="TEMP_ID", nullable=false, precision=10, scale=0)
    public long getTempId() {
        return this.tempId;
    }
    
    public void setTempId(long tempId) {
        this.tempId = tempId;
    }
    
    @Column(name="INDEX_NAME")
    public String getIndexName() {
        return this.indexName;
    }
    
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }
    
    @Column(name="INDEX_INFO", length=2000)
    public String getIndexInfo() {
        return this.indexInfo;
    }
    
    public void setIndexInfo(String indexInfo) {
        this.indexInfo = indexInfo;
    }
    
    @Column(name="INDEX_TYPE")
    public String getIndexType() {
        return this.indexType;
    }
    
    public void setIndexType(String indexType) {
        this.indexType = indexType;
    }
    
    @Column(name="PARENT_ID", precision=10, scale=0)
    public Long getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
    
    @Column(name="INDEX_WEIGHT")
    public String getIndexWeight() {
        return this.indexWeight;
    }
    
    public void setIndexWeight(String indexWeight) {
        this.indexWeight = indexWeight;
    }
    
    @Column(name="STATE", length=1)
    public Character getState() {
        return this.state;
    }
    
    public void setState(Character state) {
        this.state = state;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", length=7)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="EXT1")
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT2")
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT3")
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


