<table class="table table-bordered table-condensed table-hover" style="width:3000px;">
    <thead>
        <tr>
            <th>需求提出时间</th>
            <th>软件需求编号</th>
            <th>软件需求名称</th>
			<th>需求来源</th>
            <th>需求级别</th>
            <th>需求优先级</th>
			<th>集团考核</th>
            <th>需求分类</th>
            <th>需求类型</th>
			<th>需求变更类型</th>
            <th>变更原因</th>
            <th>初排时间</th>
			<th>终排时间</th>
            <th>上线时间</th>
            <th style="display:none;">开发任务编号</th>
			<th>开发任务名称</th>
            <th>任务状态</th>
            <th>系统大类</th>
			<th>系统子类</th>
            <th>开发人员</th>
            <th>开发管理员</th>
			<th>需求管理员</th>
            <th>需求申请人</th>
            <th>工作量评估</th>
			<th>初步情况分析</th>
            <th>是否跨周期需求</th>
            <th>是否跨系统联调</th>
			<th>重点需求</th>
            <th>集团需求</th>
            <th>存在数据库脚本</th>
        </tr>
    </thead>
    <tbody>
    {{#each this}}
        <tr>
            <td>{{reqDate}}</td>
            <td>{{reqNo}}</td>
            <td>{{reqName}}</td>
			<td>{{reqOrigin}}</td>
            <td>{{reqLevel}}</td>
            <td>{{reqPriority}}</td>
			<td>{{reqGroupFocus}}</td>
            <td>{{reqCategory}}</td>
            <td>{{reqType}}</td>
            <td>{{reqUpdate}}</td>
			<td>{{reqReason}}</td>
            <td>{{reqFirstDate}}</td>
            <td>{{reqLastDate}}</td>
			<td>{{reqOnlineDate}}</td>
            <td style="display:none;">{{devNo}}</td>
            <td>{{devName}}</td>
			<td>{{devStatus}}</td>
            <td>{{sysName}}</td>
            <td>{{subSysName}}</td>
            <td>{{devStaff}}</td>
			<td>{{devManager}}</td>
            <td>{{reqManager}}</td>
            <td>{{reqStaff}}</td>
			<td>{{devWorkload}}</td>
            <td>{{devAnalyse}}</td>
            <td>{{reqSkippingCycle}}</td>
			<td>{{qaCrossSystem}}</td>
            <td>{{reqImportant}}</td>
            <td>{{reqGroup}}</td>
            <td>{{devDataScript}}</td>
        </tr>
    {{/each}}
    </tbody>
</table>