package com.ai.am.domain;
// Generated 2017-4-26 15:47:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChangePlanOnile generated by hbm2java
 */
@Entity
@Table(name="CHANGE_PLAN_ONILE"
    ,schema="AIGA"
)
public class ChangePlanOnile  implements java.io.Serializable {


     private long onlinePlan;
     private String onlinePlanName;
     private byte planState;
     private String createOpId;
     private Date createDate;
     private Date doneDate;
     private Date planDate;
     private Date truePlanDate;
     private String result;
     private String remark;
     private String ext1;
     private BigDecimal ext2;
     private String ext3;
     private String sign;
     private BigDecimal types;

    public ChangePlanOnile() {
    }

	
    public ChangePlanOnile(long onlinePlan, String onlinePlanName, byte planState) {
        this.onlinePlan = onlinePlan;
        this.onlinePlanName = onlinePlanName;
        this.planState = planState;
    }
    public ChangePlanOnile(long onlinePlan, String onlinePlanName, byte planState, String createOpId, Date createDate, Date doneDate, Date planDate, Date truePlanDate, String result, String remark, String ext1, BigDecimal ext2, String ext3, String sign, BigDecimal types) {
       this.onlinePlan = onlinePlan;
       this.onlinePlanName = onlinePlanName;
       this.planState = planState;
       this.createOpId = createOpId;
       this.createDate = createDate;
       this.doneDate = doneDate;
       this.planDate = planDate;
       this.truePlanDate = truePlanDate;
       this.result = result;
       this.remark = remark;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
       this.sign = sign;
       this.types = types;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="CHANGE_PLAN_ONILE$SEQ")
  	@SequenceGenerator(name="CHANGE_PLAN_ONILE$SEQ",sequenceName="CHANGE_PLAN_ONILE$SEQ",allocationSize=1)
    @Column(name="ONLINE_PLAN", nullable=false, precision=12, scale=0)
    public long getOnlinePlan() {
        return this.onlinePlan;
    }
    
    public void setOnlinePlan(long onlinePlan) {
        this.onlinePlan = onlinePlan;
    }
    
    @Column(name="ONLINE_PLAN_NAME", nullable=false, length=200)
    public String getOnlinePlanName() {
        return this.onlinePlanName;
    }
    
    public void setOnlinePlanName(String onlinePlanName) {
        this.onlinePlanName = onlinePlanName;
    }
    
    @Column(name="PLAN_STATE", nullable=false, precision=2, scale=0)
    public byte getPlanState() {
        return this.planState;
    }
    
    public void setPlanState(byte planState) {
        this.planState = planState;
    }
    
    @Column(name="CREATE_OP_ID", length=200)
    public String getCreateOpId() {
        return this.createOpId;
    }
    
    public void setCreateOpId(String createOpId) {
        this.createOpId = createOpId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DONE_DATE", length=7)
    public Date getDoneDate() {
        return this.doneDate;
    }
    
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PLAN_DATE", length=7)
    public Date getPlanDate() {
        return this.planDate;
    }
    
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TRUE_PLAN_DATE", length=7)
    public Date getTruePlanDate() {
        return this.truePlanDate;
    }
    
    public void setTruePlanDate(Date truePlanDate) {
        this.truePlanDate = truePlanDate;
    }
    
    @Column(name="RESULT", length=2000)
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    
    @Column(name="REMARK", length=2000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="EXT_1", length=4000)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", precision=22, scale=0)
    public BigDecimal getExt2() {
        return this.ext2;
    }
    
    public void setExt2(BigDecimal ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=4000)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }
    
    @Column(name="SIGN", length=2000)
    public String getSign() {
        return this.sign;
    }
    
    public void setSign(String sign) {
        this.sign = sign;
    }
    
    @Column(name="TYPES", precision=22, scale=0)
    public BigDecimal getTypes() {
        return this.types;
    }
    
    public void setTypes(BigDecimal types) {
        this.types = types;
    }




}


