package com.ai.am.domain;
// Generated 2017-3-29 18:07:39 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaAutoBackupDeal generated by hbm2java
 */
@Entity
@Table(name="NA_AUTO_BACKUP_DEAL"
    ,schema="AIGA"
)
public class NaAutoBackupDeal  implements java.io.Serializable {


     private long dealId;
     private String propertyResource;
     private String field1;
     private String field2;
     private String field3;
     private String field4;
     private String field5;
     private String field6;
     private String field7;
     private String field8;
     private String field9;
     private String field10;
     private String regionId;
     private Date createDate;
     private Date dealDate;
     private Long opId;
     private Long orgId;
     private String coverEnv;
     private String errMsg;
     private Byte state;
     private Byte restoreState;

    public NaAutoBackupDeal() {
    }

	
    public NaAutoBackupDeal(long dealId) {
        this.dealId = dealId;
    }
    public NaAutoBackupDeal(long dealId, String propertyResource, String field1, String field2, String field3, String field4, String field5, String field6, String field7, String field8, String field9, String field10, String regionId, Date createDate, Date dealDate, Long opId, Long orgId, String coverEnv, String errMsg, Byte state, Byte restoreState) {
       this.dealId = dealId;
       this.propertyResource = propertyResource;
       this.field1 = field1;
       this.field2 = field2;
       this.field3 = field3;
       this.field4 = field4;
       this.field5 = field5;
       this.field6 = field6;
       this.field7 = field7;
       this.field8 = field8;
       this.field9 = field9;
       this.field10 = field10;
       this.regionId = regionId;
       this.createDate = createDate;
       this.dealDate = dealDate;
       this.opId = opId;
       this.orgId = orgId;
       this.coverEnv = coverEnv;
       this.errMsg = errMsg;
       this.state = state;
       this.restoreState = restoreState;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_AUTO_BACKUP_DEAL$SEQ")
     @SequenceGenerator(name="NA_AUTO_BACKUP_DEAL$SEQ",sequenceName="NA_AUTO_BACKUP_DEAL$SEQ",allocationSize=1)
    @Column(name="DEAL_ID", unique=true, nullable=false, precision=10, scale=0)
    public long getDealId() {
        return this.dealId;
    }
    
    public void setDealId(long dealId) {
        this.dealId = dealId;
    }
    
    @Column(name="PROPERTY_RESOURCE", length=30)
    public String getPropertyResource() {
        return this.propertyResource;
    }
    
    public void setPropertyResource(String propertyResource) {
        this.propertyResource = propertyResource;
    }
    
    @Column(name="FIELD1", length=20)
    public String getField1() {
        return this.field1;
    }
    
    public void setField1(String field1) {
        this.field1 = field1;
    }
    
    @Column(name="FIELD2", length=20)
    public String getField2() {
        return this.field2;
    }
    
    public void setField2(String field2) {
        this.field2 = field2;
    }
    
    @Column(name="FIELD3", length=20)
    public String getField3() {
        return this.field3;
    }
    
    public void setField3(String field3) {
        this.field3 = field3;
    }
    
    @Column(name="FIELD4", length=20)
    public String getField4() {
        return this.field4;
    }
    
    public void setField4(String field4) {
        this.field4 = field4;
    }
    
    @Column(name="FIELD5", length=20)
    public String getField5() {
        return this.field5;
    }
    
    public void setField5(String field5) {
        this.field5 = field5;
    }
    
    @Column(name="FIELD6", length=20)
    public String getField6() {
        return this.field6;
    }
    
    public void setField6(String field6) {
        this.field6 = field6;
    }
    
    @Column(name="FIELD7", length=20)
    public String getField7() {
        return this.field7;
    }
    
    public void setField7(String field7) {
        this.field7 = field7;
    }
    
    @Column(name="FIELD8", length=20)
    public String getField8() {
        return this.field8;
    }
    
    public void setField8(String field8) {
        this.field8 = field8;
    }
    
    @Column(name="FIELD9", length=20)
    public String getField9() {
        return this.field9;
    }
    
    public void setField9(String field9) {
        this.field9 = field9;
    }
    
    @Column(name="FIELD10", length=20)
    public String getField10() {
        return this.field10;
    }
    
    public void setField10(String field10) {
        this.field10 = field10;
    }
    
    @Column(name="REGION_ID", length=6)
    public String getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=11)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DEAL_DATE", length=11)
    public Date getDealDate() {
        return this.dealDate;
    }
    
    public void setDealDate(Date dealDate) {
        this.dealDate = dealDate;
    }
    
    @Column(name="OP_ID", precision=12, scale=0)
    public Long getOpId() {
        return this.opId;
    }
    
    public void setOpId(Long opId) {
        this.opId = opId;
    }
    
    @Column(name="ORG_ID", precision=12, scale=0)
    public Long getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }
    
    @Column(name="COVER_ENV", length=30)
    public String getCoverEnv() {
        return this.coverEnv;
    }
    
    public void setCoverEnv(String coverEnv) {
        this.coverEnv = coverEnv;
    }
    
    @Column(name="ERR_MSG", length=2000)
    public String getErrMsg() {
        return this.errMsg;
    }
    
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg;
    }
    
    @Column(name="STATE", precision=2, scale=0)
    public Byte getState() {
        return this.state;
    }
    
    public void setState(Byte state) {
        this.state = state;
    }
    
    @Column(name="RESTORE_STATE", precision=2, scale=0)
    public Byte getRestoreState() {
        return this.restoreState;
    }
    
    public void setRestoreState(Byte restoreState) {
        this.restoreState = restoreState;
    }




}


