package com.ai.am.domain;
// Generated 2017-4-24 15:40:39 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaCaseConstructionReport generated by hbm2java
 */
@Entity
@Table(name="NA_CASE_CONSTRUCTION_REPORT"
    ,schema="AIGA"
)
public class NaCaseConstructionReport  implements java.io.Serializable {


     private Long realId;
     private Long reportType;
     private String statisticalMonth;
     private Date createTime;
     private Date updateTime;
     private Long sysId;
     private String sysName;
     private Integer funNum;
     private Integer funNumIncr;
     private BigDecimal funCover;
     private BigDecimal funCoverIncr;
     private Integer caseNumQrelease;
     private Integer caseNumIncrQrelease;
     private Integer autoCaseNumQrelease;
     private Integer autoCaseNumIncrQrelease;
     private BigDecimal autoCaseCoverQrelease;
     private BigDecimal autoCaseCoverIncrQrelease;
     private Integer caseNumRelease;
     private Integer caseNumIncrRelease;
     private Integer autoCaseNumRelease;
     private Integer autoCaseNumIncrRelease;
     private BigDecimal autoCaseCoverRelease;
     private BigDecimal autoCaseCoverIncrRelease;
     private Integer busiNum;
     private BigDecimal busiCover;

    public NaCaseConstructionReport() {
    }

	
    public NaCaseConstructionReport(long realId) {
        this.realId = realId;
    }
    public NaCaseConstructionReport(Long realId, Long reportType, String statisticalMonth, Date createTime, Date updateTime, Long sysId, String sysName, Integer funNum, Integer funNumIncr, BigDecimal funCover, BigDecimal funCoverIncr, Integer caseNumQrelease, Integer caseNumIncrQrelease, Integer autoCaseNumQrelease, Integer autoCaseNumIncrQrelease, BigDecimal autoCaseCoverQrelease, BigDecimal autoCaseCoverIncrQrelease, Integer caseNumRelease, Integer caseNumIncrRelease, Integer autoCaseNumRelease, Integer autoCaseNumIncrRelease, BigDecimal autoCaseCoverRelease, BigDecimal autoCaseCoverIncrRelease, Integer busiNum, BigDecimal busiCover) {
       this.realId = realId;
       this.reportType = reportType;
       this.statisticalMonth = statisticalMonth;
       this.createTime = createTime;
       this.updateTime = updateTime;
       this.sysId = sysId;
       this.sysName = sysName;
       this.funNum = funNum;
       this.funNumIncr = funNumIncr;
       this.funCover = funCover;
       this.funCoverIncr = funCoverIncr;
       this.caseNumQrelease = caseNumQrelease;
       this.caseNumIncrQrelease = caseNumIncrQrelease;
       this.autoCaseNumQrelease = autoCaseNumQrelease;
       this.autoCaseNumIncrQrelease = autoCaseNumIncrQrelease;
       this.autoCaseCoverQrelease = autoCaseCoverQrelease;
       this.autoCaseCoverIncrQrelease = autoCaseCoverIncrQrelease;
       this.caseNumRelease = caseNumRelease;
       this.caseNumIncrRelease = caseNumIncrRelease;
       this.autoCaseNumRelease = autoCaseNumRelease;
       this.autoCaseNumIncrRelease = autoCaseNumIncrRelease;
       this.autoCaseCoverRelease = autoCaseCoverRelease;
       this.autoCaseCoverIncrRelease = autoCaseCoverIncrRelease;
       this.busiNum = busiNum;
       this.busiCover = busiCover;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_CASE_CONSTRUCTION$SEQ")
    @SequenceGenerator(name="NA_CASE_CONSTRUCTION$SEQ",sequenceName="NA_CASE_CONSTRUCTION$SEQ",allocationSize=1)
    @Column(name="REAL_ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getRealId() {
        return this.realId;
    }
    
    public void setRealId(Long realId) {
        this.realId = realId;
    }
    
    @Column(name="REPORT_TYPE", precision=2, scale=0)
    public Long getReportType() {
        return this.reportType;
    }
    
    public void setReportType(Long reportType) {
        this.reportType = reportType;
    }
    
    @Column(name="STATISTICAL_MONTH", length=8)
    public String getStatisticalMonth() {
        return this.statisticalMonth;
    }
    
    public void setStatisticalMonth(String statisticalMonth) {
        this.statisticalMonth = statisticalMonth;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", length=7)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_TIME", length=7)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    @Column(name="SYS_ID", precision=20, scale=0)
    public Long getSysId() {
        return this.sysId;
    }
    
    public void setSysId(Long sysId) {
        this.sysId = sysId;
    }
    
    @Column(name="SYS_NAME", length=2000)
    public String getSysName() {
        return this.sysName;
    }
    
    public void setSysName(String sysName) {
        this.sysName = sysName;
    }
    
    @Column(name="FUN_NUM", precision=8, scale=0)
    public Integer getFunNum() {
        return this.funNum;
    }
    
    public void setFunNum(Integer funNum) {
        this.funNum = funNum;
    }
    
    @Column(name="FUN_NUM_INCR", precision=8, scale=0)
    public Integer getFunNumIncr() {
        return this.funNumIncr;
    }
    
    public void setFunNumIncr(Integer funNumIncr) {
        this.funNumIncr = funNumIncr;
    }
    
    @Column(name="FUN_COVER", precision=8, scale=4)
    public BigDecimal getFunCover() {
        return this.funCover;
    }
    
    public void setFunCover(BigDecimal funCover) {
        this.funCover = funCover;
    }
    
    @Column(name="FUN_COVER_INCR", precision=8, scale=4)
    public BigDecimal getFunCoverIncr() {
        return this.funCoverIncr;
    }
    
    public void setFunCoverIncr(BigDecimal funCoverIncr) {
        this.funCoverIncr = funCoverIncr;
    }
    
    @Column(name="CASE_NUM_QRELEASE", precision=8, scale=0)
    public Integer getCaseNumQrelease() {
        return this.caseNumQrelease;
    }
    
    public void setCaseNumQrelease(Integer caseNumQrelease) {
        this.caseNumQrelease = caseNumQrelease;
    }
    
    @Column(name="CASE_NUM_INCR_QRELEASE", precision=8, scale=0)
    public Integer getCaseNumIncrQrelease() {
        return this.caseNumIncrQrelease;
    }
    
    public void setCaseNumIncrQrelease(Integer caseNumIncrQrelease) {
        this.caseNumIncrQrelease = caseNumIncrQrelease;
    }
    
    @Column(name="AUTO_CASE_NUM_QRELEASE", precision=8, scale=0)
    public Integer getAutoCaseNumQrelease() {
        return this.autoCaseNumQrelease;
    }
    
    public void setAutoCaseNumQrelease(Integer autoCaseNumQrelease) {
        this.autoCaseNumQrelease = autoCaseNumQrelease;
    }
    
    @Column(name="AUTO_CASE_NUM_INCR_QRELEASE", precision=8, scale=0)
    public Integer getAutoCaseNumIncrQrelease() {
        return this.autoCaseNumIncrQrelease;
    }
    
    public void setAutoCaseNumIncrQrelease(Integer autoCaseNumIncrQrelease) {
        this.autoCaseNumIncrQrelease = autoCaseNumIncrQrelease;
    }
    
    @Column(name="AUTO_CASE_COVER_QRELEASE", precision=8, scale=4)
    public BigDecimal getAutoCaseCoverQrelease() {
        return this.autoCaseCoverQrelease;
    }
    
    public void setAutoCaseCoverQrelease(BigDecimal autoCaseCoverQrelease) {
        this.autoCaseCoverQrelease = autoCaseCoverQrelease;
    }
    
    @Column(name="AUTO_CASE_COVER_INCR_QRELEASE", precision=8, scale=4)
    public BigDecimal getAutoCaseCoverIncrQrelease() {
        return this.autoCaseCoverIncrQrelease;
    }
    
    public void setAutoCaseCoverIncrQrelease(BigDecimal autoCaseCoverIncrQrelease) {
        this.autoCaseCoverIncrQrelease = autoCaseCoverIncrQrelease;
    }
    
    @Column(name="CASE_NUM_RELEASE", precision=8, scale=0)
    public Integer getCaseNumRelease() {
        return this.caseNumRelease;
    }
    
    public void setCaseNumRelease(Integer caseNumRelease) {
        this.caseNumRelease = caseNumRelease;
    }
    
    @Column(name="CASE_NUM_INCR_RELEASE", precision=8, scale=0)
    public Integer getCaseNumIncrRelease() {
        return this.caseNumIncrRelease;
    }
    
    public void setCaseNumIncrRelease(Integer caseNumIncrRelease) {
        this.caseNumIncrRelease = caseNumIncrRelease;
    }
    
    @Column(name="AUTO_CASE_NUM_RELEASE", precision=8, scale=0)
    public Integer getAutoCaseNumRelease() {
        return this.autoCaseNumRelease;
    }
    
    public void setAutoCaseNumRelease(Integer autoCaseNumRelease) {
        this.autoCaseNumRelease = autoCaseNumRelease;
    }
    
    @Column(name="AUTO_CASE_NUM_INCR_RELEASE", precision=8, scale=0)
    public Integer getAutoCaseNumIncrRelease() {
        return this.autoCaseNumIncrRelease;
    }
    
    public void setAutoCaseNumIncrRelease(Integer autoCaseNumIncrRelease) {
        this.autoCaseNumIncrRelease = autoCaseNumIncrRelease;
    }
    
    @Column(name="AUTO_CASE_COVER_RELEASE", precision=8, scale=4)
    public BigDecimal getAutoCaseCoverRelease() {
        return this.autoCaseCoverRelease;
    }
    
    public void setAutoCaseCoverRelease(BigDecimal autoCaseCoverRelease) {
        this.autoCaseCoverRelease = autoCaseCoverRelease;
    }
    
    @Column(name="AUTO_CASE_COVER_INCR_RELEASE", precision=8, scale=4)
    public BigDecimal getAutoCaseCoverIncrRelease() {
        return this.autoCaseCoverIncrRelease;
    }
    
    public void setAutoCaseCoverIncrRelease(BigDecimal autoCaseCoverIncrRelease) {
        this.autoCaseCoverIncrRelease = autoCaseCoverIncrRelease;
    }
    
    @Column(name="BUSI_NUM", precision=8, scale=0)
    public Integer getBusiNum() {
        return this.busiNum;
    }
    
    public void setBusiNum(Integer busiNum) {
        this.busiNum = busiNum;
    }
    
    @Column(name="BUSI_COVER", precision=8, scale=4)
    public BigDecimal getBusiCover() {
        return this.busiCover;
    }
    
    public void setBusiCover(BigDecimal busiCover) {
        this.busiCover = busiCover;
    }




}


