package com.ai.am.domain;
// Generated 2017-4-24 17:28:08 by Hibernate Tools 3.2.2.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaChangeResultValidate generated by hbm2java
 */
@Entity
@Table(name="NA_CHANGE_RESULT_VALIDATE"
)
public class NaChangeResultValidate  implements java.io.Serializable {


     private Long id;
     private String isChangeValidate;
     private String validateContent;
     private String testTime;
     private String testStep;
     private String testMan;
     private Long planId;
     private String fileName;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaChangeResultValidate() {
    }

	
    public NaChangeResultValidate(Long id) {
        this.id = id;
    }
    public NaChangeResultValidate(Long id, String isChangeValidate, String validateContent, String testTime, String testStep, String testMan, Long planId, String fileName, String ext1, String ext2, String ext3) {
       this.id = id;
       this.isChangeValidate = isChangeValidate;
       this.validateContent = validateContent;
       this.testTime = testTime;
       this.testStep = testStep;
       this.testMan = testMan;
       this.planId = planId;
       this.fileName = fileName;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_CHANGE_RESULT_VALIDATE$SEQ")
     @SequenceGenerator(name="NA_CHANGE_RESULT_VALIDATE$SEQ",sequenceName="NA_CHANGE_RESULT_VALIDATE$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="IS_CHANGE_VALIDATE", length=200)
    public String getIsChangeValidate() {
        return this.isChangeValidate;
    }
    
    public void setIsChangeValidate(String isChangeValidate) {
        this.isChangeValidate = isChangeValidate;
    }
    
    @Column(name="VALIDATE_CONTENT", length=200)
    public String getValidateContent() {
        return this.validateContent;
    }
    
    public void setValidateContent(String validateContent) {
        this.validateContent = validateContent;
    }
    
    @Column(name="TEST_TIME", length=200)
    public String getTestTime() {
        return this.testTime;
    }
    
    public void setTestTime(String testTime) {
        this.testTime = testTime;
    }
    
    @Column(name="TEST_STEP", length=200)
    public String getTestStep() {
        return this.testStep;
    }
    
    public void setTestStep(String testStep) {
        this.testStep = testStep;
    }
    
    @Column(name="TEST_MAN", length=200)
    public String getTestMan() {
        return this.testMan;
    }
    
    public void setTestMan(String testMan) {
        this.testMan = testMan;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="FILE_NAME", length=200)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="EXT_1", length=200)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=200)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=200)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


