package com.ai.am.domain;
// Generated 2017-4-24 15:00:18 by Hibernate Tools 3.2.2.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaChangeContents generated by hbm2java
 */
@Entity
@Table(name="NA_CHANGE_CONTENTS")
public class NaChangeContents  implements java.io.Serializable {


     private Long id;
     private String questionDesc;
     private String changeObject;
     private String sysName;
     private String changeGoal;
     private String changeDangerous;
     private String impactRange;
     private String groupCheckImpact;
     private String groupImpact;
     private String imfoImpact;
     private Long planId;
     private String fileName;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaChangeContents() {
    }

	
    public NaChangeContents(Long id) {
        this.id = id;
    }
    public NaChangeContents(Long id, String questionDesc, String changeObject, String sysName, String changeGoal, String changeDangerous, String impactRange, String groupCheckImpact, String groupImpact, String imfoImpact, Long planId, String fileName, String ext1, String ext2, String ext3) {
       this.id = id;
       this.questionDesc = questionDesc;
       this.changeObject = changeObject;
       this.sysName = sysName;
       this.changeGoal = changeGoal;
       this.changeDangerous = changeDangerous;
       this.impactRange = impactRange;
       this.groupCheckImpact = groupCheckImpact;
       this.groupImpact = groupImpact;
       this.imfoImpact = imfoImpact;
       this.planId = planId;
       this.fileName = fileName;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NA_CHANGE_CONTENTS$SEQ")
  	@SequenceGenerator(name = "NA_CHANGE_CONTENTS$SEQ", sequenceName = "NA_CHANGE_CONTENTS$SEQ", allocationSize = 1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="QUESTION_DESC", length=400)
    public String getQuestionDesc() {
        return this.questionDesc;
    }
    
    public void setQuestionDesc(String questionDesc) {
        this.questionDesc = questionDesc;
    }
    
    @Column(name="CHANGE_OBJECT", length=400)
    public String getChangeObject() {
        return this.changeObject;
    }
    
    public void setChangeObject(String changeObject) {
        this.changeObject = changeObject;
    }
    
    @Column(name="SYS_NAME", length=400)
    public String getSysName() {
        return this.sysName;
    }
    
    public void setSysName(String sysName) {
        this.sysName = sysName;
    }
    
    @Column(name="CHANGE_GOAL", length=400)
    public String getChangeGoal() {
        return this.changeGoal;
    }
    
    public void setChangeGoal(String changeGoal) {
        this.changeGoal = changeGoal;
    }
    
    @Column(name="CHANGE_DANGEROUS", length=400)
    public String getChangeDangerous() {
        return this.changeDangerous;
    }
    
    public void setChangeDangerous(String changeDangerous) {
        this.changeDangerous = changeDangerous;
    }
    
    @Column(name="IMPACT_RANGE", length=400)
    public String getImpactRange() {
        return this.impactRange;
    }
    
    public void setImpactRange(String impactRange) {
        this.impactRange = impactRange;
    }
    
    @Column(name="GROUP_CHECK_IMPACT", length=400)
    public String getGroupCheckImpact() {
        return this.groupCheckImpact;
    }
    
    public void setGroupCheckImpact(String groupCheckImpact) {
        this.groupCheckImpact = groupCheckImpact;
    }
    
    @Column(name="GROUP_IMPACT", length=400)
    public String getGroupImpact() {
        return this.groupImpact;
    }
    
    public void setGroupImpact(String groupImpact) {
        this.groupImpact = groupImpact;
    }
    
    @Column(name="IMFO_IMPACT", length=400)
    public String getImfoImpact() {
        return this.imfoImpact;
    }
    
    public void setImfoImpact(String imfoImpact) {
        this.imfoImpact = imfoImpact;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="FILE_NAME", length=400)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="EXT_1", length=400)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=400)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=400)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


