package com.ai.am.domain;
// Generated 2017-4-11 15:17:20 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaChangeReview generated by hbm2java
 */
@Entity
@Table(name="NA_CHANGE_REVIEW"
    ,schema="AIGA"
)
public class NaChangeReview  implements java.io.Serializable {


     private Long reviewId;
     private Long onlinePlanId;
     private Long conclusion;
     private String reviewResult;
     private Date reviewDate;
     private String reviewer;
     private String remark;
     private String ext1;
     private Long ext2;
     private String ext3;
     private Date planReviewDate ;// 
     private  Long reviewNum ;//

    public NaChangeReview() {
    }

	
    public NaChangeReview(Long reviewId) {
        this.reviewId = reviewId;
    }
    public NaChangeReview(Long reviewId, Long onlinePlanId, Long conclusion, String reviewResult, Date reviewDate, String reviewer, String remark, String ext1, Long ext2, String ext3) {
       this.reviewId = reviewId;
       this.onlinePlanId = onlinePlanId;
       this.conclusion = conclusion;
       this.reviewResult = reviewResult;
       this.reviewDate = reviewDate;
       this.reviewer = reviewer;
       this.remark = remark;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_CHANGE_REVIEW$SEQ")
     @SequenceGenerator(name="NA_CHANGE_REVIEW$SEQ",sequenceName="NA_CHANGE_REVIEW$SEQ",allocationSize=1)
    @Column(name="REVIEW_ID", unique=true, nullable=false, precision=12, scale=0)
    public Long getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(Long reviewId) {
        this.reviewId = reviewId;
    }
    
    @Column(name="PLAN_REVIEW_DATE", precision=12, scale=0)
    public Date getPlanReviewDate() {
        return this.planReviewDate;
    }
    
    public void setPlanReviewDate(Date planReviewDate) {
        this.planReviewDate = planReviewDate;
    }
    
    @Column(name="REVIEW_NUM", precision=12, scale=0)
    public Long getReviewNum() {
        return this.reviewNum;
    }
    
    public void setReviewNum(Long reviewNum) {
        this.reviewNum = reviewNum;
    }
    
    @Column(name="ONLINE_PLAN_ID", precision=12, scale=0)
    public Long getOnlinePlanId() {
        return this.onlinePlanId;
    }
    
    public void setOnlinePlanId(Long onlinePlanId) {
        this.onlinePlanId = onlinePlanId;
    }
    
    @Column(name="CONCLUSION", precision=12, scale=0)
    public Long getConclusion() {
        return this.conclusion;
    }
    
    public void setConclusion(Long conclusion) {
        this.conclusion = conclusion;
    }
    
    @Column(name="REVIEW_RESULT", length=200)
    public String getReviewResult() {
        return this.reviewResult;
    }
    
    public void setReviewResult(String reviewResult) {
        this.reviewResult = reviewResult;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REVIEW_DATE", length=7)
    public Date getReviewDate() {
        return this.reviewDate;
    }
    
    public void setReviewDate(Date reviewDate) {
        this.reviewDate = reviewDate;
    }
    
    @Column(name="REVIEWER", length=200)
    public String getReviewer() {
        return this.reviewer;
    }
    
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer;
    }
    
    @Column(name="REMARK", length=2000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="EXT_1", length=20)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=20)
    public Long getExt2() {
        return this.ext2;
    }
    
    public void setExt2(Long ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=20)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


