package com.ai.am.domain;
// Generated 2017-4-24 15:00:18 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaChangeGoalDevice generated by hbm2java
 */
@Entity
@Table(name="NA_CHANGE_GOAL_DEVICE"
)
public class NaChangeGoalDevice  implements java.io.Serializable {


     private Long id;
     private String resourceType;
     private String deviceName;
     private String ipAddress;
     private String sysName;
     private String searchCode;
     private String changeContent;
     private Long planId;
     private String fileName;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaChangeGoalDevice() {
    }

	
    public NaChangeGoalDevice(Long id) {
        this.id = id;
    }
    public NaChangeGoalDevice(Long id, String resourceType, String deviceName, String ipAddress, String sysName, String searchCode, String changeContent, Long planId, String fileName, String ext1, String ext2, String ext3) {
       this.id = id;
       this.resourceType = resourceType;
       this.deviceName = deviceName;
       this.ipAddress = ipAddress;
       this.sysName = sysName;
       this.searchCode = searchCode;
       this.changeContent = changeContent;
       this.planId = planId;
       this.fileName = fileName;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NA_CHANGE_GOAL_DEVICE$SEQ")
 	@SequenceGenerator(name = "NA_CHANGE_GOAL_DEVICE$SEQ", sequenceName = "NA_CHANGE_GOAL_DEVICE$SEQ", allocationSize = 1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="RESOURCE_TYPE", length=1000)
    public String getResourceType() {
        return this.resourceType;
    }
    
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }
    
    @Column(name="DEVICE_NAME", length=1000)
    public String getDeviceName() {
        return this.deviceName;
    }
    
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }
    
    @Column(name="IP_ADDRESS", length=1000)
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    
    @Column(name="SYS_NAME", length=1000)
    public String getSysName() {
        return this.sysName;
    }
    
    public void setSysName(String sysName) {
        this.sysName = sysName;
    }
    
    @Column(name="SEARCH_CODE", length=1000)
    public String getSearchCode() {
        return this.searchCode;
    }
    
    public void setSearchCode(String searchCode) {
        this.searchCode = searchCode;
    }
    
    @Column(name="CHANGE_CONTENT", length=1000)
    public String getChangeContent() {
        return this.changeContent;
    }
    
    public void setChangeContent(String changeContent) {
        this.changeContent = changeContent;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="FILE_NAME", length=1000)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="EXT_1", length=1000)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=1000)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=1000)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


