package com.ai.am.domain;
// Generated 2017-7-31 11:39:31 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NaIndexAllocation generated by hbm2java
 */
@Entity
@Table(name="NA_INDEX_ALLOCATION")
public class NaIndexAllocation  implements java.io.Serializable {


     private Long kpiId;
     private String kpiName;
     private Byte kpiType;
     private String kpiSql;
     private BigDecimal value;
     private String icon;
     private String bgColor;
     private Long isShow;
     private Date createDate;
     private Date doneDate;
     private Long opId;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaIndexAllocation() {
    }

	
    public NaIndexAllocation(Long kpiId) {
        this.kpiId = kpiId;
    }
    public NaIndexAllocation(Long kpiId, String kpiName, Byte kpiType, String kpiSql, BigDecimal value, String icon, String bgColor, Long isShow, Date createDate, Date doneDate, Long opId, String ext1, String ext2, String ext3,short isDefault) {
       this.kpiId = kpiId;
       this.kpiName = kpiName;
       this.kpiType = kpiType;
       this.kpiSql = kpiSql;
       this.value = value;
       this.icon = icon;
       this.bgColor = bgColor;
       this.isShow = isShow;
       this.createDate = createDate;
       this.doneDate = doneDate;
       this.opId = opId;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_INDEX_ALLOCATION$SEQ")
    @SequenceGenerator(name="NA_INDEX_ALLOCATION$SEQ",sequenceName="NA_INDEX_ALLOCATION$SEQ",allocationSize=1)
    @Column(name="KPI_ID", unique=true, nullable=false, precision=14, scale=0)
    public Long getKpiId() {
        return this.kpiId;
    }
    
    public void setKpiId(Long kpiId) {
        this.kpiId = kpiId;
    }
    
    @Column(name="KPI_NAME", length=400)
    public String getKpiName() {
        return this.kpiName;
    }
    
    public void setKpiName(String kpiName) {
        this.kpiName = kpiName;
    }
    
    @Column(name="KPI_TYPE", precision=2, scale=0)
    public Byte getKpiType() {
        return this.kpiType;
    }
    
    public void setKpiType(Byte kpiType) {
        this.kpiType = kpiType;
    }
    
    @Column(name="KPI_SQL", length=4000)
    public String getKpiSql() {
        return this.kpiSql;
    }
    
    public void setKpiSql(String kpiSql) {
        this.kpiSql = kpiSql;
    }
    
    @Column(name="VALUE", precision=14, scale=0)
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }
    
    @Column(name="ICON", length=400)
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
    
    @Column(name="BG_COLOR", length=400)
    public String getBgColor() {
        return this.bgColor;
    }
    
    public void setBgColor(String bgColor) {
        this.bgColor = bgColor;
    }
    
    @Column(name="IS_SHOW", precision=2, scale=0)
    public Long getIsShow() {
        return this.isShow;
    }
    
    public void setIsShow(Long isShow) {
        this.isShow = isShow;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE", length=7)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DONE_DATE", length=7)
    public Date getDoneDate() {
        return this.doneDate;
    }
    
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }
    
    @Column(name="OP_ID", precision=14, scale=0)
    public Long getOpId() {
        return this.opId;
    }
    
    public void setOpId(Long opId) {
        this.opId = opId;
    }
    
    @Column(name="EXT_1", length=1000)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=1000)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=1000)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }

}


