package com.ai.am.domain;
// Generated 2017-4-17 12:30:36 by Hibernate Tools 3.2.2.GA




import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * NaReleaseReport generated by hbm2java
 */
@Entity
@Table(name="NA_RELEASE_REPORT"
    ,schema="AIGA"
)
public class NaReleaseReport  {


     private Long reportId;
     private Long onlinePlanId;
     private String onlinePlanName;
     private Long taskId;
     private String taskName;
     @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
     private Date releaseDate;
     private String applicationName;
     @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
     private Date startTime;
     @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
     private Date finishTime;
     private String duration;

    public NaReleaseReport() {
    }

	
    public NaReleaseReport(Long reportId) {
        this.reportId = reportId;
    }
    public NaReleaseReport(Long reportId, Long onlinePlanId, String onlinePlanName, Long taskId, String taskName, Date releaseDate, String applicationName, Date startTime, Date finishTime, String duration) {
       this.reportId = reportId;
       this.onlinePlanId = onlinePlanId;
       this.onlinePlanName = onlinePlanName;
       this.taskId = taskId;
       this.taskName = taskName;
       this.releaseDate = releaseDate;
       this.applicationName = applicationName;
       this.startTime = startTime;
       this.finishTime = finishTime;
       this.duration = duration;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_RELEASE_REPORT$SEQ")
     @SequenceGenerator(name="NA_RELEASE_REPORT$SEQ",sequenceName="NA_RELEASE_REPORT$SEQ",allocationSize=1)
    @Column(name="REPORT_ID", precision=12, scale=0)
    public Long getReportId() {
        return this.reportId;
    }
    
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }
    
    @Column(name="ONLINE_PLAN_ID", precision=22, scale=0)
    public Long getOnlinePlanId() {
        return this.onlinePlanId;
    }
    
    public void setOnlinePlanId(Long onlinePlanId) {
        this.onlinePlanId = onlinePlanId;
    }
    
    @Column(name="ONLINE_PLAN_NAME", length=200)
    public String getOnlinePlanName() {
        return this.onlinePlanName;
    }
    
    public void setOnlinePlanName(String onlinePlanName) {
        this.onlinePlanName = onlinePlanName;
    }
    
    @Column(name="TASK_ID", precision=22, scale=0)
    public Long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }
    
    @Column(name="TASK_NAME", length=200)
    public String getTaskName() {
        return this.taskName;
    }
    
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RELEASE_DATE", length=7)
    public Date getReleaseDate() {
        return this.releaseDate;
    }
    
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }
    
    @Column(name="APPLICATION_NAME")
    public String getApplicationName() {
        return this.applicationName;
    }
    
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_TIME", length=7)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FINISH_TIME", length=7)
    public Date getFinishTime() {
        return this.finishTime;
    }
    
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }
    
    @Column(name="DURATION")
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }




}


