package com.ai.am.domain;
// Generated 2017-4-24 15:00:18 by Hibernate Tools 3.2.2.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaRollbackMethod generated by hbm2java
 */
@Entity
@Table(name="NA_ROLLBACK_METHOD"
)
public class NaRollbackMethod  implements java.io.Serializable {


     private Long id;
     private String isRollback;
     private String rollbackStep;
     private String rollbackPerson;
     private String startRollbackTime;
     private String stopRollbackTime;
     private String rollbackScript;
     private Long planId;
     private String fileName;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaRollbackMethod() {
    }

	
    public NaRollbackMethod(Long id) {
        this.id = id;
    }
    public NaRollbackMethod(Long id, String isRollback, String rollbackStep, String rollbackPerson, String startRollbackTime, String stopRollbackTime, String rollbackScript, Long planId, String fileName, String ext1, String ext2, String ext3) {
       this.id = id;
       this.isRollback = isRollback;
       this.rollbackStep = rollbackStep;
       this.rollbackPerson = rollbackPerson;
       this.startRollbackTime = startRollbackTime;
       this.stopRollbackTime = stopRollbackTime;
       this.rollbackScript = rollbackScript;
       this.planId = planId;
       this.fileName = fileName;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_ROLLBACK_METHOD$SEQ")
     @SequenceGenerator(name="NA_ROLLBACK_METHOD$SEQ",sequenceName="NA_ROLLBACK_METHOD$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="IS_ROLLBACK", length=100)
    public String getIsRollback() {
        return this.isRollback;
    }
    
    public void setIsRollback(String isRollback) {
        this.isRollback = isRollback;
    }
    
    @Column(name="ROLLBACK_STEP", length=100)
    public String getRollbackStep() {
        return this.rollbackStep;
    }
    
    public void setRollbackStep(String rollbackStep) {
        this.rollbackStep = rollbackStep;
    }
    
    @Column(name="ROLLBACK_PERSON", length=100)
    public String getRollbackPerson() {
        return this.rollbackPerson;
    }
    
    public void setRollbackPerson(String rollbackPerson) {
        this.rollbackPerson = rollbackPerson;
    }
    
    @Column(name="START_ROLLBACK_TIME", length=100)
    public String getStartRollbackTime() {
        return this.startRollbackTime;
    }
    
    public void setStartRollbackTime(String startRollbackTime) {
        this.startRollbackTime = startRollbackTime;
    }
    
    @Column(name="STOP_ROLLBACK_TIME", length=100)
    public String getStopRollbackTime() {
        return this.stopRollbackTime;
    }
    
    public void setStopRollbackTime(String sopRollbackTime) {
        this.stopRollbackTime = sopRollbackTime;
    }
    
    @Column(name="ROLLBACK_SCRIPT", length=100)
    public String getRollbackScript() {
        return this.rollbackScript;
    }
    
    public void setRollbackScript(String rollbackScript) {
        this.rollbackScript = rollbackScript;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="FILE_NAME", length=100)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="EXT_1", length=100)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=100)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=100)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


