package com.ai.am.domain;
// Generated 2017-4-13 15:56:17 by Hibernate Tools 3.2.2.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaServiceChangeOnlineList generated by hbm2java
 */
@Entity
@Table(name="NA_SERVICE_CHANGE_ONLINE_LIST"
)
public class NaServiceChangeOnlineList  implements java.io.Serializable {


     private Long id;
     private String changeType;
     private String serviceName;
     private String seriviceId;
     private String requireId;
     private String taskId;
     private String sysName;
     private String sysSubName;
     private String servicePrivideSystem;
     private String testResult;
     private String devMan;
     private String requireMan;
     private String remark;
     private Long planId;
     private String ext1;
     private String ext2;
     private String ext3;

    public NaServiceChangeOnlineList() {
    }

	
    public NaServiceChangeOnlineList(Long id) {
        this.id = id;
    }
    public NaServiceChangeOnlineList(Long id, String changeType, String serviceName, String seriviceId, String requireId, String taskId, String sysName, String sysSubName, String servicePrivideSystem, String testResult, String devMan, String requireMan, String remark, Long planId, String ext1, String ext2, String ext3) {
       this.id = id;
       this.changeType = changeType;
       this.serviceName = serviceName;
       this.seriviceId = seriviceId;
       this.requireId = requireId;
       this.taskId = taskId;
       this.sysName = sysName;
       this.sysSubName = sysSubName;
       this.servicePrivideSystem = servicePrivideSystem;
       this.testResult = testResult;
       this.devMan = devMan;
       this.requireMan = requireMan;
       this.remark = remark;
       this.planId = planId;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_SERVICE_CHANGE_ONLINE$SEQ")
     @SequenceGenerator(name="NA_SERVICE_CHANGE_ONLINE$SEQ",sequenceName="NA_SERVICE_CHANGE_ONLINE$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="CHANGE_TYPE", length=200)
    public String getChangeType() {
        return this.changeType;
    }
    
    public void setChangeType(String changeType) {
        this.changeType = changeType;
    }
    
    @Column(name="SERVICE_NAME", length=200)
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    
    @Column(name="SERIVICE_ID", length=100)
    public String getSeriviceId() {
        return this.seriviceId;
    }
    
    public void setSeriviceId(String seriviceId) {
        this.seriviceId = seriviceId;
    }
    
    @Column(name="REQUIRE_ID", length=100)
    public String getRequireId() {
        return this.requireId;
    }
    
    public void setRequireId(String requireId) {
        this.requireId = requireId;
    }
    
    @Column(name="TASK_ID", length=100)
    public String getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }
    
    @Column(name="SYS_NAME", length=100)
    public String getSysName() {
        return this.sysName;
    }
    
    public void setSysName(String sysName) {
        this.sysName = sysName;
    }
    
    @Column(name="SYS_SUB_NAME", length=100)
    public String getSysSubName() {
        return this.sysSubName;
    }
    
    public void setSysSubName(String sysSubName) {
        this.sysSubName = sysSubName;
    }
    
    @Column(name="SERVICE_PRIVIDE_SYSTEM", length=100)
    public String getServicePrivideSystem() {
        return this.servicePrivideSystem;
    }
    
    public void setServicePrivideSystem(String servicePrivideSystem) {
        this.servicePrivideSystem = servicePrivideSystem;
    }
    
    @Column(name="TEST_RESULT", length=4000)
    public String getTestResult() {
        return this.testResult;
    }
    
    public void setTestResult(String testResult) {
        this.testResult = testResult;
    }
    
    @Column(name="DEV_MAN", length=100)
    public String getDevMan() {
        return this.devMan;
    }
    
    public void setDevMan(String devMan) {
        this.devMan = devMan;
    }
    
    @Column(name="REQUIRE_MAN", length=100)
    public String getRequireMan() {
        return this.requireMan;
    }
    
    public void setRequireMan(String requireMan) {
        this.requireMan = requireMan;
    }
    
    @Column(name="REMARK", length=4000)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="PLAN_ID", precision=22, scale=0)
    public Long getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Long planId) {
        this.planId = planId;
    }
    
    @Column(name="EXT_1", length=100)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=100)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=100)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }




}


