package com.ai.am.domain;
// Generated 2017-4-27 15:07:17 by Hibernate Tools 3.2.2.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NaSystemInterfaceAddress generated by hbm2java
 */
@Entity
@Table(name="NA_SYSTEM_INTERFACE_ADDRESS"
)
public class NaSystemInterfaceAddress  implements java.io.Serializable {


     private Long id;
     private String sysName;
     private String interAddress;
     private String paramers;
     private String ext1;
     private String ext2;
     private String ext3;
     private String serviceType;
     private String interfaceType;
     private String requestType;

    public NaSystemInterfaceAddress() {
    }

	
    public NaSystemInterfaceAddress(Long id) {
        this.id = id;
    }
    public NaSystemInterfaceAddress(Long id, String sysName, String interAddress, String paramers, String ext1, String ext2, String ext3, String serviceType, String interfaceType, String requestType) {
       this.id = id;
       this.sysName = sysName;
       this.interAddress = interAddress;
       this.paramers = paramers;
       this.ext1 = ext1;
       this.ext2 = ext2;
       this.ext3 = ext3;
       this.serviceType = serviceType;
       this.interfaceType = interfaceType;
       this.requestType = requestType;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="NA_SYSTEM_INTERFACE_ADDRESS$SEQ")
     @SequenceGenerator(name="NA_SYSTEM_INTERFACE_ADDRESS$SEQ",sequenceName="NA_SYSTEM_INTERFACE_ADDRESS$SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="SYS_NAME", length=2000)
    public String getSysName() {
        return this.sysName;
    }
    
    public void setSysName(String sysName) {
        this.sysName = sysName;
    }
    
    @Column(name="INTER_ADDRESS", length=2000)
    public String getInterAddress() {
        return this.interAddress;
    }
    
    public void setInterAddress(String interAddress) {
        this.interAddress = interAddress;
    }
    
    @Column(name="PARAMERS", length=2000)
    public String getParamers() {
        return this.paramers;
    }
    
    public void setParamers(String paramers) {
        this.paramers = paramers;
    }
    
    @Column(name="EXT_1", length=2000)
    public String getExt1() {
        return this.ext1;
    }
    
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }
    
    @Column(name="EXT_2", length=2000)
    public String getExt2() {
        return this.ext2;
    }
    
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
    
    @Column(name="EXT_3", length=2000)
    public String getExt3() {
        return this.ext3;
    }
    
    public void setExt3(String ext3) {
        this.ext3 = ext3;
    }
    
    @Column(name="SERVICE_TYPE", length=2000)
    public String getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }
    
    @Column(name="INTERFACE_TYPE", length=2000)
    public String getInterfaceType() {
        return this.interfaceType;
    }
    
    public void setInterfaceType(String interfaceType) {
        this.interfaceType = interfaceType;
    }
    
    @Column(name="REQUEST_TYPE", length=2000)
    public String getRequestType() {
        return this.requestType;
    }
    
    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }




}


