package com.ai.am.domain;
// Generated 2017-6-29 17:18:05 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Root generated by hbm2java
 */
@Entity
@Table(name="ROOT")
public class Root  implements java.io.Serializable {


     private long quesType;
     private String name;

    public Root() {
    }

	
    public Root(long quesType) {
        this.quesType = quesType;
    }
    public Root(long quesType, String name) {
       this.quesType = quesType;
       this.name = name;
    }
   
     @Id 
    @Column(name="QUES_TYPE", unique=true, nullable=false, precision=10, scale=0)
    public long getQuesType() {
        return this.quesType;
    }
    
    public void setQuesType(long quesType) {
        this.quesType = quesType;
    }
    
    @Column(name="NAME", length=10)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

}


