package com.ai.am.domain;
// Generated 2017-2-17 15:47:35 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysRoleStationtype generated by hbm2java
 */
@Entity
@Table(name = "SYS_ROLE_STATIONTYPE")
public class SysRoleStationtype implements java.io.Serializable {

	private long roleStationtypeRelatId;
	private Long roleId;
	private Long stationTypeId;
	private Character isAuthor;
	private Character isRealOperation;
	private String notes;
	private Byte state;
	private Long doneCode;
	private Date createDate;
	private Date doneDate;
	private Date validDate;
	private Date expireDate;
	private Long opId;
	private Long orgId;

	public SysRoleStationtype() {
	}

	public SysRoleStationtype(long roleStationtypeRelatId) {
		this.roleStationtypeRelatId = roleStationtypeRelatId;
	}

	public SysRoleStationtype(long roleStationtypeRelatId, Long roleId, Long stationTypeId, Character isAuthor,
			Character isRealOperation, String notes, Byte state, Long doneCode, Date createDate, Date doneDate,
			Date validDate, Date expireDate, Long opId, Long orgId) {
		this.roleStationtypeRelatId = roleStationtypeRelatId;
		this.roleId = roleId;
		this.stationTypeId = stationTypeId;
		this.isAuthor = isAuthor;
		this.isRealOperation = isRealOperation;
		this.notes = notes;
		this.state = state;
		this.doneCode = doneCode;
		this.createDate = createDate;
		this.doneDate = doneDate;
		this.validDate = validDate;
		this.expireDate = expireDate;
		this.opId = opId;
		this.orgId = orgId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SYS_ROLE_STATIONTYPE$SEQ")
	@SequenceGenerator(name = "SYS_ROLE_STATIONTYPE$SEQ", sequenceName = "SYS_ROLE_STATIONTYPE$SEQ", allocationSize = 1)
	@Column(name = "ROLE_STATIONTYPE_RELAT_ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getRoleStationtypeRelatId() {
		return this.roleStationtypeRelatId;
	}

	public void setRoleStationtypeRelatId(long roleStationtypeRelatId) {
		this.roleStationtypeRelatId = roleStationtypeRelatId;
	}

	@Column(name = "ROLE_ID", precision = 12, scale = 0)
	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "STATION_TYPE_ID", precision = 12, scale = 0)
	public Long getStationTypeId() {
		return this.stationTypeId;
	}

	public void setStationTypeId(Long stationTypeId) {
		this.stationTypeId = stationTypeId;
	}

	@Column(name = "IS_AUTHOR", length = 1)
	public Character getIsAuthor() {
		return this.isAuthor;
	}

	public void setIsAuthor(Character isAuthor) {
		this.isAuthor = isAuthor;
	}

	@Column(name = "IS_REAL_OPERATION", length = 1)
	public Character getIsRealOperation() {
		return this.isRealOperation;
	}

	public void setIsRealOperation(Character isRealOperation) {
		this.isRealOperation = isRealOperation;
	}

	@Column(name = "NOTES", length = 100)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "STATE", precision = 2, scale = 0)
	public Byte getState() {
		return this.state;
	}

	public void setState(Byte state) {
		this.state = state;
	}

	@Column(name = "DONE_CODE", precision = 12, scale = 0)
	public Long getDoneCode() {
		return this.doneCode;
	}

	public void setDoneCode(Long doneCode) {
		this.doneCode = doneCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DONE_DATE", length = 7)
	public Date getDoneDate() {
		return this.doneDate;
	}

	public void setDoneDate(Date doneDate) {
		this.doneDate = doneDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VALID_DATE", length = 7)
	public Date getValidDate() {
		return this.validDate;
	}

	public void setValidDate(Date validDate) {
		this.validDate = validDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIRE_DATE", length = 7)
	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	@Column(name = "OP_ID", precision = 12, scale = 0)
	public Long getOpId() {
		return this.opId;
	}

	public void setOpId(Long opId) {
		this.opId = opId;
	}

	@Column(name = "ORG_ID", precision = 12, scale = 0)
	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

}
